### ISSUE TITLE
Material select now shown when used with sidebar

### ISSUE THREAD

**Issue by pantonis** [angular/material2#10105]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When clicked select box should open

#### What is the current behavior?
When clicked select box is not shown.

#### What are the steps to reproduce?
I am using primeng [sidebar](https://www.primefaces.org/primeng/#/sidebar) component. On that component I add a material select box. When I click on the sidebar it opens up and then click on the material select box. Nothing appears. When I close sidebar I see the opened select box below it.

#### What is the use-case or motivation for changing an existing behavior?
Bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.0, material 5.0.3, Windows 10, TS:2.4.2, all browsers

**Comment by crisbeto** [comment]
It looks like PrimeNG set their sidebar `z-index` to 11002, whereas all Material overlays have a `z-index` of 1000. Closing since Material isn't built to work with PrimeNG. You should be able to work around it in your app by setting `z-index` of the `.cdk-overlay-container` to something higher than the sidebar's.

**Comment by pantonis** [comment]
@crisbeto thanks for your help
