### ISSUE TITLE
required doesn't work with mat-select if template-driven style used

### ISSUE THREAD

**Issue by kodwi** [angular/material2#10136]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

The `required` validator has to work as expected.

#### What is the current behavior?

If you change the selection, there is no any effect.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-jtahpy

#### What is the use-case or motivation for changing an existing behavior?

Incorrect behaviour.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material 5.2.1+

#### Is there anything else we should know?

If I use reactive form, the behaviour is correct. But I used to use template-driven.

**Comment by crisbeto** [comment]
That's because you don't have an `ngModel` on it. [Here's a forked example that works](https://stackblitz.com/edit/angular-jtahpy-jws6yk?file=app/select-hint-error-example.html).

**Comment by aelkoussy** [comment]
In case someone else has this issue in future, you have to use **ngModel** as said by @crisbeto & you have to give a name attribute to the control so that angular create a FormControl.

You can refer to this [stackoverflow question ](https://stackoverflow.com/questions/50087495/angular-5-material-dropdown-select-required-validation-is-not-working/50087824#50087824)about the same issue
