### ISSUE TITLE
mat-progress-bar Indeterminate mode bad animation when long process is made

### ISSUE THREAD

**Issue by badcoder28** [angular/material2#10234]
#### Bug, feature request, or proposal:
Bug? 

#### What is the expected behavior?
Smooth animation flow of progressbar despite long process.

#### What is the current behavior?
Progressbar animation is stretching in the same particular place  and not moving.

#### What are the steps to reproduce?
Just simply add a for loop process with max 100k items iteration. <br/>
[Demo](https://bad-matprogressbar-animation-behaviour.stackblitz.io) and  [Editor](https://stackblitz.com/edit/bad-matprogressbar-animation-behaviour) link

#### What is the use-case or motivation for changing an existing behavior?
Better UI experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular v5.2.4
Material v5.2.1
Windows 10 64 bit
Typescript 2.4.2
Chrome Version 64.0.3282.167

#### Is there anything else we should know?
Nothing else

**Comment by josephperrott** [comment]
Unfortunately, because of javascript's single threadedness, there is not anything we can do to prevent the animation from being affected by other things running in the UI thread.

To prevent this kind of issue from appearing, you will need to split you long running tasks into something asycronous, or use something akin to service workers to move the processing outside of the single UI thread.

**Comment by AskYous** [comment]
I'm having this problem too. When my data comes in from a web service, I have to process it which then causes this issue.
