### ISSUE TITLE
apply class on mat-menu cdk overlay

### ISSUE THREAD

**Issue by jimitit** [angular/material2#10312]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
Allow applying class on cdk overlay of mat-menu

#### What is the current behavior?
Currently, there is no way to apply class on cdk overlay of mat-menu

**Comment by crisbeto** [comment]
See the discussion on https://github.com/angular/material2/issues/10062.

**Comment by fenta23** [comment]
it's nice that you guys addressed this feature. But would it be possible to merge it in the current stable version published on npm?

MaterialDesignGuid advice to add a semi transparent white overlay on mobile devices behind floating action buttons menues. With this feature you can add such a class on the cdk overlay.

Because Angular 6 is still rc and a lot of modules are not adopt to it, i can not switch to your latest version.

Or do you have an advice how to get this in 5.2.5 ?

Thanks, Micha.
