### ISSUE TITLE
Checkbox Check Bug

### ISSUE THREAD

**Issue by flaglerkid** [angular/material2#10320]
#### Bug, feature request, or proposal:
Bug: The checkboxes do not actually check, even though their value and click event is rendered correctly. I am creating the check boxes from an ng-for loop and associating them with a form group and form controls (there will be additional validation and dynamic funkiness later but for now it is just basic overkill).

#### What is the expected behavioror?
Checkbox will toggle visually once clicked

#### What is the current behavior?
Checkbox remains blank even though value is true.

#### What are the steps to reproduce?
CSS Grid: https://angular-yc9efv-qhovd8.stackblitz.io
HTML Table: https://angular-yc9efv.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
Check goes in the box

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest All.

**Comment by crisbeto** [comment]
It's because you're setting a class on the checkbox like this: `class="{{'checkbox-' + item.designator}}"`. What it ends up doing is that it'll override all of the Material classes on the checkbox element. You can assign the class like this to avoid the issue: `[ngClass]="'checkbox-' + item.designator"`.
