### ISSUE TITLE
trigger.autocomplete.closed only reacts to first autocomplete element in html

### ISSUE THREAD

**Issue by pawmel** [angular/material2#10412]
#### Bug, feature request, or proposal:

bug - autocomplete.closed  observable reacts only to first autocomplete element on html

#### What is the expected behavior?

to react on all autocomplete elements

#### What is the current behavior?

reacts to only first element

#### What are the steps to reproduce?

https://stackblitz.com/edit/autocomplete-force-selection-tests-whm4cj

#### What is the use-case or motivation for changing an existing behavior?

if user select nothing - it should reset the autocomplete element.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Current build: 6.0.0-beta.2

**Comment by crisbeto** [comment]
Can you elaborate how to reproduce the issue?

**Comment by pawmel** [comment]
@crisbeto  you have to start typing something but dont select.

value of the input should reset like in the first autocomplete element if you choose nothing

**Comment by crisbeto** [comment]
Your issue comes from the fact that you've got two instances of `MatAutocompleteTrigger` whereas the `@ViewChild` only picks up the first one, e.g. if you remove the first one, the last will start working. You can fix it either by binding to `(closed)` in the template or using `@ViewChildren` to get both autocomplete trigger instances.
