### ISSUE TITLE
mat-sort-header not working when using ng-content

### ISSUE THREAD

**Issue by frikkievb** [angular/material2#10446]
#### Bug, feature request, or proposal:
When including content for a table using ng-content - the mat-sort-header is not working.

#### What is the expected behavior?
Mat-sort-header to be working when including row definitions via ng-content.

#### What is the current behavior?
Rows are rendered with ng-content but the sorting is not working.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://angular-klhdhh.stackblitz.io<br/>

https://stackblitz.com/edit/angular-klhdhh

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/animations": "^5.2.2",
    "@angular/cdk": "^5.2.2",
    "@angular/common": "^5.2.2",
    "@angular/compiler": "^5.2.2",
    "@angular/core": "^5.2.2",
    "@angular/flex-layout": "^2.0.0-beta.12",
    "@angular/forms": "^5.2.2",
    "@angular/http": "^5.2.2",
    "@angular/material": "^5.2.2",
    "@angular/platform-browser": "^5.2.2",
    "@angular/platform-browser-dynamic": "^5.2.2",
    "@angular/router": "^5.2.2",
"typescript": "~2.4.2"
"@angular/cli": "^1.6.3",
"@angular/compiler-cli": "^5.2.2",

**Comment by frikkievb** [comment]
Hi, hope you are well.  Is there any feedback on this problem maybe? :)

**Comment by andrewseguin** [comment]
In your example, there are two instances of `MatSort`. The app component had one on the grid, which was being registered to by the sort header. The table had its own sort that was connected to the data source but was not registered to.

To resolve this, only have one MatSort: https://stackblitz.com/edit/angular-vze9r3?file=app/ics-module/ics-datagrid.component.ts

I changed it so that the data source is provided the sort through `ContentChild`

**Comment by frikkievb** [comment]
Thank you very much.  I missed that.
