### ISSUE TITLE
MatHorizontalStepper not validating all required fields

### ISSUE THREAD

**Issue by matthews90** [angular/material2#10563]
#### Bug, feature request, or proposal:
I am using matHorizontalStepper with linear mode is on. 
On step 1 I have a form with two inputs which are required. But stepper checks if only one required input is filled. It's enough for stepper that user filled only one required field and let the user go for the step 2.

#### What is the expected behavior?
All required input/fields should be validated/filled before allow to see step 2.

#### What is the current behavior?
If user fill only one required input stepper allows to see step 2.

#### What are the steps to reproduce?
Here's what I'm talking about https://angular-ugvs4m.stackblitz.io. Fill only one required input and you will be able to see step 2

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Material 5.2.4 with Angular 4/5. Chrome tested.

**Comment by crisbeto** [comment]
That's because you've got both the first and last name fields pointing to the same form control (`firstCtrl`). Note how the errors will get cleared from one once you fill out the other. [Here's a fork of your example](https://stackblitz.com/edit/angular-ugvs4m-xpt66n?file=app/stepper-overview-example.ts) that shows it working by having separate controls for the different form fields.

**Comment by matthews90** [comment]
Oh, sorry, thanks
