### ISSUE TITLE
Mat-Table shows empty cells when observable if fed by non-angular event

### ISSUE THREAD

**Issue by konsultaner** [angular/material2#10587]
I used the current stackblitz temple to create the [reproducer](https://github.com/angular/material2/files/1852691/reproducer.zip) that connects to a demo websocket server to get the issue working.

The problem is that I use an `Observable` as datasource in a mat-table element. The observables `Subject` is fed by a [when.js](https://github.com/cujojs/when) deferred object like this:

```js
// in my reproducer in src/app/_services/user-data.service.ts:19-40
someLib
    .call().then(() => {
        mySubject.next([new User(), new User()]);
     });
```

The result is that the table shows all rows but does not render the actual cells until I for example focus the search input in the upper left corner of my reproducer.

If I instead feed the subject like this:

```js
setTimeout(function () {
    mySubject.next([new User(), new User()]);
}, 100);
```
it works just as expected.

Apparently zone.js replaces the setTimeout to detect changes.

**Comment by andrewseguin** [comment]
You are right that the `setTimeout` tells the zone that change detection should occur. You will want to inject `ChangeDetectorRef` and mark for check when your subject fires so that the view knows to update. 

If you have further trouble or need help, feel free to re-open with a stackblitz reproduction and we can diagnose the issue.
