### ISSUE TITLE
Mat-Selection-List SelectionModel not selecting the options

### ISSUE THREAD

**Issue by sivahanuman** [angular/material2#10613]
Hi Mat-Selection-List not selecting the items, i am binding json array to selection and options.

Bug

mat-list-option show as selected

mat-selection-list not selecting the items

[Issue on stackblitz](https://stackblitz.com/edit/angular-material2-issue-plomrp?file=app/app.component.html)

I am using Angular 5, VSCode 1.20.1 and chrome version 65.0.3325.181

**Comment by donroyco** [comment]
Why are you opening a new instance of your previous issue? #10596

**Comment by sivahanuman** [comment]
Sorry I thought that post is closed

**Comment by josephperrott** [comment]
This is working as expected.  You are attempting to assign a different object as selected rather than one of the objects in the list.

You can see [this working version](https://stackblitz.com/edit/angular-material2-issue-wctpet?file=app/app.component.html) forked from your stackblitz you provided.

The relevant code snippet that was changed is below:
```
export class AppComponent {
  ar = [
    {"id": 1,"name": "test1"},
    {"id": 2,"name": "test2"}
  ];
  sar: any[];
  constructor() {
    this.sar = [this.ar[1]];
  }
}
```

**Comment by josephperrott** [comment]
Sorry, if I was unclear I will try to expand a bit.  I closed the issue you because the issue are running into isn't an issue with the `MatSelectionList`, but rather an effect of equality of javascript objects.

For an object to be equal it must be the same object, not just an object containing the same keys and values.

To explain a bit more:
```
let obj1 = {a: 1, b: 'test'};
let obj2 = {a: 1, b: 'test'};
console.log(obj1 == obj2); // This will log false, as obj1 and obj2 are not the same object.
```
However,
```
let obj1 = {a: 1, b: 'test'};
let obj2 = obj1;
console.log(obj1 == obj2); // This will log true, as obj1 and obj2 are the same exact object.
```

For you example, you are trying to set an initial value of the select with a new object that has the same key value pairs.  Instead you will need to set the initial value as references to the actual same object.

**Comment by SalahudinMalik** [comment]
Facing the same problem 
https://github.com/angular/material2/issues/10780

**Comment by simeyla** [comment]
Just put a string representation of the object key into the list. 
Combine two properties if your key is composite.
