### ISSUE TITLE
Checkbox problem in RTL on scrolling page

### ISSUE THREAD

**Issue by mbnsoft** [angular/material2#1062]
RTL direction in css as below:

```
html {
   direction: rtl;
}
```

If vertical scrollbar visible on the page, checkbox border move to left:
![capture](https://cloud.githubusercontent.com/assets/6398149/17737341/f1aefa6c-64a1-11e6-8a6e-ed98b87511c4.JPG)
I have this problem with dir attribute on html tag also, thanks in advance.

**Comment by DevVersion** [comment]
I just took a quick look at that issue. 

At first I came up with a solution like
```scss
/**
 * Temporary mixin to detect whether the current selector is inside of an RTL direction.
 * This can be removed in the future when a service takes control over the RTL detection.
 */
@mixin if-rtl() {
  [style*="direction:rtl"] &, [dir='rtl'] & {
    @content;
  }
}
```

But that approach only works for the inline style of `direction: rtl` - So it's not the solution.

I think now would be a good point to consider creating the RTL service, which detects RTL from the `computed style`.

There must be some discussion about that, since `computed style` can damage the performance significant. 

But the correct approach would be definitely using the `computed style`.

I thought about a directive, which will be applied to the components root element, and then toggles a class for RTL when the upper direction changed.

**Comment by mbnsoft** [comment]
I found a solution, parent scroll container must set force overflow in css:
```
html {
   direction: rtl;
}

#container {
   overflow: auto;
}
```

```
<md-sidenav-layout fullscreen>
   <md-sidenav #sidenav mode="side" align="end" opened="true">
      ...
   </md-sidenav>
   <div id="container">
      ...
   </div>
</md-sidenav-layout>
```

**Comment by eladh** [comment]
Hi  @mbnsoft .
its seems working with the latest release.

see - [https://plnkr.co/edit/oVhHwQIIAgCO7OEFl0c3?p=preview](url)

@EladBezalel 
#goodnessSquad

**Comment by EladBezalel** [comment]
@eladh Thanks !

**Comment by mbnsoft** [comment]
Hi @eladh 
Yes it's works correctly, Thanks!
