### ISSUE TITLE
[Table] Does not trigger `markForCheck` with `trackyBy` and `OnPush`

### ISSUE THREAD

**Issue by keatkeat87** [angular/material2#10755]
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
it should work same as ngFor + trackby + onPush 

#### What is the current behavior?
not trigger markForCheck

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-pbw1ew?file=app%2Fwrap-table%2Fwrap-table.component.html
you can open the ngFor comment link and hide material table to look the different. ngFor will work as expected. 
![image](https://user-images.githubusercontent.com/8691013/38463139-7768e47c-3b26-11e8-9cf6-4b412832b219.png)

#### What is the use-case or motivation for changing an existing behavior?
more easy to use and understand. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
ng 5.2.9, 
material 5.2.4

#### Is there anything else we should know?
i don't know this is a bug or by design and this is my first time to submit issues. 
if anything i m go wrong, please let me know and sorry about that.

**Comment by fr-ench** [comment]
I experience the same issue with CdkTable: when I update data items properties and change data in dataSource, while having trackBy, changes are not reflected on the page. I am not mutating the data, just regenerating new array each time. 
And I can't find a way to run change detection for the table data manually.

**Comment by admosity** [comment]
This is a misunderstanding in the way OnPush works. It literally means that if the inputs of the component has not changed reference wise, it will not get checked/re-rendered. I think it may make sense that cdk calls change detection when it receives a data source change event.

Here's an update to your stackblitz:

https://stackblitz.com/edit/angular-pbw1ew-qjkjae

I made a change to subscribe and mark the component for check when the data source emits new data.

Here's it working below (had to click twice because my recording program lost focus of chrome):

![apr-09-2018 10-42-22](https://user-images.githubusercontent.com/4655972/38504440-b68f02e6-3be2-11e8-8a41-b077f41b2033.gif)
![apr-09-2018 10-43-54](https://user-images.githubusercontent.com/4655972/38504595-137a61e4-3be3-11e8-944b-17d5b0394c23.gif)


Here's some references to angular on this particular issue that I've had myself...

https://github.com/angular/angular/issues/20611
https://github.com/angular/angular/issues/22461

**Comment by admosity** [comment]
An alternative may be to change the trackBy to be more identifying to include the parts of the data that may change:

![apr-09-2018 10-56-46](https://user-images.githubusercontent.com/4655972/38505301-d7fbbee0-3be4-11e8-9bc1-05b281f23ee4.gif)

For your case, you can make it a tuple of the `id` and the `name`.

**Comment by andrewseguin** [comment]
The reason your data is updating when the `ngFor` is present is due to the async pipe which is triggering change detection. Note that without the `ngFor`, nothing on your view is triggering change detection.

**Comment by karthickDhanapal** [comment]
hi @andrewseguin ,

If i change an array object value I need to trigger change detection , Obviously currently not working

**Comment by keatkeat87** [comment]
thank for andrewseguin explain my question. 
karthickDhanapal you have to subscribe your observable and run changedetectorref markforcheck() just like what async pipe done.
