### ISSUE TITLE
Form not showing when inside mat-grid-list / mat-grid-tile

### ISSUE THREAD

**Issue by Buttars** [angular/material2#10849]
#### What is the expected behavior?
Show form split between the grid tile. Username field on top, password below that, all one column.

#### What is the current behavior?
The content inside form does not render.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ncnsqq

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.8
Material: 5.2.4

#### Is there anything else we should know?
If there is any alternative work arounds I can use until this gets fixed, I would love to know.

**Comment by Buttars** [comment]
I only need one column so I opted to use mat-list instead which does not have the same issue. For now, this is a solution for my problem but does not fix the bug.

**Comment by julianobrasil** [comment]
You can switch `mat-grid-list` and `form` tags:
 
```html
<form [formGroup]="loginForm" novalidate>
  <mat-grid-list cols="1">
    <mat-grid-tile>
      <mat-form-field>
        <input matInput placeholder="Test">
       </mat-form-field>
    </mat-grid-tile>
	
    <mat-grid-tile>
      <mat-form-field>
        <input matInput formControlName="password">
      </mat-form-field>
    </mat-grid-tile>
  </mat-grid-list>
</form>
```

**Comment by michaeltarleton** [comment]
Will there be support for this in the future?

**Comment by vjamwec13579** [comment]
Why isn't this supported?  What's the point of creating Material IO directives if Angular's component's  selectors aren't supported?  I thought this was supposed to make layout's more in line with Material IO.  It seems that mat-grid-list only supports the most basic functionality.  One might as well ditch the Angular Material IO and use material IO directly.  In order to solve this problem, one needs to write a component and directive to support what would be part of Angular Material IO.

**Comment by lebyanelm** [comment]
@Buttars had the same issue, my form was not showing inside the `mat-grid-list`, realised the problem was that I had set `rowHeight` to 100% which made it to disappear since there was another element(sibling to `mat-grid-list`) using the space
