### ISSUE TITLE
form-field: outline appearance, input value doesn't align with non-focused label

### ISSUE THREAD

**Issue by fxck** [angular/material2#10926]
![image](https://user-images.githubusercontent.com/1303561/39034421-a3920412-4476-11e8-9c5f-801e37a821c0.png)

cc @mmalerba

**Comment by mmalerba** [comment]
From what I can tell, this is actually an intentional part of the spec. The label is centered and the input text is a little lower. I agree that it seems a little strange... I think it may have been done for better alignment with the filled text fields. I'll keep an eye on the spec and update it if anything changhes
