### ISSUE TITLE
Datepicker: updating ngModel binding clears input

### ISSUE THREAD

**Issue by mark-langer** [angular/material2#10963]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The user enters a value, the code reads the input value and writes the perfectly formatted date into the model. Angular then writes the value into the input field.

#### What is the current behavior?
The user enters a value, the code reads the input value, updates the model and... the input field is cleared with a red error border.

#### What are the steps to reproduce?
Just throw an `[(ngModel)]` onto the datepicker input and transform the input value on a change event. As soon as the model gets updated, Angular clears the input completely.
https://stackblitz.com/edit/angular-rsduqa?file=app/datepicker-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?
We're parsing shortcuts for "yesterday" (y) and "the day before yesterday" (b) from the user input and replace the letter with a date. The Angular datepicker currently breaks that behavior. I have not been able to find a workaround.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with Angular 5.2.10

#### Is there anything else we should know?
The other features of the Datepicker and its looks are awesome!

**Comment by mmalerba** [comment]
The recommended way to do this is to create a custom `DateAdapter` by extending the `NativeDateAdapter` and overriding the parse behavior. Implementation here: https://github.com/angular/material2/blob/2fad732b090335054dbfca539ce76f17f55b8590/src/lib/core/datetime/native-date-adapter.ts#L176

Your adapter would basically be:

```ts
class MyNativeDateAdapter extends NativeDateAdapter {
  parse(value: any): Date | null {
    if (value === 'today' || ...) {
      // custom parse logic
    } else {
      return super.parse(value);
    }
  }
}
```

The docs discuss how to provide your custom DateAdapter so that the Datepicker will use it: https://material.angular.io/components/datepicker/overview
