### ISSUE TITLE
Required input in mat-form chip-list does not show required * mark in label

### ISSUE THREAD

**Issue by Antoniossss** [angular/material2#10992]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
When I use Input for adding new chips, marking input as [required]='true' in mat-form-field should render 

#### What is the current behavior?
No asterisk is not shown if input is not first element in `mat-form-field`

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-bfqypg

#### What is the use-case or motivation for changing an existing behavior?
Consistent behavior of inputs

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/cdk": "^5.2.4",
    "@angular/material": "^5.2.4",

**Comment by tinayuangao** [comment]
@Antoniossss The `required` can only be added to chip list, instead of the chip input. There shouldn't be asterisk if you put `required` on `input`, regardless the input is the first element in `mat-form-field` or not.

Do you have a use case that makes `input` required but doesn't make `chip-list` required?

**Comment by Antoniossss** [comment]
@tinayuangao ok, styling is applied, but input is still clickable. If disabled not applied to input as well, then it is possible to edit disabled type into input.

**Comment by Antoniossss** [comment]
Wrong usage. Closing.
