### ISSUE TITLE
MatMenu overlay position issue

### ISSUE THREAD

**Issue by isametal88** [angular/material2#11220]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
MatMenu should use xPosition and yPosition, and overlap the trigger by default

#### What is the current behavior?
xPosition and yPosition are ignored, the overlay position is incorrect

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ofiauh

#### What is the use-case or motivation for changing an existing behavior?
-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 6.0.0.

#### Is there anything else we should know?
My issue is in a more complex environment, but the example I provided above is the simplest possible.

**Comment by crisbeto** [comment]
@isametal88 your example doesn't work, because you haven't included Material's structural styles which are required for the menu positioning. There's also a warning being logged from Material that these styles are missing. [Here's a working fork of your example](https://stackblitz.com/edit/angular-msyxsb?file=src%2Fstyles.css). The only change is adding the following to the `style.css`:

```css
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
```

**Comment by isametal88** [comment]
Thank you so much for your quick response.
Yes, I was missing that part, my bad. Everything works properly now.
Thank you again.
