### ISSUE TITLE
How I make a mat-table printable (output to a printer)

### ISSUE THREAD

**Issue by IngoManthey** [angular/material2#11227]
Hi,
I test:
<mat-table [dataSource]="dataSource" matSort matSortActive="fullName" matSortDirection="asc" id="print-section">

print(): void {
    let printContents, popupWin;
    printContents = document.getElementById('print-section').innerHTML;
    popupWin = window.open('', '_blank', 'top=0,left=0,height=100%,width=auto');
    popupWin.document.open();
    popupWin.document.write(`
      <html>
        <head>
          <title>Print tab</title>
          <style>
          //........Customized style.......
          </style>
        </head>
    <body onload="window.print();window.close()">${printContents}</body>
      </html>`
    );
    popupWin.document.close();
}

But it do not work.

Regards Ingo

**Comment by ewaschen** [comment]
I don't know if you can use the `mat-table` since it requires angular material js, you would have to pass the script files to the print window along with the css.

What I currently do is I have a hidden component where I pass the data from my `mat-table`.  The component's html is just a simple `table` styled with bootstrap.  I then print that table and make sure to pass bootstrap css to the print window.

If you want something with the material style, you can download the css and js for [Material Lite](https://getmdl.io/components/index.html#tables-section).  Style the printing table according to the guidelines and pass the css and js files to the print window and it should print the mat lite table, which is very similar to angular material.

Also, make a [Stackblitz](https://stackblitz.com/fork/angular) since it is easier for people to help you

**Comment by jelbourn** [comment]
Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are stack overflow, gitter, mailing list, etc.

(this is a canned response)
