### ISSUE TITLE
(bug) slider with `dir=rtl` does not work as expected

### ISSUE THREAD

**Issue by klaascuvelier** [angular/material2#11276]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When adding the RTL direction on the slider's parent, the slider's knob should start at the right side and be moved to the left side to change it's value, as well as the slider's value indicator (the colored bar). 

#### What is the current behavior?
When adding the RTL direction on the slider's parent, the knob is still left-to-right (but the value indicator is correct)

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://angular-y6pkcn.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
*n.a*

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.2.10
Material: 5.2.4

Bug reproducible in Safari, Chrome, Firefox on OSX

#### Is there anything else we should know?
*n.a*

**Comment by klaascuvelier** [comment]
Hmm, it seems I can only reproduce this bug on Stackblitz, and not locally; I tried locally with `@angular/material` at `5.2.4` and `6.0.0`.

In both cases my minimal setup seems to work.
Upon debugging the Stackblitz link, it seems the `_thumbContainerStyles` method thinks it's in `ltr` mode

**Comment by crisbeto** [comment]
That's because you're setting the `dir` attribute on an element that is outside your Angular app, which means that Material can't pick it up. The only elements, outside of the Angular app, that Material looks at are the `html` and `body` tags. You can fix it by moving the `dir` to a root element inside the app. [Here's a working fork of your Stackblitz](https://stackblitz.com/edit/angular-y6pkcn-1xuw3j?file=app/slider-overview-example.html).

**Comment by klaascuvelier** [comment]
Eric from stackblitz pushed a fix for this bug a couple of hours after I've filed this bug and then found out it was not Material related (see thread https://twitter.com/elad_bezalel/status/994818732898881536)
