### ISSUE TITLE
Placeholder text not displaying for matInput

### ISSUE THREAD

**Issue by AryanJ-NYC** [angular/material2#11355]
#### Bug, feature request, or proposal:
I followed the `matInput` [documentation](https://material.angular.io/components/input/overview) and my placeholder disappears.

#### What is the expected behavior?
The placeholder should appear in the input and above the input when a value is inside the input.
![screen shot 2018-05-15 at 9 04 25 pm](https://user-images.githubusercontent.com/8263430/40091057-95b8fdac-5883-11e8-9bab-2f6fdc9c3c30.png)

#### What is the current behavior?
The placeholder is blank and only displays when animating or input is focused:

![screen shot 2018-05-15 at 9 05 10 pm](https://user-images.githubusercontent.com/8263430/40091085-b67db05a-5883-11e8-8fed-6f306e81838c.png)

AND

![screen shot 2018-05-15 at 9 05 17 pm](https://user-images.githubusercontent.com/8263430/40091086-b68d8534-5883-11e8-871f-07e725dad108.png)

Please note that the gap to the left of the password `input` _should_ be the username `input`.

#### What are the steps to reproduce?
[StackBlitz](https://stackblitz.com/edit/angular-material2-issue-l5taiw)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
@angular: 6.02
@angular/material: 6.0.2
typescript: 2.7.2
```
Mac OS 10.13.4

**Comment by okeefem2** [comment]
It looks like you are using the purple-green prebuilt them, since this (and the pink-bluegrey) are 'dark themes' if you change your background color to a darker color you should be able to see your inputs. I have attached an image from your Stackblitz link as illustration.
<img width="1074" alt="screen shot 2018-05-26 at 11 40 46 am" src="https://user-images.githubusercontent.com/9085397/40577885-ce9ad74a-60d9-11e8-8455-72dea01b032b.png">

**Comment by josephperrott** [comment]
Closing as this is working as expected.  In your stackblitz you provided you can see that the placeholders are there, however they are not visible since they are white text with the white page background.
