### ISSUE TITLE
[Tooltip] displaying issue

### ISSUE THREAD

**Issue by levgaas** [angular/material2#11361]
#### Bug, feature request, or proposal:
Sorry for inconvenience, but I'm not able to reproduce it on a StackBlitz.
It happens on a large project and tooltips are completely broken after some period of time.
![screen shot 2018-05-16 at 3 03 20 pm](https://user-images.githubusercontent.com/10091564/40116137-63aa76a4-591b-11e8-860c-9bb484f8ac01.png)

Usage:
```
<button mat-icon-button
        color="primary"
        matTooltip="Search"
        [matTooltipShowDelay]="tooltipShowDelay">
  <mat-icon [svgIcon]="SvgIcon.Search"></mat-icon>
</button>
```
While inspecting it transforms to 
![screen shot 2018-05-16 at 3 18 10 pm](https://user-images.githubusercontent.com/10091564/40116475-6fb45e64-591c-11e8-9eba-7cd809e9b9ae.png)

There are cases when it's displayed somewhere on the screen. Mostly top-left corner

From my perspective something happened to cdk-overlay. Since menus in that case won't close until I click some button (i.e. re-render)

Frequency increased after switching to v6 from v5.

#### What is the expected behavior?
Tooltips are displayed correctly

#### What is the current behavior?
Tooltips are broken

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.1
Material 6.0.1
TS 2.7.2
RxJS 6.1.0 + rxjs-compat
Flexbox-layout 6.0.0-beta.15. Btw with Angular v5 I used 2.0.0-beta.12
Browser: Chrome 66.0.3359.170
MacOS

**Comment by crisbeto** [comment]
It's going to be difficult to debug this without some more info @levgaas. Off the top of my head, the only thing that could cause something similar is if you tried to open an overlay outside of the `NgZone`.

**Comment by levgaas** [comment]
@crisbeto , thanks for your response. I have been succeed in finding the issue.
It's not related to material tooltip by any reasons. 
I'm still not sure why exactly it happens but angular is broken after 5-6 app ticks when I do auth / redirection / routing / lazy load children / activateChild guard... stuff

**Comment by sanojantonyfico** [comment]
I see this with material 6.3.0 but only when it is deployed as an Angular Element. Regular ng serve works fine. Setting show and close delays to 0 not working.

**Comment by turbolego** [comment]
I have the same issue.
Angular 7, deployed as Angular Element.
Every time i hover on the button, a small grey "blob" is added to a "row" under the address-field in my browser.

<img width="411" alt="Screenshot_188" src="https://user-images.githubusercontent.com/2650749/55893283-3f8fa780-5bb8-11e9-9b26-e21f4d47e6ca.png">

When i click the button, a "tick()" is triggered (because angular elements needs that without ngZone) and the row of grey blobs is replaced with the tooltip. It's in the wrong spot, but it's there. I suspect this has something to do with how "Angular Elements" work? Since the grey blobs were only "converted" to the tooltip after a "tick()"?

<img width="336" alt="Screenshot_189" src="https://user-images.githubusercontent.com/2650749/55893443-87aeca00-5bb8-11e9-858b-af4d8b5b2589.png">

My code:

_app.module.ts_
`import { MatTooltipModule } from '@angular/material/tooltip';`

_somecomponent.component.ts_
`<button mat-button class="button" (click)="openDialog()" matTooltip="Åpne" aria-label="Åpne">
ÅPNE</button>`

Thanks for reading! 😄
