### ISSUE TITLE
Need to visually disable Material form controls without affecting the state

### ISSUE THREAD

**Issue by dobrevad** [angular/material2#11519]
#### Bug, feature request, or proposal:
I am trying to disable form controls on submit while async validation is running.
Doing so affects the form control state and forces validation to run twice.

#### What is the expected behavior?
To be able to only visually disable form controls.

#### What is the current behavior?
Calling formControl.disable() affects the state of the control. Once the validation has finished and the control is enabled and runs the validation for a second time.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-5njmxc-fevtfu

1. Write anything except 'dog' in the input
2. Click Submit

[Expected]: The validation finishes, the input is enabled and it shows the error
[Actual] The validation finishes, the input is enabled and it runs the async validation again

#### What is the use-case or motivation for changing an existing behavior?
Need to only visually disable Material form controls during async validation on submit.

**Comment by pfeigl** [comment]
There is https://angular.io/api/forms/AbstractControl#updateOn which can be set to `submit`. Also this is very much a question for other channels (i.e. gitter, SO) and not a bug or feature request.

**Comment by dobrevad** [comment]
Thanks for the input but this is not what I am looking for. I am trying to visually disable Material form controls without affecting their internal state.
UpdateOn is just postponing the validation but it doesn't have anything to do with disabling the controls.

I posted it here since I think this should be supported and I believe it's not.

**Comment by pfeigl** [comment]
The `updateOn` option was thought to help you out with duplicated validation rounds.

Anyways, I think this is nothing what `@angular/material` should do. In the end, it only provides input elements, not complete form support. Also there is no definition of what you are asking for in standard forms.

I would just go with a solution where you put a overlay over your whole form with a defined opacity. And you might optionally check the `isvalid` flag of the form.

Anyways, this is why I recommended to ask in other channels, because it is not specific to `@angular/material` but more a general problem you try to solve here.

**Comment by dobrevad** [comment]
That makes sense. Thanks
