### ISSUE TITLE
select value not updating with formControl value in the view

### ISSUE THREAD

**Issue by casizzi** [angular/material2#11536]
#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-9lmupb?file=app%2Fapp.component.ts

**Comment by pmnevill** [comment]
@casizzi you need a [compareWith](https://angular.io/api/forms/SelectControlValueAccessor#caveat-option-selection) function to specify how you want the option values compared

**Comment by crisbeto** [comment]
Closing since this works as expected. `mat-select` compares the values by reference, which means that you're initializing the model with a completely new, but identical, object. If you switch to initializing it by referencing an item in the array, [it'll work as expected](https://stackblitz.com/edit/angular-material2-issue-3eafh1?file=app/app.component.ts).
