### ISSUE TITLE
[datepicker] time is reset to midnight when field is blurred

### ISSUE THREAD

**Issue by tchandelle** [angular/material2#11545]
#### Bug
Create a `mat-datepicker`, with `MatMomentDateModule` adapter and with this provider
```ts
  providers: [{
    provide: MAT_DATE_FORMATS,
    useValue: {
      parse: {
        dateInput: 'L LTS',
      },
      display: {
        dateInput: 'L LTS',
        monthYearLabel: 'MMM YYYY',
        dateA11yLabel: 'L LTS',
        monthYearA11yLabel: 'MMMM YYYY',
      },
    }
  }]
``` 

Select a date

The input display **05/28/2018 12:00:00 AM**

Edit the time

#### What is the expected behavior?
The date should change the time

#### What is the current behavior?
The time is reset to 12:00:00 AM when user blur the field

#### What are the steps to reproduce?
**StackBlitz doesn't work with moment**, this is another issue (#9780). But for reference : https://stackblitz.com/edit/angular-material2-issue-25p4rg

#### What is the use-case or motivation for changing an existing behavior?
It use to work before a62cdb6

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Chrome Version 66.0.3359.181 
moment 2.22.1

```
Angular CLI: 6.0.5
Node: 8.11.1
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0
@angular-devkit/build-angular      0.6.0
@angular-devkit/build-optimizer    0.6.0
@angular-devkit/core               0.6.0
@angular-devkit/schematics         0.6.5
@angular/cdk                       6.1.0
@angular/cli                       6.0.5
@angular/material                  6.1.0
@angular/material-moment-adapter   6.1.0
@ngtools/webpack                   6.0.0
@schematics/angular                0.6.5
@schematics/update                 0.6.5
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.6.0
```

**Comment by mmalerba** [comment]
This is probably because the `DateAdapter` doesn't officially support dealing with the time component of the date yet. My guess is that creating a custom `DateAdapter` that extends the adapter you're currently using and overrides the `compareDate` method to consider time would fix it: https://github.com/angular/material2/blob/master/src/lib/core/datetime/date-adapter.ts#L241

In case you're not familiar with the `DateAdapter`, I wrote a blog post about it a while back: https://medium.com/@esanjiv/working-with-custom-dateadapter-for-angular-material-2-datepicker-76d4446277dc

I think your custom one would look like this:

```ts
class MyNativeDateAdapter extends NativeDateAdapter {
  compareDate(first: Date, second: Date): number {
    return first.getTime() - second.getTime();
  }
}
```

Eventually the datepicker will officially support time and we'll probably add a separate method `compareDatetime`.

**Comment by tchandelle** [comment]
Thanks. I confirm that extending `MomentDateAdapter` with the method below solve the issue

 ```ts
 compareDate(first: Moment, second: Moment): number {
    return first.valueOf() - second.valueOf();
  }
```

**Comment by PunkHaz4rd** [comment]
It doesn't anymore
