### ISSUE TITLE
md-toolbar width doesn't respect the margin.

### ISSUE THREAD

**Issue by colinfang** [angular/material2#1155]
When we set `margin: 100px`, the toolbar simply moves to the right.

http://plnkr.co/edit/D8731pOYJm7LOFCCjcMy?p=preview

Chome

**Comment by fxck** [comment]
That's because it's `width: 100%`, but I'm pretty sure that the material design spec doesn't allow toolbar to be anything but full screen width so I don't really think it's something that should be fixed. 

You can do either this http://plnkr.co/edit/f7TCUu3FLzlrCJvFHG5d?p=preview or this http://plnkr.co/edit/N0dnVSQ9rbJXOZVVBPpV?p=preview

**Comment by DevVersion** [comment]
@fxck I can agree with that.
>  Theoretically we could use flexbox to fill the remaining space, but I do not like the fact that the toolbar considers other elements in the current flexbox layout (if present)

**Comment by colinfang** [comment]
@fxck Thx. Good to know.
