### ISSUE TITLE
mat-select disabled status doesn't refresh correctly

### ISSUE THREAD

**Issue by CedBadarou** [angular/material2#11601]
Bug
I'm creating a form in Angular with a mat-select input, bound to a FormControl, which should be disabled or not, according to a boolean, when the form is created.

What is the expected behavior?
The mat-select should be disabled/enabled according to the FormGroup disabled/enabled status.

What is the current behavior?
The mat-select stays enabled/disabled even when the FormGroup disabled/enabled status change.

What are the steps to reproduce?
step 1: The form is created and the FormGroup is disabled in the initForm method, according to the if condition. The mat-select is correctly disabled.

step 2: Click on the "Toggle" button change the boolean to false and calls the initForm method, so this time the FormGroup is not disabled ==> the mat-select button is still disabled.

https://stackblitz.com/edit/angular-qy1hqc?file=src%2Fapp%2Fapp.component.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.9, Material 5.2.4

**Comment by josephperrott** [comment]
Closing as this is working as expected.  The form element is not changing its disabled state visually because rather than toggling the disabled state of the form control, you are creating an entirely new form group.  This form element is not a member of the new form group you are creating.  You can see a working fork of your stackblitz [here](https://stackblitz.com/edit/angular-fckbcp?file=src/app/app.component.ts) .
