### ISSUE TITLE
Ability to filter or disable Keyboard Input for Mat-Select

### ISSUE THREAD

**Issue by JKing-B16** [angular/material2#11654]
#### Bug, feature request, or proposal:

I have a project that uses a unique keyboard remote control for navigation. To move between fields, I'm pretty much restricted to arrows. It would be very helpful if I could disable the mat-select's default behavior for right and left arrow keys.

#### What is the expected behavior?

Ability to disable left and right arrow keys for mat-select interaction

#### What is the current behavior?

No documented way to disable keyboard or filter keyboard input.

#### What is the use-case or motivation for changing an existing behavior?

An GUI that is controlled via a Remote control attached as USB Keyboard, but limited to only 13 keys.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6

**Comment by crisbeto** [comment]
Closing the issue, because in general we avoid adding APIs that would inhibit accessibility. You can work around it in your API by binding a custom `keydown` event and stopping it before it has reached the select. [Here's a quick example](https://stackblitz.com/edit/angular-nftpdq?file=app/select-overview-example.ts).
