### ISSUE TITLE
WARNING in ./node_modules/@angular/material/esm5/material.es5.js 41:0-371 "export 'ɵh21' was not found in '@angular/material/tabs'

### ISSUE THREAD

**Issue by PsychicCat** [angular/material2#11664]
This is happening in 6.2.1 again...

**Comment by pfeigl** [comment]
I had the same problem here, but found out that after upgrading a project from 6.0.2 to 6.2.1 I actually suddenly had a 6.0.0 version installed in node_modules.

Somehow (either through caching or whatever) yarn didn't install the correct package, even while yarn.lock file had all the correct version information.

After deleting node_modules and doing a fresh install, I had the correct 6.2.1 package installed locally and everything was working fine.

**Comment by pfeigl** [comment]
Could reproduce the it in another project while upgrading from 6.2.0 to 6.2.1. While yarn.lock shows the following: 

```
"@angular/material@^6.2.1":
  version "6.2.1"
  resolved "https://registry.yarnpkg.com/@angular/material/-/material-6.2.1.tgz#aec3387db755145b80d66d8497d4a834f88b61be"
  dependencies:
    tslib "^1.7.1"
```

node_modules still kept a version of 6.2.0 in the background - or possibly parts of it. Maybe some files were locked by i.e. VSCode and haven't been removed / replaced correctly. 
Also I'm behind a corporate proxy, but I doubt caching problems there, because the whole download-url changes between versions.
