### ISSUE TITLE
Material providers

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#1170]
All material modules are loaded using forRoot. That means modules are loaded with their providers.
Overlay_Provider is exported by both menu and dialog. Since providers are singleton, I wonder if this will produce an issue.

**Comment by RoxKilly** [comment]
The regular modules no longer export their providers by default. The only way to get providers is to import `ModuleName.forRoot()`

This means that if for instance  several of your modules import `MdDialogModule`, they will not get the provider. Only the bootstrapped `AppModule` should get it because it imports `MdDialogModule.forRoot()`. As a result, there is only one instance of the provider app-wide

Suppose the root `AppComponent` sees the same provider listed twice. This is not a problem because the same component will not re-import what it already has.
