### ISSUE TITLE
mat-filtering not show correct data when use ngif in mat-table parent

### ISSUE THREAD

**Issue by avechuche** [angular/material2#11716]
#### Bug, feature request, or proposal:
Bug

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-wqkekh?file=app/table-pagination-example.html

Note that paging does not show the number of elements it is showing, but if you delete the line in the html file * ngIf = "dataSource? .filteredData.length> 0" the error is fixed

**EDIT:** Also, changing the number of items per page does not work
**EDIT 2:** Also, mat sorter does not work

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.4
Material 6.2.1

**Comment by andrewseguin** [comment]
ViewChild will not work to grab items nested in an ngIf. The view has not yet evaluated the statement by the time the ViewChild tries to grab the element.

To trivially resolve your case, change `ngOnInit` to `ngAfterViewInit` so that the ngIf has a chance to evaluate the view first

https://stackblitz.com/edit/angular-wqkekh-cwczhb?file=app/table-pagination-example.ts

**Comment by avechuche** [comment]
@andrewseguin First of all thank you for the response, I modified the example so that it is more similar to my reality. Can you check it? It is the same problem that I mentioned in the original thread. https://stackblitz.com/edit/angular-wqkekh-sam3r9?file=app%2Ftable-pagination-example.ts. Thx!

**Comment by andrewseguin** [comment]
In this case, you are telling the paginator and sort to enter the view until the datasource has data. The problem here is that before this you a trying to grab the paginator and sort and set them to the data source.

To make sure that the paginator/sort are set when they appear in the view, you can use a setter that will make sure it is given to the data source once it is set.

https://stackblitz.com/edit/angular-wqkekh-a5an3y?file=app/table-pagination-example.ts

**Comment by avechuche** [comment]
@andrewseguin Very good answer. It works perfect. Thank you very much!
