### ISSUE TITLE
Dialog so complicated 

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#1180]
First of all, chapeau bas @jelbourn for writing down this amazing dialog code.
But I don't understand why it's so complicated adding components dynamically with ng2
I think a piece of api like hereafter is missing:
let factory = getFactory(myCmp);
let cmp = factory.createInstance();
this.renderer.addChildComponent(this.htmlElement);

**Comment by fxck** [comment]
I personally like this API the best https://github.com/ng-bootstrap/ng-bootstrap/issues/3#issuecomment-241984406 (and following discussion)

and it shouldn't even be that hard to make, since I've finally figured out how to use that portal / overlay combo https://github.com/angular/material2/issues/998#issuecomment-244156632

**Comment by jelbourn** [comment]
We feel that a declarative API really doesn't make sense for components like dialog, snackbar, etc.

@zigzag95 Saying the implementation is "too complicated" is not a bug, feature request, or proposal for Material. It's as complicated as it has to be to support AoT compilation.

**Comment by fxck** [comment]
@jelbourn I'd argue that for modal particularly it does 

a) it's how the native `dialog` element will work https://developer.mozilla.org/en/docs/Web/HTML/Element/dialog
b) allows you to utilize state managment libs like @ngrx/store better, as it can practically be stateless
