### ISSUE TITLE
Sidenav / drawer closes when it should be pinned

### ISSUE THREAD

**Issue by mfilar** [angular/material2#11840]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
There should be a way to disable toggling sidenav when mode pinned selected

#### What is the current behavior?
When you set mode pinned and opened to true sidenav still can be closed with ESC key

#### What are the steps to reproduce?
Demo from angular material sidenav page:
https://stackblitz.com/angular/lvexjmxjgey?file=app%2Fsidenav-drawer-overview-example.html
1. Left-click on sidenav (sidenav is in focused state)
2. Hit ESC on keyboard - sidenav closes
Issue also exists in material navigation schematics, when a user closes sidenav like this there is no way to open it (no toggle button in desktop view)

#### What is the use-case or motivation for changing an existing behavior?
User should be able to navigate on a page

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all

#### Is there anything else we should know?
--

**Comment by crisbeto** [comment]
This works as expected, it just looks weird in the docs, because there's no button for toggling the sidenav. If you don't want users to be able to close it by pressing escape, [you can set the `disableClose` attribute](https://stackblitz.com/edit/angular-kdzhv4?file=app/sidenav-drawer-overview-example.html).
