### ISSUE TITLE
CDK LiveAnnouncer region not hidden from screen reader

### ISSUE THREAD

**Issue by diminutivesloop** [angular/material2#11991]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The message text announced via the CDK `LiveAnnouncer` service should not be accessible to screen reader users except when it is being announced.

#### What is the current behavior?
Once a message has been announced the aria-live element is visible to a screen reader user during normal page element navigation.

#### What are the steps to reproduce?
1. With a screen reader enabled click the "Announce" button.
2. After the message "Hello world!" has been announced navigate through the other page elements by pressing the down arrow key.
=> After pressing the arrow key several times the element containing the message text "Hello world!" is read by the screen reader.

#### What is the use-case or motivation for changing an existing behavior?
Hearing the message from a previous aria-live announcement while navigating page elements is confusing for users.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.6
Material 6.3.0

#### Is there anything else we should know?
I was able to reproduce this issue with both NVDA and JAWS.

**Comment by satheeshd** [comment]
This needs to be fixed. 
Once any component uses `LiveAnnouncer`, it never removes the previously announced message from the dom, leaving trail in the DOM, ever after the user have navigated to different route.

Perhaps an auto 'removal' of message string after a 'Configurable' timeout would help.
The announcer method could be enhanced with this 'timeout' time, because sometimes the message might be pretty long and a pre-defined timer would not allow the screen readers to finish reading it.
