### ISSUE TITLE
ngFor of buttons cause ripple to malfunction 

### ISSUE THREAD

**Issue by tmburnell** [angular/material2#12132]
#### Bug, feature request, or proposal:
Bug where multiple mini fabs (probably other buttons too) if placed in an *ngFor ...
the ripple or boxshadow is miss fired. 

#### What is the expected behavior?
The should only fire on the clicked button (and works correctly if not nested in a ngFor).

#### What is the current behavior?
The ripple simi randomly fires on other buttons.  It does seem to have impact if you have touched other buttons prior too. 

#### What are the steps to reproduce?
https://stackblitz.com/edit/stepper-buttons?file=app%2Fstepper-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The stackblitz is in 5, I have not fully tested 6.

**Comment by DevVersion** [comment]
I think there is nothing we could do about that issue. Since you basically modify the array that is being rendered using `*ngFor` with buttons, there will be a different button instance with a new ripple directive.

Meaning that the old button instance will be destroyed, and the ripples will hide immediately. Consider having an object inside of the array that guarantees object equality.

e.g. https://stackblitz.com/edit/stepper-buttons-7mfguy?file=app%2Fstepper-overview-example.ts
