### ISSUE TITLE
MdCard incompatible with MdTab

### ISSUE THREAD

**Issue by Cayan** [angular/material2#1220]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

MdTab should work with other components properly.
#### What is the current behavior?

MdTab's body wrapper has CSS overflow defined as hidden, if have a card inside a tab's content it won't display properly.
#### What are the steps to reproduce?

http://plnkr.co/edit/W7B8TFNpGzXr022kHD2z?p=preview

Since MdTab is not working properly #1219, I manually fixed it and the following screenshots show how it is and how it should be:
- http://prntscr.com/cga6ve
- http://prntscr.com/cga6xs
#### What is the use-case or motivation for changing an existing behavior?

Faulty one
#### Which versions of Angular, Material, OS, browsers are affected?

Angular2 RC 6
Material 2.0.0-alpha.8-1
OS Linux Mint 18 64x
Browser Chrome 52.0.2743.116
#### Is there anything else we should know?

Guess not

**Comment by caseyhoward** [comment]
It appears to have nothing to do with md-card. The example from the docs doesn't even work: http://plnkr.co/edit/gLEzn5dw3xxpYtOZTCBH?p=preview

**Comment by Cayan** [comment]
@caseyhoward there is a problem with this plunker, once this error gets fixed you can notice how those two components are not working properly together

**Comment by andrewseguin** [comment]
@Cayan md-card displays its border effect by using shadows that beyond extend itself. Are your expectations that the card should display those shadows beyond the frame of the tab? 

Your expected behavior says that MdTab should work well with other components, but this does seem to be the actual behavior. MdCard needs some breathing room to show its box shadow.

Here is a working example of the issue you are highlighting as well as a fix using margins around the card. http://plnkr.co/edit/dfP7PiRTWzLMCutZwh0T?p=preview

**Comment by Cayan** [comment]
This makes sense.

I think the main question for this issue would be what is the expected behavior?

**Comment by andrewseguin** [comment]
I believe it is exercising the expected behavior since in your example there is no margin surrounding the card. Any component whose box shadow exceeds the bounds of the tab will have the same issue and it is expected that a margin should be placed.

In general, components are not prescribed a certain margin so that it is left to the developer to add for their design. This seems funny with md-card because they practically require a margin, but they are following the right guideline as they are right now. 

You can especially see the issue if you line up several md cards in a row without setting a margin:
http://plnkr.co/edit/9Rhdq0pnCMW2R7mwQCDr?p=preview

If there is a problem here it is likely to be with the cards not giving themselves that appropriate breathing room. I don't think the tabs should accommodate for it.
