### ISSUE TITLE
fix(mat-datepicker): icon size

### ISSUE THREAD

**Issue by levgaas** [angular/material2#12226]
#### Bug:
I'd expect date icon to consistent with other icons using in form fields. Plus to match the specs.

#### What is the expected behavior?
![image](https://user-images.githubusercontent.com/10091564/42750988-f6df2388-88f1-11e8-826b-1e9ddb22c8d6.png)

#### What is the current behavior?
![image](https://user-images.githubusercontent.com/10091564/42750926-b5227422-88f1-11e8-8f0b-9c3c558faae2.png)

#### Place to look into
![image](https://user-images.githubusercontent.com/10091564/42751156-7e94bf7c-88f2-11e8-8a66-a4d5987fb99d.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material: **v.6.3.3**
Browser: **Chrome**

**Comment by mmalerba** [comment]
Your example is using the "legacy" variant of the form-field, which maintains styles that appeared in an older version of the spec in order to avoid automatically causing significant visual changes in people's existing apps. If you use the "standard" variant instead, you'll see that the icon size is correct: https://stackblitz.com/edit/angular-pbspjf?file=app%2Fdatepicker-overview-example.html

**Comment by levgaas** [comment]
@mmalerba makes sense.
I just grabbed an example from 
https://material.angular.io/components/datepicker/examples

Is it something we should reflect there as well?

**Comment by mmalerba** [comment]
Ah, yeah if you want to send a PR to change the examples to standard style, I'll approve it
