### ISSUE TITLE
Spaces cannot be input on Expansion Tile Titles

### ISSUE THREAD

**Issue by the-amber-joy** [angular/material2#12391]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Editing an expansion tile title should allow all alphanumeric values, including spaces between words.

#### What is the current behavior?
Letters, numbers, and special characters are allowed, but SPACES are not.

#### What are the steps to reproduce?
1) Add (click) event to change title text of an expansion panel into an input.
2) Attempt to change title text to multiple words.
3) Spaces are not allowed but all other characters are.
Example:
https://stackblitz.com/edit/angular-material2-issue-yql7df

#### What is the use-case or motivation for changing an existing behavior?
I need to be able to edit the expansion tile title text with spaces between words.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular, Material, TS, Windows, MacOS - most recent 
Chrome, IE, Edge, Safari - most recent
Chrome on Android 7.0 (I have not tested other versions of Android).
I have not tested on iOS.

#### Is there anything else we should know?
Nope

**Comment by crisbeto** [comment]
THat's because space is the key for toggling the expansion panel and the header isn't meant to have input elements. You can workaround it by adding `(keydown)="$event.stopPropagation()"` to the `input` which will prevent the event from reaching it while you're typing. Closing the issue since it works as expected.
