### ISSUE TITLE
The MatSelectionList should support ControlValueAccessor

### ISSUE THREAD

**Issue by germanamz** [angular/material2#12447]
#### Bug, feature request, or proposal:
The [MatSelectionList](https://material.angular.io/components/list/api#MatSelectionList) should support [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor) to be used inside any [FormGroup](https://angular.io/api/forms/FormGroup).

#### What is the expected behavior?
The [MatSelectionList](https://material.angular.io/components/list/api#MatSelectionList) should support [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor)

#### What is the current behavior?
The [MatSelectionList](https://material.angular.io/components/list/api#MatSelectionList) doenst support [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor)

#### What are the steps to reproduce?
N/A

#### What is the use-case or motivation for changing an existing behavior?
To use the [MatSelectionList](https://material.angular.io/components/list/api#MatSelectionList) inside a [MatStepper](https://material.angular.io/components/stepper/overview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
N/A

#### Is there anything else we should know?
<3

**Comment by DevVersion** [comment]
The `MatSelectionList` actually acts as a `ControlValueAccessor` and we run various tests that ensure that `NgModel` or a `FormControl` works properly with the selection list.

I'm closing this issue because everything works as expected. Please reply if you want me to reopen this issue.

https://stackblitz.com/edit/selection-list-model?file=app/list-selection-example.html
