### ISSUE TITLE
Missing style when rendering a angular material control

### ISSUE THREAD

**Issue by atmike** [angular/material2#12453]
#### What is the expected behavior?     #### What is the current behavior?
I’m using the angular rendering engine to render material components. But when I render the controls (in my case Cards => mat-card) they do not have any style. So everything that comes with the prebuilt-themes(node_modules\@angular\material\prebuilt-themes ).

![tbvn1](https://user-images.githubusercontent.com/22487185/43447739-6b7bb56a-94ac-11e8-895b-437c104234be.png)

When I add a card by hand =>

`<mat-card> test</mat-card>`
And set the class Attribute at the rendering process it works =>

`renderer.setAttribute(matCard , "class", "mat-card");`

![t1jgr](https://user-images.githubusercontent.com/22487185/43447794-90b0157e-94ac-11e8-8994-a3fe9da3affb.png)

So the Question is, how can I tell angular that it has to add the styles to the Page?

Here is the complete code I’m using to create the control

var matCard = renderer.createElement('mat-card');
renderer.setAttribute(matCard , "class", "mat-card");
const matCardInner = renderer.createText('Dynamic card!');          
renderer.appendChild(matCard, matCardInner);
const container = targetEl.nativeElement;
renderer.appendChild(container, matCard);
Thanks for your help 
Michael

#### What is the use-case or motivation for changing an existing behavior?
I have to generate my view from a configuration!

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular ^5.2.4 
OS: Windows
typescript: ~2.5.3
browser: all

**Comment by jotatoledo** [comment]
1. A card is not a "material control", AFAIK there is no such term.
2. You are mixing dynamic element creation with dynamic component creation. You are currently doing the first, what you want is the second.

**Comment by DevVersion** [comment]
Hey, just creating a `HTMLElement` with the `mat-card` tag does not mean that the `MatCard` directive is being instantiated.

Since we add styles through the instantiated directive, just appending a `HTMLElement` that is not compiled through Angular, won't work.

Please consider using `<ng-template>` to render your app dynamically. Also there is a more programmatic way by using `ComponentFactoryResolver`. Related: [Potentially this helps](https://stackoverflow.com/questions/44284026/creating-a-angular2-component-with-ng-content-dynamically) for the content.

See: https://angular.io/guide/dynamic-component-loader.

**Comment by atmike** [comment]
@DevVersion: thx for pushing me in the right direction
