### ISSUE TITLE
Removing a tab gets the body and tab out of sync.

### ISSUE THREAD

**Issue by BenAychh** [angular/material2#12465]
#### What are the steps to reproduce?
https://stackblitz.com/github/benaychh/ClosingTabs

Click on "Name: diagram0" on the left and it will open a new tab.
Click on "Name: diagram1" on the left and it will open another tab.

Click the close on diagram0, the tab will disappear but the body no longer matches the tab up top. In my real app, the body is a fairly complicated graph.

**Comment by DevVersion** [comment]
Hi, I've looked at your demo and could reproduce your issue. Though, I could not reproduce this when looking at our demos.

* e.g. https://stackblitz.com/angular/pxgyvellkryq?file=app%2Ftab-group-dynamic-example.ts


Due to amount of files in your demo, we can't really have a quick look in order to identify the issue. If you want us too look closer into your **specific** demo, please try to reduce your code to a minimum that still shows the issue. Sorry.
