### ISSUE TITLE
Set-up cron job to run tests against Angular snapshots nightly

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#12516]
We should set up a cron job for a nightly test against the Angular master snapshots. Ideally this would be both for Travis and for CircleCI.

**Comment by DevVersion** [comment]
Some reminder: Since we now moved to CircleCI, the snapshot cronjob no longer runs. I'm thinking about using Bazel `--override_repository` flag to run tests against snapshot, but it feels a bit brittle because the rules API can change very quickly.

Rather it probably makes sense to run the `local_browsers` job (Chrome and Firefox) against the Github builds.

**Comment by DevVersion** [comment]
@jelbourn Also, what we could do very easily is building our components with Ivy. It's just one command line flag and we could verify that our components _will_ work with Ivy.
