### ISSUE TITLE
Warning message by using tooltip in <div> element.

### ISSUE THREAD

**Issue by kyusupov33** [angular/material2#12614]
#### Bug:
Bug
#### What is the expected behavior?
No warning message.
#### What is the current behavior?
Component matTooltip return error when i use it in div or button elements. But it correctly work in browser.

![image](https://user-images.githubusercontent.com/29026701/43952434-a179b4ce-9c9e-11e8-8951-68d130e13c72.png)

#### What are the steps to reproduce?

On stackblitz i dont have an error message
https://stackblitz.com/edit/angular-material2-issue-tooltip-div?file=app%2Fapp.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material v 6.4.2
angular v 6.1.0

**Comment by splincode** [comment]
also too

![image](https://user-images.githubusercontent.com/12021443/43956867-656bdf1a-9cae-11e8-96b5-47c430171548.png)

**Comment by josephperrott** [comment]
This looks to be an error in the way your IDE is consuming the typings provided by @angular/material.  

This error would show up if you are not importing the material component's `NgModule` declaring the directive being used in your module.

Are you seeing this same error while building and running your application?  As it stands it appears that this is actually an issue with your IDE rather than the Angular Material library.

**Comment by josephperrott** [comment]
Closing as we are not be able to reproduce this issue.
