### ISSUE TITLE
Sidenav not showing with angular 2.0

### ISSUE THREAD

**Issue by Castrovalva** [angular/material2#1266]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
A sidenav that I can open and close.

#### What is the current behavior?
Using the example provided at sidenav/README.md. Only showing: 'My regular content. This will be moved into the proper DOM at runtime.' Without the css, without console errors.

#### What are the steps to reproduce?
1. Install latest angular-cli (that is changed from SystemJS to Webpack)
2. Create new project
3. Add the following imports in app.module.ts: 'import { MdSidenavModule } from '@angular2-material/sidenav';', 'import { MdButton } from '@angular2-material/button';'
4. Add these imports to the imports array @NgModule().
5. Add the example  provided at [sidenav/README.md ](https://github.com/angular/material2/blob/master/src/lib/sidenav/README.md#examples)

#### Which versions of Angular, Material, OS, browsers are affected?
The current ones.

**Comment by jelbourn** [comment]
@Castrovalva [material2-app](https://github.com/jelbourn/material2-app) has a working sidenav

**Comment by RoxKilly** [comment]
@Castrovalva 

The README is unfortunately not that useful as-is, because it starts with the nav hidden with no way to show it.  [This Plunk](http://plnkr.co/edit/tl8CFw5yt9LMkRc7ELDq?p=preview) is probably what you're seeing.

To make things more useful, provide a way to open the sidenav as I do [on this Plunk](http://plnkr.co/edit/KJomI9be6kFFktJDcW5Q?p=preview)

**Comment by jelbourn** [comment]
We should update the example in the readme to include open and close...

**Comment by jelbourn** [comment]
Tracking in #1537
