### ISSUE TITLE
mat-form-field causes Error: ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by tinyweasel** [angular/material2#12714]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Angular test should pass

#### What is the current behavior?
Test errors with:
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'mat-form-field-should-float: false'. Current value: 'mat-form-field-should-float: true'.

#### What are the steps to reproduce?
Implement 'it should create' test on a component that uses mat-form-field. Do not set floatLabel or anything similar on the html file.

#### What is the use-case or motivation for changing an existing behavior?
Test won't pass and it should.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.7, Material 5.2.3, Chrome  

#### Is there anything else we should know?
Test passes if fixture.detectChanges(); not called.

**Comment by crisbeto** [comment]
Can you post what the test looks like?

**Comment by tinyweasel** [comment]
It was the basic "it should create" test. The issue turned out to be that the component was generating form fields dynamically using an array of fields, and the fields array was not mocked.

**Comment by tinyweasel** [comment]
I'm not how I did it this time, but I've recently fixed this in another instance by using an onPush ChangeDetectionStrategy.

**Comment by hollygood** [comment]
i also got the same error by using mat-form-field in ng-bootstrap modal: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'mat-form-field-should-float: false'. Current value: 'mat-form-field-should-float: true'.

ChangeDetectionStrategy.OnPush doesn't work for me.

The reason for this is when open a new dialog, the ng-bootstrap modal auto focus on the first focusable element within modal, which is my first mat-form-field, and the mat-form-field-should-float value change from 'false' to 'true' because of the focus event.

I manage to resolve this issue by moving the focus to other element instead of mat-form-field by using 'ngbAutofocus'.

example:

```
//--- the following code is within a ng-bootstrap modal
<button>View</button>

<form>
<div class="form-group">
        <mat-form-field>
            <mat-label>Test Field</mat-label>
            <input
                matInput
                type="text"
                formControlName="test"

            />
        </mat-form-field>
    </div>
</form>
```

**Comment by peter-snr** [comment]
@hollygood - Thanks, that's exactly what I was getting as well.  

So I used the **ngbAutofocus** to focus the cancel button on my form and that solved it.
