### ISSUE TITLE
cdkDrag containing textarea and cdkDragHandle causes positioning glitches

### ISSUE THREAD

**Issue by intellix** [angular/material2#12718]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To be able to drag elements containing a textarea like there isn't one

#### What is the current behavior?
They move to weird positions and cdkDragHandler doesn't get used

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/angular-3h4hbb?file=src%2Fapp%2Fapp.component.html

#### What is the use-case or motivation for changing an existing behavior?
You would expect any element inside a `cdkDrag` to work along with `cdkDragHandle`

**Comment by crisbeto** [comment]
Your example doesn't work because of the following:
1. The directive for the handle is called `cdkDragHandle`, not `cdkDragHandler`.
2. The preview "jumps" because it becomes larger than the initial element. You have to add `box-sizing: border-box` to it for the sizing to work correctly.

[Here's a working fork of the example.](https://stackblitz.com/edit/angular-yfarc7)
