### ISSUE TITLE
mat-icon does not render in currently selected mat-select > mat-option

### ISSUE THREAD

**Issue by wholypantalones** [angular/material2#12756]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To render the selected mat-icon in a mat-select component

#### What is the current behavior?
mat-icon does not render when an option is selected in a mat-select but does render in the mat-option

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz: https://stackblitz.com/edit/angular-select-option-matprefix-icons-issue?file=app/form-field-overview-example.html<br/>

#### What is the use-case or motivation for changing an existing behavior?
To visually see the selected mat-icon in a mat-select

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular v6.1.3
Angular material v6.4.5
Angular CDK v6.4.5

**Comment by crisbeto** [comment]
That's because the select only looks at the text value for an input to determine what to show in the trigger. You can customize the trigger text yourself with an icon using the `mat-select-trigger`. [There's an example of how you can do it in the docs](https://material.angular.io/components/select/overview#customizing-the-trigger-label).

**Comment by DashanWang1** [comment]
It is a bug. `mat-select-trigger` only solve some problem. But if I want to use `i18n` to translate what is in the `mat-select-trigger` what should I do? 

It is easy to translate the innerText in the `mat-option` and use the default behavior of `mat-select` to display the text. But when it comes to `mat-select-trigger`, because there is variable in this tag, how should I translate this then?

**Comment by jguyenot** [comment]
I, i solve this problem with the next code:

into html
`<mat-form-field>
    <mat-label>Libellé</mat-label>

    <mat-select-trigger>
        <mat-icon>{{ getSelectedValue() }}</mat-icon>
    </mat-select-trigger>

    <mat-select #selectIcon class="mat-select-icon" [(value)]="selectedIconItem">
        <mat-option [value]="0">
            <mat-icon>text_fields</mat-icon>
        </mat-option>
        <mat-option [value]="1">
            <mat-icon>title</mat-icon>
        </mat-option>
        <mat-option [value]="2">
            <mat-icon>format_bold</mat-icon>
        </mat-option>
    </mat-select>
</mat-form-field>`

into ts
`@ViewChild('selectIcon') selectIcon;
getSelectedValue() {
    if (this.selectIcon && this.selectIcon.options && this.selectIcon.options.length > 0) {
        return this.selectIcon.options.find(
            item => {
                return item.value === this.selectIcon.value;
            }
        ).getLabel();
    }
    return '';
}`

if this can help someone.
