### ISSUE TITLE
Failed: Can't resolve all parameters for MatTableDataSource: (?).

### ISSUE THREAD

**Issue by harshthakur92** [angular/material2#12854]
![untitled](https://user-images.githubusercontent.com/19525609/44675257-9becef00-aa4d-11e8-905e-4555b2c575f9.png)

Any Idea for this, in unit testing i am getting this error.
@mprobst  @alexweber  @alexeagle  @PowerKiKi 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6, Latest.

**Comment by GitSage** [comment]
Unless you have some reason to believe this is a bug in Angular Material rather than an error in your own code, you should close this and post your question to StackOverflow. That's the place to go for help.

Either way you need to include reproduction. What code are you testing against? Consider putting together an [SSCCE](http://sscce.org/).

**Comment by jelbourn** [comment]
Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are stack overflow, gitter, mailing list, etc.

(this is a canned response)
