### ISSUE TITLE
virtual-scroll: Change detection not triggered when using DataSource that uses viewChange.

### ISSUE THREAD

**Issue by grant77** [angular/material2#12869]
#### Bug, feature request, or proposal:
Change detection is not triggered when you scroll if you are using a custom DataSource that utilizes viewChange.  I have no idea what the appropriate way to fix this is, but this is what I did and it solved my problem:

```
const onRenderedDataChange = CdkVirtualForOf.prototype['_onRenderedDataChange'];
CdkVirtualForOf.prototype['_onRenderedDataChange'] = function (this: any) {
    onRenderedDataChange.apply(this, arguments);
    if (!this._changeDetectorRef) {
        this._changeDetectorRef = this._viewContainerRef.injector.get(ChangeDetectorRef);
    }
    this._changeDetectorRef.detectChanges();
}
```
#### What is the expected behavior?
Change detection should occur when the underlying DataSource's data changes.

#### What is the current behavior?
Change detection does not occur when the underlying DataSource's data changes.

#### What are the steps to reproduce?
This demo is almost identical to the one that I created for #11289.  In that demo I used setInterval(noop, 1000) to suppress this problem.  That is obviously a horrible solution, but I was trying to focus on that particular bug.  In this demo, just scroll to the bottom and the words "Loading..." will not disappear like they should.  If you put setInterval(noop, 1000) in the constructor or apply my patch mentioned above, the problem will go away.

https://stackblitz.com/edit/angular-material2-issue-czyxyd

#### What is the use-case or motivation for changing an existing behavior?
It's broken.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cdk-experimental 6.4.6

#### Is there anything else we should know?
No.

**Comment by mmalerba** [comment]
Hmm it looks like this may be caused by the fact that `cdkVirtualFor` is emitting on `viewChange` outside the `NgZone`. If I create an Observable based on `viewChange` and put it back inside the zone, change detection seems to trigger: https://stackblitz.com/edit/angular-material2-issue-sgwfxs?file=app/virtual-scroll/virtual-data-source.class.ts (of course there's still a mess of errors, I'll need to look into that too). I'll create a PR to emit in the zone so this workaround isn't needed

**Comment by grant77** [comment]
Awesome!  Thank you.
