### ISSUE TITLE
Bottom Sheet doesn't detect some async changes

### ISSUE THREAD

**Issue by yosoyju** [angular/material2#12931]
#### Bug, feature request, or proposal:
Component UI inside the Bottom Sheet doesn't seem to update when an async change is started early on (tested in constructor, ngOnInit, ngAfterContentInit, and ngAfterViewInit) but not resolved until after the popup animation is completed.

#### What is the expected behavior?
Change detection is not affected by the Bottom Sheet.

#### What is the current behavior?
Change detection seems to not work.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-qkeurg

#### What is the use-case or motivation for changing an existing behavior?
Changes should always be detected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 6.1.6
Material: 6.4.7
Mac OSX High Sierra
TS: 2.7.2
Browser: Chrome 68

**Comment by crisbeto** [comment]
That's because the bottom sheet triggers change detection when it's created and when the animation ends, but it doesn't have a way of anticipating when you might have done a change inside a timeout. You can tell Angular yourself when it's supposed to check by calling `ChangeDetectorRef.markForCheck`. [Here's a working fork of your example](https://stackblitz.com/edit/angular-vafpkj).
