### ISSUE TITLE
Material ecosystem thought

### ISSUE THREAD

**Issue by sarbull** [angular/material2#12992]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Make angular material component work with less or without any extra CSS, if possible.

#### What is the current behavior?
It's almost impossible to create a dashboard layout without adding tons of custom CSS so that it "does the job".

#### What is the use-case or motivation for changing an existing behavior?
I am trying to build a simple dashboard layout, meaning navbar, sidebar and content.. and:
- it's not responsive by default
- it's not layout intuitive, i'm not even sure if `mat-grid-list` is the answer in terms of grid mechanisms
- the components are very "rigid" they can't adapt in certain scenarios(button in navbar, buttons in list in sidebar, or other simple aggregations)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All.

#### Is there anything else we should know?
Angular Material is an ecosystem hard to use and develop with, it's not just an UI framework, it's something like this:

![image](https://user-images.githubusercontent.com/1864112/45116987-0cd28c00-b15d-11e8-9d70-e489e835481a.png)

P.S. Is it just me?

**Comment by jelbourn** [comment]
Angular Material aims to provide a set of atomic components as the building blocks for an application. It _intentionally_ does not provide a system for application-level layout, since this is a completely separate concern from the individual components themselves. By decoupling these concerns, the components can be used with any layout system instead of tying users into something that may not be appropriate for their project.

**Comment by TmanTman** [comment]
@sarbull I've also struggled with this, but have found that this library should be used alongside something like Angular-Flex for layout. Otherwise, using Bootstrap provides the whole ecosystem.
