### ISSUE TITLE
[Feature] Full support for theming components

### ISSUE THREAD

**Issue by jcano** [angular/material2#13008]
A theme is generally considered more than just a color palette for the site. Typography, border radius, shadows, button shapes, etc are important parts of a theme that cannot be customised at this time. Material is a set of design guidelines, not a specific look and feel, and this has been emphasised by the latest documentation and articles about Material. For example:

https://material.io/design/material-studies/

Plain material makes all apps lose their identity, so there should be a way of customising it. There are currently two ways of allowing for this:

1. By adding some sort of CSS-in-JS code that allows the manipulation of the elements, as for example [Material UI does in React](https://material-ui.com/customization/themes/).
2. By separating the styles into a SCSS/LESS library with variables that allow customisation, as for example [Bootstrap](https://getbootstrap.com/docs/4.1/getting-started/theming/) and [SemanticUI](https://semantic-ui.com/usage/theming.html) do.

The current situation is that Angular Material doesn't support JS methods to change the theme, and the CSS used by the library is not documented so "hacking" a theme is a daunting task.

**Comment by jelbourn** [comment]
For the time being we have no plans to support APIs for anything beyond color and [typography](https://material.angular.io/guide/typography). 

We feel strongly that theming should be done at _compile time_. Dynamically changing styles at run-time  (like AngularJS did) incurs what we consider to be an unacceptable performance cost.

Customization through something like Sass variables is not a viable option for a component-centric model of development because, by the time the component is consumed, the source Sass has already been compiled into CSS and associated with the component as one atomic unit. To make this work, you would have to insert a dependency (overrides) into your dependency, which doesn't play well with build systems and packaging in general. 

We'll have a lot more options for theming once we no longer support IE11 (roughly Jan 2020), when CSS custom properties become available.
