### ISSUE TITLE
No provider for CdkAccordion!  StaticInjectorError

### ISSUE THREAD

**Issue by ravishivt** [angular/material2#13069]
#### Bug, feature request, or proposal:

Bug, very similar to https://github.com/angular/material2/issues/10820 but for `CdkAccordion` instead of `Overlay`.

#### What is the expected behavior?

`CdkAccordion` already marked as a provider when importing the `CdkAccordionModule`.

#### What is the current behavior?

I'm trying to use `CdkAccordion` in my application following the instructions from https://medium.com/@simonb90/hidden-features-of-angular-material-cdk-ee07066d73d1.  Attempting to inject CdkAccordion into a component generates the below stacktrace.  

```js
Error: StaticInjectorError(AppModule)[AppComponent -> CdkAccordion]: 
  StaticInjectorError(Platform: core)[AppComponent -> CdkAccordion]: 
    NullInjectorError: No provider for CdkAccordion!
    at NullInjector.get (injector.ts:35)
    at resolveToken (injector.ts:337)
```

#### What are the steps to reproduce?

https://stackblitz.com/edit/cdk-accordion-mnfzpd?file=src/app/app.component.ts

#### Is there anything else we should know?

A workaround is to add `CdkAccordion` to the AppModule's `providers`.

**Comment by josephperrott** [comment]
You are running into this issue because your component needs to have accordion provided above it in the component tree, but since it is your component is the root of your tree it does not exist.

[In `CdkAccordionItem`](https://github.com/angular/material2/blob/master/src/cdk/accordion/accordion-item.ts#L99), `CdkAccordion` is optionally injected `@Optional() @SkipSelf() public accordion: CdkAccordion`.

It does not make sense for the CdkAccordion to be generaly placed as a provider because it does not work when provided without a component instance existing.

**Comment by ravishivt** [comment]
Thanks, I learned something new about Angular DI.  I didn't need `accordion: CdkAccordion` in my component.  I just needed to pass it to `super()`.  So the fix was to not explicitly add `CdkAccordion` as a provider and instead use `@Optional() accordion: CdkAccordion,`.
