### ISSUE TITLE
mat-ripple fires ripple animation when touch dragging list on mobile

### ISSUE THREAD

**Issue by mbellezi** [angular/material2#13093]
#### Bug, feature request, or proposal:
Bug?

#### What is the expected behavior?
A mat-list with mat-list-item using the mat-ripple on each list element should not fire the ripple animation on touch dragging, only on click or tap without dragging. 

#### What is the current behavior?
A mat-list with mat-list-item using the mat-ripple on each list element fires the ripple animation on touch dragging the list. This is very distracting and not in line with mobile apps.

#### What are the steps to reproduce?
Create a long list like:
<mat-list>
 <mat-list-item mat-ripple (click)="doSomething()"> Pepper </mat-list-item>
 <mat-list-item mat-ripple (click)="doSomething()"> Salt </mat-list-item>
...
 <mat-list-item mat-ripple (click)="doSomething()"> Paprika </mat-list-item>
</mat-list>

Tries to drag tha list on mobile devices

#### What is the use-case or motivation for changing an existing behavior?
To be inline with other material apps on mobile

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.4.7, Angular Materia 6.4.7, Typescript 2.7.2

**Comment by DevVersion** [comment]
Thanks for your issue. This doesn't happen in Android because the ripples don't show up at `touchstart` for the Android implementation of the Material Design. There might be special behavior specifically for Android, but we try to match MDC and the public guidelines which also cover partially desktop.

* https://material.io/design/interaction/states.html#pressed

Also there is no easy way to differentiate between a touch that came from scrolling or not. Since the current implementation matches the specs and is aligned with MDC, I don't think we can address that issue.
