### ISSUE TITLE
"ng update @angular/material" installs 7.0.0-beta.1 instead of 6.4.7 (when upgrading from 5.2.5)

### ISSUE THREAD

**Issue by mattva01** [angular/material2#13204]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The installed version and that in package.json should be 6.4.7 

#### What is the current behavior?
7.0.0-beta.1 is installed, with the same reflected in package.json.

#### What are the steps to reproduce?
Pastebin from an existing project here: https://pastebin.com/bYkbWTdz

Was able to kludge a reproduction together with a freshly generated angular codebase inside a docker container here:  https://pastebin.com/xCRtMDwF

#### What is the use-case or motivation for changing an existing behavior?
NA

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 5.2.5 (issue might be in migration scripts in 6.4.7)

#### Is there anything else we should know?
Sorry if this is a little unclear, it's not very easy to generate/reproduce an angular codebase that's not at the latest version.

**Comment by DevVersion** [comment]
Thanks for your issue. This is indeed an issue with the old schematics because `6.4.7` accidentally installs `@angular/material@next` after the migrations run.

We've made a lot of changes to the schematics for `7.0.0`, and those should avoid such issues in the future. Also migration errors like you've got (_for the check-inheritance stuff_) shouldn't show up anymore.

I don't think that we will have any patch release to fix this issue, so I'd recommend waiting until V7 is released, or using the beta versions of it.

* `ng update @angular/material@next`.

Thanks again!
