### ISSUE TITLE
Mat-grid-tile height set to 0 and is not visible on MS Edge

### ISSUE THREAD

**Issue by tusharchutani** [angular/material2#13252]
#### Bug, feature request, or proposal:
Bug 

#### What is the expected behavior?
I am suppose to see mat-grid-tile on the page I am rendering

#### What is the current behavior?
The height of the mat-grid-tile is set to 0 on MS-Edge

#### What are the steps to reproduce?
In the template file of my component 

```
<mat-grid-list cols="2" rowHeight="350px;"  (window:resize)="onResize($event)">
  <mat-grid-tile id="jabroni1"><h1>hello this is heading 1</h1></mat-grid-tile>
  <mat-grid-tile id="jabroni2"><h2>hello this is heading 2</h2></mat-grid-tile>
</mat-grid-list>
```
[StackBliz](https://stackblitz.com/edit/angular-n4phua)

Run the app and go to the page containing the component on MS-Edge 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6 
Typescript: 2.7.7
Windows 10 
MS-Edge 42.17134.1.0

**Comment by crisbeto** [comment]
Your issue comes from the fact that you're setting the `rowHeight` to an invalid value (`350px;`). Notice how there's an extra semicolon at the end. It will be ignored by Chrome, but Edge will consider the expression as invalid. I've submitted #13254 which will throw an error for cases like this one.
