### ISSUE TITLE
Unable to `npm i` on material2 repo

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/material2#13383]
#### Bug, feature request, or proposal:
I wanted to see if I can contribute to angular material so I followed steps from [DEV_ENVIRONMENT.md](https://github.com/angular/material2/blob/master/DEV_ENVIRONMENT.md). However, when running `npm install`, I get an error (see below)

#### What is the expected behavior?
Should not get an error

#### What is the current behavior?
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\edmitry\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\edmitry\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=C:\\Source\\Random\\material2\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.
node" "--module_name=grpc_node" "--module_path=C:\\Source\\Random\\material2\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
gyp ERR! cwd C:\Source\Random\material2\node_modules\grpc
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Windows 10
node -v: v10.0.0
npm -v: 6.0.0

**Comment by crisbeto** [comment]
This seems like something wrong with your setup. Installing and building the project works fine for me on Windows 10.

**Comment by jelbourn** [comment]
Issues like this get closed because they genuinely have nothing to do with the repo itself. There is no action anyone on the team can take to resolve install problems on your specific environment. At least two of our core team members develop every day on Windows.

We don't use Angular CLI because we're the first testing ground for new features or changes in the Angular compiler (before Angular CLI supports the changes), so we need to generally work directly against the lower-level APIs.
