### ISSUE TITLE
Package docs content into an npm package

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#13454]
We currently publish the docs content to https://github.com/angular/material2-docs-content in an ad hoc structure. It's not an npm package, meaning we need a bash script to pull in the content to the right place. 

**Things that are pending:**

- [X] Build material-examples using Bazel
- [x] Generate highlighted files from example source w/ Bazel
- [x] Docs SCSS should no longer expect a class for each markdown HTML element
- [x] Package all together in a NPM package:
   * Example package (needed for show-casing examples in the docs)
   * StackBlitz example source files (needed for external stackblitz examples)
   * Highlighted example source files (in `.html`, needed for source view of examples)
   * Guides which will be shown in the docs
   * Components overview files

**Comment by DevVersion** [comment]
I think we discussed just having another Github builds repository for that, right?

**Comment by jelbourn** [comment]
Is there any reason not to reuse the existing repo?

**Comment by DevVersion** [comment]
I was just thinking that we need another repository because one would be for the `@angular/material-examples` package and the other one just for the individual API/guide/StackBlitz files.

```json
dependencies: {
  "@angular/material-examples": "github:angular/material2-docs-content"
}
```

After re-reading, I think you've actually meant that we should somehow package the HTML API, guide and StackBlitz files into the NPM package. That way we would eliminate all scripts, right?

**Comment by jelbourn** [comment]
Yep, exactly

**Comment by devversion** [comment]
We can close this once #14612 and #14634 are merged.
