### ISSUE TITLE
MdTabs min-width is wrong for mobile and gets in the way

### ISSUE THREAD

**Issue by dasois** [angular/material2#1350]
#### Bug, feature request, or proposal:
Bug: MdTabs have a min-width of 160px, which is only true for larger views, [but not for mobile views](https://material.google.com/components/tabs.html#tabs-specs)

#### What is the expected behavior?
Mobile Tabs should have min-width of 72px.
After that the user should be able to switch between scrollable tabs and fixed tabs (that's for another issue).

#### What is the current behavior?
Tabs are 160px and thus too big.

#### What is the use-case or motivation for changing an existing behavior?
For mobile views style has to be overridden with !important, which is bad practice.

**Comment by philip-firstorder** [comment]
According to the [guidelines](https://material.io/design/components/tabs.html#spec) it should have a min-width of 90px on all devices, and a max-width of 360px.

Because the smallest mobile width is 360px, and the smallest navbar width is also 360px.
which combined with this rule
> Don’t use more than four fixed tabs in a set.

gives us 360px / 4 = 90px

Setting this regardless of screen width will also solve #2829

This ticket should be reopened and fixed.
