### ISSUE TITLE
Z-Index NOT working on Angular's Material Dialog 

### ISSUE THREAD

**Issue by aidvb** [angular/material2#13664]
#### Bug:
Z-Index NOT working on Material Dialog 

#### What is the expected behavior?
Z-Index should work on Material Dialog or Dialog should be on top of everything else.

#### What is the current behavior?
Material Dialog gets covered by select's options that are below.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-gsa8kr-rkss7t?file=app/dialog-overview-example.html
Screenshots: https://postimg.cc/gallery/2i3tc2sbc/

#### Is there anything else we should know?
1. Type text.
2. Select dropdown.

Tried CSS fixes:
.modal__content,
dialog-layout,
mat-dialog-container,
.mat-dialog-container,
#cdk-overlay-0,
.cdk-overlay-pane {z-index: 9999 !important;}

NONE of that worked.

**Comment by josephperrott** [comment]
This actually working as expected as stacking order is not something that can be defined/controlled for a native `<select>`'s `<option>`s.

Since the `<select>` is still opened and has the current focus (at the OS level) it appears in the page and renders above the browser similar to a right-click context menu.

**Comment by aidvb** [comment]
The workaround has been found, please look at https://stackoverflow.com/questions/52871875/z-index-not-working-on-angulars-material-dialog
