### ISSUE TITLE
Binding between examples and git

### ISSUE THREAD

**Issue by briangmilnes** [angular/material2#13716]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Add a github link to the examples. When you go to stackblitz you can't easily see which
revision (branch) of the material2 examples you are using.

#### What is the current behavior?
You go to stackblitz but can't see which revision of the git code to look at for details.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
It is confusing to new users. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All.

**Comment by josephperrott** [comment]
Closing as you are able to determine what version of all libraries you are using in stackblitz by looking in the dependencies section (see below). This is actually preferable to being tied to a version in github since its possible for the same example to work across multiple releases.

![image](https://user-images.githubusercontent.com/10864441/47297302-8ae1d980-d5c9-11e8-8cde-fd4d61b8e869.png)
