### ISSUE TITLE
disabled input on mat-checkbox not behaving like with other components

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material2#13739]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The disabled attribute/input should have the same behavior on all input elements. 

#### What is the current behavior?
```
<!-- This does not disable the checkbox -->
<mat-checkbox disabled>Check me! disabled</mat-checkbox>
<!-- This does disable the checkbox incorrectly -->
<mat-checkbox disabled="false">Foo</mat-checkbox>

<!-- This does disable the button -->
<button mat-button disabled>Bar</button>
<!-- This does not disable the button -->
<button mat-raised-button disabled="false">Click me! disabled="false"</button>
```

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material-checkboxes-hkdft7

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
6.1.10/6.4.7

#### Is there anything else we should know?
`<mat-checkbox disabled>Foo</mat-checkbox>` used to work, not exactly sure when it broke.

**Comment by thomaspink** [comment]
`<mat-checkbox disabled="false">Check me! disabled="false"</mat-checkbox> ` seems correct to me. 
1. If you want to set the boolean value `false` use a binding `[disabled]="false"` otherwise it a generic string like `disabled="any string you want"` which will always resolve to true (also like `disabled="disabled"`)
2. Native checkbox behaves exactly the same (does disable the input): `<input type="checkbox" disabled="false">`
