### ISSUE TITLE
mat-radio-button disable don't work

### ISSUE THREAD

**Issue by Zacknero** [angular/material2#13785]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
When set the attribute "disable" this to be disabled and is ok.

#### What is the current behavior?
The (click) event works whit the radio disabled

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-cydwd3

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.0, Material 6.4.2 and 7.0.1, Typescript 2.7.2, All browsers

**Comment by UserGalileo** [comment]
The '_click_' event shouldn't fire on a disabled input only if we're talking about native input elements.

Since `<mat-radio-button>` is not a native input element, when you set the click listener on it you're actually listening for a click on `<mat-radio-button>` itself, which is doable and there's nothing that can be done to prevent the 'click' event from firing _from inside_.

Therefore, you should use the '_change_' event to listen for a value change, or you could fire the desired function only if the input isn't disabled:

`(click)="!isDisabled && onClick()"`

**Comment by crisbeto** [comment]
@UserGalileo is correct. Another workaround can be to set `pointer-events: none` on the disabled radio buttons. Closing since there isn't much we can do about it.

**Comment by Zacknero** [comment]
> @UserGalileo is correct. Another workaround can be to set `pointer-events: none` on the disabled radio buttons. Closing since there isn't much we can do about it.

Ok is closed. For me to be set one property when passing a boolean value and disable the radio. How the <input> attribute.

Thanke you boys @UserGalileo @crisbeto
