### ISSUE TITLE
Icon: Style definitions in SVG are bleeding to global styles

### ISSUE THREAD

**Issue by bene-starzengruber** [angular/material2#13896]
#### Bug, feature request, or proposal:
Style tags in SVG defs are not enclosed to the icon but applied globally

#### What is the expected behavior?
Styles defined in the SVG should only be effective inside of the SVG

#### What is the current behavior?
Styles are applied globally (multiple icons => overriding styles of each other)

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-73v5nm?file=src%2Fassets%2Ficon2.svg
Two icons are registered - both have a style definition with different colors but as the styles are bleeding globally, both icons get the same fill.

#### What is the use-case or motivation for changing an existing behavior?
Using Material-Icons is not possible if designers are using <style> tags in svgs

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.0.1

#### Is there anything else we should know?
View Encapsulation: Shadow Dom would work but as it is not supported in all browsers, we can't use this

**Comment by josephperrott** [comment]
Closing as this is actually something that falls outside of the purview of MatIcon.  MatIcon's responsiblity is only for placing the font or SVG icon into the correct place.  It does not factor in any styling that may be at play.

Additionally, because the SVG is projected into the component, Angular does not do emulated view encapsulation so the styling for the SVG elements cannot be altered.
