### ISSUE TITLE
mat-stroked-button with matBadge is cropped

### ISSUE THREAD

**Issue by tjaussoin-luna** [angular/material2#13909]
#### Bug, feature request, or proposal:
On a mat-stroked-button with a matBadge, the badge is cropped.

#### What is the expected behavior?
matBadge not cropped, like it is on a mat-button.

#### What is the current behavior?
matbadge is cropped.

#### What are the steps to reproduce?
Change the mat-raised-button to a mat-stroked-button here :
https://stackblitz.com/angular/gxraooqgqod?file=app%2Fbadge-overview-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7
Angular Material 7.0.2
Browser: Chrome

**Comment by DevVersion** [comment]
Good catch. This is caused by https://github.com/angular/material2/commit/4cdf5bafd6af0085d3fe93c755a92c92bfd3e483.

We should consider removing the `overflow: hidden` again, and just expanding the overlays by the amount of pixels the border takes up.

This is how it would be if we just remove the overflow and specify a `border-radius` for the underlying ripple container, and focus overlay.

![image](https://user-images.githubusercontent.com/4987015/47302045-c5c32c00-d620-11e8-9d58-bc34b421943f.png)

**Comment by DevVersion** [comment]
As mentioned above, we could technically expand the `focus-overlay` and `ripple container` by the _width of the border_, in order to be able to remove the `overflow: hidden`.

![image](https://user-images.githubusercontent.com/4987015/47805918-cb172980-dd38-11e8-8c41-e885d279a670.png)

The trade-off here would be just that it won't work properly if someone changes the `border-width` of the stroked button. Any thoughts @crisbeto?

**Comment by crisbeto** [comment]
It should be fine, as long as we put the border width in a variable.
