### ISSUE TITLE
bug: ngIf disables cdkDropListConnectedTo

### ISSUE THREAD

**Issue by bbogdanov** [angular/material2#13998]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Having the possibility of drag and drop items from one list container to another.

#### What is the current behavior?
Enable to drag from both list, unenable to move item from list to another list.

#### What are the steps to reproduce?
By adding ngIf directive on both lists.

https://stackblitz.com/edit/angular-material-todo-dragndrop?file=app%2Fcdk-drag-drop-connected-sorting-example.html

#### What is the use-case or motivation for changing an existing behavior?
Showing a list when it has received items and also if there are any other lists the user to be able to move the items between these lists.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All the versions are listed in the stackbliz example.

#### Is there anything else we should know?
I don't have time rn to check why, but I think it is related to TemplateRef. 

I searched in the issues I didn't find any related issues so if there is one I am sorry.

**Comment by crisbeto** [comment]
It's because the `*ngIf` turns it into an `ng-template`. You can work around it [by using a string ID instead](https://stackblitz.com/edit/angular-material-todo-dragndrop-tzeqky). We also have https://github.com/angular/material2/pull/13754 coming up which will make it easier to connect drop containers. Closing the issue since there isn't much we can do about it on our end.
