### ISSUE TITLE
Snackbar: Prevent same multiple messages option.

### ISSUE THREAD

**Issue by SergejSa** [angular/material2#14029]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
Do not show the same message over and over again

#### What is the current behavior?
it breaks and is not reactive anymore

#### What are the steps to reproduce?
open a message every second, should have the same effect. 
for me my error handler throws a binding error for example like every second.

#### What is the use-case or motivation for changing an existing behavior?
easier global error handling.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.02

**Comment by crisbeto** [comment]
This will be tricky to handle on our end, because we support showing both plain text snack bars and projected components inside the snack bar container, which means that we have no way of knowing what the content will be. You should be able to get it working on your own by keeping track of the last message that was displayed and deciding whether to show another snack bar based on it.
