### ISSUE TITLE
mat-expansion-panel-body cannot override padding style

### ISSUE THREAD

**Issue by chrisrrowland** [angular/material2#14069]
#### Bug, feature request, or proposal:
I'm doing recursive embedding of mat-expansion-panel.
I tried to reduce the padding-right of the mat-expansion-panel-body but the style
.mat-expansion-panel-body {
    padding: 0 24px 16px;
}
is always used.

#### What is the expected behavior?
Respect my css

#### What is the current behavior?
my style is not used

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-ojcyga-kmgpkr

**Comment by josephperrott** [comment]
From looking at your stackblitz, it looks like your styles that you created did not apply because of view encapsulation.  Since your component uses emulated encapsulation, the `nghost` special selectors are added to the styles, instead to style here you need to use a deep selector or turn off view encapsulation. 

You can see in this [fork of your stackblitz](https://stackblitz.com/edit/angular-ojcyga-cqf8kb?file=app%2Fexpansion-overview-example.css), it works as expected with view encapsulation turned off.
