### ISSUE TITLE
Add option to disable dialog click-outside-to-close

### ISSUE THREAD

**Issue by jcmoore0** [angular/material2#1419]

**Comment by JanStureNielsen** [comment]
Dup of #114

**Comment by aciccarello** [comment]
@jcmoore0, Your issue is a bit hard to read. Maybe separating your answers from the questions (so they are not bold) will make it easier. Also, a more descriptive title would be good. As far as I can tell this is not a duplicate.

>  Clicking outside the dialog container closes MdDialogRef. I would like to be able to turn disable this, so the user may not click outside and is only allowed to interact with the most recent "highest z-index" MdDialog open. We use one dialog on top of another.

Is there a way to avoid having multiple dialog boxes on top of each other?
