### ISSUE TITLE
Performance test infrastructure

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#142]
- [ ] Set up Google Compute Engine environment
- [ ] Benchpress tests run on GCE
- [ ] Travis CI calls out to GCE and gets results back

**Comment by cgatian** [comment]
@jelbourn This week I started doing some research in this area. Since this is an area you're looking to dig into I thought I'd share what I've accomplished and hopefully you could provide some feedback.

Also, I'm looking to create a package that would allow other component libraries to easily consume and capture metrics.

My current process:
* Create a module for the component
* Compile an AOT/minified version of the component module factory
* Open browser via protractor and bootstrap Angular
* Once Angular is ready dynamically load component module factory
   * This is done to gather rough download size metrics
* Gather metrics on size and performance

The metrics I'm currently capturing:

- **componentBootstrapTime**: time it takes for ngModuleFactory and ngComponentFactory to create component
- **componentSize**: gziped/minified size of the component and module factory
- **onInitTime**: time OnInit runs (if available)
- **onAfterViewInit**: time OnAfterViewInit runs (if available)
- **componentStableTime**: time it takes for ngZone onStable to run after component has been created on View

![e2e](https://user-images.githubusercontent.com/1752170/26978858-e6e61254-4cfa-11e7-8394-d41635041411.gif)

**Comment by jelbourn** [comment]
@cgatian we actually already have something for this built; it uses some of Google's internal tooling. We use [Angular's Benchpress](https://github.com/angular/angular/tree/master/packages/benchpress) to collect performance information. 

The biggest challenge with running tests like this is having a **normalized environment**. Even if you run the tests on the same machine on the same browser, the results can be affected by any number of things going on with the machine (other processes running, memory usage, etc). In order to collect meaningful data over time, all of these factors need to be controlled.

**Comment by cgatian** [comment]
@jelbourn sorry I should've mentioned this is using Angular Benchpress.

Normalized environments aside, I was looking for feedback in the types of metrics your team was looking to collect. I imagine you have put some thought into this and wondered how close or far off I was with my approach.  This is mostly due to the resources around the subject are extremely scarce.

**Comment by jelbourn** [comment]
Those are all useful metrics, though it's largely focused around start-up. Capturing metrics for interactions as well is useful.

**Comment by jelbourn** [comment]
Closing this since we now have this running in Google's internal infrastructure.
