### ISSUE TITLE
Google translate to english breaks icons

### ISSUE THREAD

**Issue by vapits** [angular/material2#14334]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Keep the icon position.
![image](https://user-images.githubusercontent.com/8594758/49293396-53abf580-f4b0-11e8-8268-bdd39300233e.png)

#### What is the current behavior?
All icons from all places (including buttons, text etc) are loosing their position.
* Position is not altered in anyway from the original.
Go to following stackbliz and then the compiled result open it in new window. Then you can replicate the issue: https://stackblitz.com/edit/angular-material2-issue-2qhorc 
![image](https://user-images.githubusercontent.com/8594758/49293441-73dbb480-f4b0-11e8-9b5e-5a48b1fd9c91.png)

#### What are the steps to reproduce?
Right click on a non-english web app with Angular Material and icons:
![image](https://user-images.githubusercontent.com/8594758/49293426-69211f80-f4b0-11e8-8759-2dd105d2fc2e.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Chrome 70.
Angular 7.x
Angular Material 7.x

**Comment by crisbeto** [comment]
This seems to be because Google Translate adds a couple of layers of `font` tags which throw off the Material styling. I'm not sure whether this is something we want to support @jelbourn.

**Comment by jelbourn** [comment]
I don't consider this to be within the purview of Angular Material; it's more of a bug with Google Translate and font-icons.

**Comment by pavel-agarkov** [comment]
before translation | after translation
:---:|:---:
![image](https://user-images.githubusercontent.com/24639631/51412407-8bfcb580-1b7c-11e9-8d4c-9f1204b556b7.png) | ![image](https://user-images.githubusercontent.com/24639631/51412741-aaaf7c00-1b7d-11e9-9921-060f8e28a337.png)

Currently the problem is that words inside `mat-icon` are getting translated when the target language is not English. In my example translated icon has slightly more lines...
`class="notranslate"` can be added to element to prevent translators from doing their job.
@jelbourn, @crisbeto, what do you think about automatically adding this class to `mat-icon` by default?

**Comment by pavel-agarkov** [comment]
@jelbourn please take a look: #14889
