### ISSUE TITLE
improvments in CdkTable._getAllRenderRows()

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#14416]
The classic template will not fit here because the behavior is not visible much...

I found some things I can't explain logically, which makes the code hard to read... if I'm wrong - sorry in advance:

```ts
  private _getAllRenderRows(): RenderRow<T>[] {
    const renderRows: RenderRow<T>[] = [];

    // Store the cache and create a new one. Any re-used RenderRow objects will be moved into the
    // new cache while unused ones can be picked up by garbage collection.
    const prevCachedRenderRows = this._cachedRenderRowsMap;
    this._cachedRenderRowsMap = new Map();

    // For each data object, get the list of rows that should be rendered, represented by the
    // respective `RenderRow` object which is the pair of `data` and `CdkRowDef`.
    for (let i = 0; i < this._data.length; i++) {
      let data = this._data[i];
      const renderRowsForData = this._getRenderRowsForData(data, i, prevCachedRenderRows.get(data));

      if (!this._cachedRenderRowsMap.has(data)) {
        this._cachedRenderRowsMap.set(data, new WeakMap());
      }

      for (let j = 0; j < renderRowsForData.length; j++) {
        let renderRow = renderRowsForData[j];

        const cache = this._cachedRenderRowsMap.get(renderRow.data)!;
        if (cache.has(renderRow.rowDef)) {
          cache.get(renderRow.rowDef)!.push(renderRow);
        } else {
          cache.set(renderRow.rowDef, [renderRow]);
        }
        renderRows.push(renderRow);
      }
    }

    return renderRows;
  }
```

## (1) Redundant if:

I think this if statement can be removed:

```ts
      if (!this._cachedRenderRowsMap.has(data)) {
        this._cachedRenderRowsMap.set(data, new WeakMap());
      }
```

Because `_cachedRenderRowsMap` is being reset before the loop:

```ts
 this._cachedRenderRowsMap = new Map();
```

And since we loop over each `data` item once, it will always be missing...

> Remember this fact, looping over `data` once

## (2) Redundant array in the cache that is always a single item

The cache is defined like this:

```ts
private _cachedRenderRowsMap = new Map<T, WeakMap<CdkRowDef<T>, RenderRow<T>[]>>();
```

There is a comment for why the array is there:

> The array is necessary to handle cases where the data array contains multiple duplicate data objects and each instantiated `RenderRow` must be stored.

If a data item is our instance (T) we can render between 1 to N rows, depending on the `CdkRowDef` we have and their `when` predicate.

This is expressed through `Map<T, WeakMap<CdkRowDef<T>, RenderRow<T>>>`... For each data item T we have a map of `CdkRowDef` that points to an object that holds the same instances of `T` and `CdkRowDef<T>` plus the data index of T...

What is the scenario that can possibly lead to multiple `RenderRow`, this doesn't make sense because `RenderRow` itself holds the values we need to query it in the cache maps...

Meaning:

```ts
const renderRows = this._cachedRenderRowsMap.get(X).get(Y); 
for (const rr of renderRows) {
  rr.data === X // TRUE
  rr.rowDef === Y // TRUE
}
```

The argument get's stronger in:

```ts
  private _getRenderRowsForData(
      data: T, dataIndex: number, cache?: WeakMap<CdkRowDef<T>, RenderRow<T>[]>): RenderRow<T>[] {
    const rowDefs = this._getRowDefs(data, dataIndex);

    return rowDefs.map(rowDef => {
      const cachedRenderRows = (cache && cache.has(rowDef)) ? cache.get(rowDef)! : [];
      if (cachedRenderRows.length) {
        const dataRow = cachedRenderRows.shift()!;
        dataRow.dataIndex = dataIndex;
        return dataRow;
      } else {
        return {data, rowDef, dataIndex};
      }
    });
  }
```

Where only the first item is taken from the cache

```ts
     const dataRow = cachedRenderRows.shift()!;
```

Now `_getRenderRowsForData` is called from (and only from) `_getAllRenderRows` and the cache that is sent to it is `prevCachedRenderRows.get(data)`, coming back to the fact that `data` is used once in the iteration thus that cache array will never be used again, i.e. **it always uses 1 item from the array**

> I also don't understand why we `shift`... mutating the cache that we don't use again...

**Comment by andrewseguin** [comment]
Consider the following example where we have 
 - A simple data source array: `[true, true, false]`
 - A table that renders a single row per boolean
 - A single column per row that shows the value of the boolean

https://stackblitz.com/angular/ndjvyykgoje?file=app%2Ftable-basic-example.html

In this case, the table renders three rows. 

Now consider there is a button that swaps the second and third boolean to change it into `[true, false, true]`. Ideally the table recognizes that it needs to swap two rows instead of destroying and creating two rows.

In order to do this, it needs to compare the previous render to the next one. It does this using the `RenderRow` objects to identify each row. 

First it takes a cache of what it previously rendered, as a map of data to rendered rows:

`true`: [RenderedRow, RenderedRow],
`false`: [RenderedRow]

Then it goes one by one through the data and pops off a `RenderedRow` if one exists for that data, otherwise it makes a new `RenderedRow`.

In our case, it finds a `RenderedRow` for each new row and when it runs it through the `IterableDiffer`, it finds that it can move two rows since their identities matched up.

----------------------

In case you want to see this in the code/tests, try removing the `if (!this._cachedRenderRowsMap.has(data))` conditional from table.ts. Run the tests and you'll see one failure that captures this use case.

I understand that this code has evolved into something far more complex than it used to be, but I assure you a whole lot of thought and care has gone into making the code as straightforward as possible. 

I appreciate your in-depth look and I hope my explanation clears some things up. Let me know if you have any follow-up questions.
