### ISSUE TITLE
MatTable renderRows not working when sorting is used

### ISSUE THREAD

**Issue by dav1126** [angular/material2#14451]
#### What is the expected behavior?
Adding data to the dataSource and calling renderRows() should make the new data appear in the table.

#### What is the current behavior?
When mat-table sorting is used, renderRows doesnt add the new data in the table.

#### What are the steps to reproduce?
This is the sorting example from the doc. I added a button to add data to the dataSource.
StackBlitz starter: https://stackblitz.com/edit/angular-tverea<br/>

This same example is working if we remove the sorting: 
https://stackblitz.com/edit/angular-hyew7w-sjrovr?file=app%2Ftable-sorting-example.ts

**Comment by andrewseguin** [comment]
The datasource provides the data array to the table via an Observable. That Observable emits when new data is set. In your example, that stream will not emit new data to the table since you are not providing a new data array.

Instead, take the data and perform on operation on it, and then provide it to the datasource so it knows to emit a new value to the table.

```ts
  add() {
    const data = this.dataSource.data;
    data.unshift(ELEMENT_DATA[2]);
    this.dataSource.data = data;
  }
```

https://stackblitz.com/edit/angular-tverea-h47kpv?file=app/table-sorting-example.ts

The `renderRows` function should need to be called in the case where you provide an array directly to the table (e.g. `[dataSource]="myDataArray"`)
