### ISSUE TITLE
[cdkDragDrop] override scale porperty so can't use with scale

### ISSUE THREAD

**Issue by Flashunt** [angular/material2#14590]
#### Please describe the feature you would like to request.
Please support somehow the scale of dragDropContainer.

#### What is the use-case or motivation for this proposal?
I have too many content on a page, and i have a scaler function with drag and drop and the dragDrop kill my scaler :( 

#### Is there anything else we should know?
Stackblitz link for example: https://stackblitz.com/edit/angular-na8k5p?file=app%2Fcdk-drag-drop-custom-placeholder-example.css

**Comment by crisbeto** [comment]
It doesn't work, because the preview element isn't under the drop list in the DOM hierarchy which means that the transform doesn't apply to it. You can use the `cdk-drag-preview` class to style the preview while it's being dragged. That being said, styling the preview itself won't work for your case, because we use `transform` to move the preview around on the page. You might be able to work around it by using a custom preview.

This is definitely a valid issue, however I have to close it, because there's no performant way to solve it from the CDK.
