### ISSUE TITLE
Add feature: new component(DataTable)

### ISSUE THREAD

**Issue by sky10p** [angular/material2#1462]
#### Bug, feature request, or proposal:
Feature: DataTable

#### What is the expected behavior?
Data tables display sets of raw data. They usually appear in desktop enterprise products.
https://material.google.com/components/data-tables.html

#### What is the current behavior?
Nothing.

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/581

You can see status of various components here https://github.com/angular/material2/blob/master/README.md#feature-status

**Comment by jelbourn** [comment]
See #581

**Comment by kkarandikar0807** [comment]
Hi. I was just going through the specs and I just want to add one thing. When you have inline editing, and inline dropdown selection, is it possible to have a inline autocomplete instead of a regular dropdown. So, in that case, even if the amout of data is huge, we can easily filter instead of having a big dropdown list
