### ISSUE TITLE
Table sorting, excluding elements

### ISSUE THREAD

**Issue by webplease** [angular/material2#14664]
Hi to all,

using MatSort is it possible to exclude from the ordering of the elements leaving them fixed as last of the table?

Thank you in advance

**Comment by lroedal** [comment]
I don't think it is possible to 'exclude' elements, but you can choose to return a different value than the actual one, using a custom sort function. I forked the stackblitz with sorting etc from Material - this will now keep the rows with color black on top at all times. For this dataset I had to use matSortDisableClear, because it default to the leftmost numbers if no sorting was chosen. It leaves the rows with black color on top now, but if you want them to be last you can 'reverse' what is returned.

https://stackblitz.com/edit/custom-sort

**Comment by webplease** [comment]
Perfect lroedal, it was exactly what I needed! Thanks very much!

In my case the field is numeric (as ad ID), so to make sure that these records are last, I have to put an enormously high number, like "1000000000". Do you know a solution for this problem too?

Thanks!

**Comment by webplease** [comment]
return Number.MAX_SAFE_INTEGER could be a valid solution? :)

**Comment by vivian-hu** [comment]
Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are stack overflow, gitter, mailing list, etc.

(this is a canned response)
