### ISSUE TITLE
How to display table headers in a column Angular material table

### ISSUE THREAD

**Issue by jd17364** [angular/material2#14914]
Creating a table for a single user and I want to use Angular Material (mat-table).

Here is what I'm looking for in my table:

Username    | becky123
First Name  | becky
Last Name   | stewart

Notice that the headers are in 1 column instead of your typical row like I've seen in most of the Material table documentation (https://material.angular.io/components/table/overview).

Also the User object is basically the data source in the ts file (it's not an array since it's just a singular user.) Could someone please help me achieve this?

I've seen this How to display the table headers in a row, in angular material table? but this would be assuming that I have multiple users when I only have one stored in an object.

I really appreciate it.

**Comment by andrewseguin** [comment]
This is something we do not recommend since it would not work well for accessibility purposes. The table is specifically meant for data rendering and the column headers play a critical role in that.

If you do need to pursue this, I think your question will be best answered on StackOverflow or Gitter where our community can provide tips. We try to keep our issues for feature requests and bugs only.
