### ISSUE TITLE
The ripple causes strange margin - reproduced

### ISSUE THREAD

**Issue by kfrankiewicz** [angular/material2#14981]
Related issues:
https://github.com/angular/material2/issues/10898
https://github.com/angular/material2/issues/12210

The ripple creates strange margins, when _position: relative_ is added to the children divs in the global CSS. The recent angular versions. In my case I used _mat-tab-group_ with the ripple.

It causes this problem:

https://stackblitz.com/edit/angular-m5y3yx?file=src%2Fapp%2Fapp.component.html

It seems the _position: absolute_ (or whatever it is) from the ripple is overwritten by the global _position_.

The ripple works well when I add this globally:
```
div.mat-ripple-element {
  position: absolute !important;
}
```

**Comment by devversion** [comment]
Hi @kfrankiewicz, thanks for your issue!

The `matRipple` is internally used by a lot of Angular Material components, but I realize there are a few use-cases where the `matRipple` does not work as expected. Though the ripple is more intended to be used in advanced cases, where other parts of the surroundings are properly overwritten so that the ripple can behave properly.

Most of the time ripples can be launched safely by creating an absolute overlapping transparent container that acts as the ripple container and does not affect the parent elements. this can be seen in the `lib/button` implementation for reference.

Also, I commented on your proposal #14982. Let's track this issue for compatibility with the `<mat-card>` in the existing issue #10898. Thanks!

We can also have an issue for the tab-group compatibility, but we need to figure out if we actually want to guarantee that every Material component is working fine with additional _custom_ ripples. Developers should be _always_ able to properly use the `matRipple´ directive as long as the surrounded elements are properly handled.
