### ISSUE TITLE
[MatTable], [MatSort] Sorting stops work if table has *ngIf attribute

### ISSUE THREAD

**Issue by vadjs** [angular/material2#15008]
#### What is the expected behavior?
Sorting should work correct.

#### What is the current behavior?
```
<table *ngIf='true' mat-table [dataSource]="dataSource" matSort>
```
`*ngIf` makes sorting not work.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-sn7pfz?file=app/table-sorting-example.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular = 7.2.2
Material = 7.3.0
OS = ALL
TypeScript = ALL

**Comment by andrewseguin** [comment]
The `ViewChild` for `MatSort` is undefined at `ngOnInit` since the view has not yet had a chance to evaluate if the table will be displayed. To resolve this, set the `MatSort` on your data source after view has initialized by using the `ngAfterViewInit` hook.

https://stackblitz.com/edit/angular-sn7pfz-c8f9xc?file=app/table-sorting-example.ts

**Comment by andrebienemann** [comment]
I also have this issue when using *ngIf. Placing the code inside ngAfterViewInit couldn't really help to solve the problem.

**Comment by babzooka** [comment]
I fixed it by replacing 
`@ViewChild(MatSort,{static:true}) paginator: MatSort; `
with :
```
 @ViewChild(MatSort, {static: false}) set content(sort: MatSort) {
    this.dataSource.sort = sort;
  }
```
and on my NgOnInit :

```
   this.userDataService.getUserData().subscribe(
      data => {
        this.dataSource = new MatTableDataSource<UserData>(data);
      },
      error => {
        console.log(error)
      }
      
    )

```
