### ISSUE TITLE
[DragDrop] drag items indexes not being updated

### ISSUE THREAD

**Issue by LiadIdan** [angular/material2#15089]
#### What is the current behavior?
I'm using the dragDrop service to create a draggable list from content children, but the previous and current indexes not being updated after updating the list.

#### What is the expected behavior?
The indexes should be updated after updating the list.

#### What are the steps to reproduce?
https://stackblitz.com/edit/cdk-drag-drop-index-bug-vaqfmc

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular - 7.2.3
Material - 7.3.1

**Comment by LiadIdan** [comment]
I found that the cause of the issue is that `DropListRef._draggables` not being updated after updating the `ContentChildren` array. As a workaround, for now, I'm calling the `moveItemInArray` function with `DropListRef._draggables` as the first argument.
https://stackblitz.com/edit/cdk-drag-drop-index-bug-q1ys6n

**Comment by crisbeto** [comment]
It's because you're passing in an array to `withItems` which, unlike a `QueryList`, won't update once you drop the item. You should be able to get it working by passing in the shuffled array back to `withItems` when it's dropped. 

That being said, a better approach would be if the drop list adapted when the array is mutated. Currently that won't happen since we clone the array inside `withItems`, but looking through the code, I can't see a good reason to continue doing so.
