### ISSUE TITLE
md-spinner has very high CPU utilization

### ISSUE THREAD

**Issue by shanemgrey** [angular/material2#1511]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?

The spinner should not elevate CPU usage so much
#### What is the current behavior?

One spinner produces about 27% CPU utilization on Google Chrome Helper or 35% in Firefox.  Add more spinners and each adds 7 to 10%.
#### What are the steps to reproduce?

Sample code from the sample app can be used.
Can be see in chrome on the demo app https://material2-app.firebaseapp.com/ 

Remove this code and CPU use is is normal. 
`<md-spinner class="app-spinner"></md-spinner>`

Add it back and CPU spikes.
#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.0.2
AngularMaterial2 2.0.0-alpha.9-3
All browsers
#### Anything else?

Looking at the DOM in chrome while the spinner is active, the calculations behind it seem to be going at full speed, and to a high precision.   Probably just need to delay the recalculations.

**Comment by fxck** [comment]
Can confirm, it eats buttload of CPU for me as well.

**Comment by jelbourn** [comment]
@josephperrott I'm starting to think we should go back to doing the svg animation by default and then do a off-spec animation for IE11.

**Comment by crisbeto** [comment]
Instead of doing an off-spec animation, why not use the JS-based approach as a fallback @jelbourn? It shouldn't be a big issue, apart from doing the feature detection properly.  I'm not sure whether you can detect whether an element is actually animating, but you could sniff some of the IE-specific global variables.

Also note that Edge doesn't support transitions on SVG either.

**Comment by jelbourn** [comment]
Closing this form work on #1635
