### ISSUE TITLE
MatProgressBar determinate progress choppy when value updated quickly

### ISSUE THREAD

**Issue by acohenOT** [angular/material2#15138]
#### What is the expected behavior?
Increasing the value of the determinate progress bar should smoothly fill in the progress of the bar.

#### What is the current behavior?
When the value changes quickly (about once every 200 ms), the progress bar becomes choppy and appears to even slightly regress.

#### What are the steps to reproduce?
Using the determinate progress bar, change the value quickly, at about once every 200ms. Example stackblitz: https://stackblitz.com/edit/angular-eq4b5m

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/core": "7.2.4",
"@angular/material": "7.3.1",
"typescript": "~3.1.1"
Chrome 72

**Comment by crisbeto** [comment]
It's because our animation is 250ms, whereas the data updates every 200ms so it doesn't have time to finish. Since it's a CSS `transition`, we can't do much about it. You can adjust the `transition-duration` on `.mat-progress-bar .mat-progress-bar-fill` to something that makes sense for your use case.
