### ISSUE TITLE
CDK Drag and Drop reordering lists preview element is blank when list item contains canvas element

### ISSUE THREAD

**Issue by LE88I5** [angular/material2#15201]
CDK Drag and Drop reordering lists preview element is blank when list item contains canvas element.

The problem is that Node.CloneNode function doesn't clone what canvas contains, and I don't have a chance to intercept and fix the problem, should I?

```js
  cdkDragStarted($event) {
    console.log($event);
    let source = $event.source.element.nativeElement;
    let canvas = source.querySelector('canvas');
    let node = source.cloneNode(true);
    node.querySelector('canvas').getContext('2d').drawImage(canvas, 0 , 0);
    document.getElementById('copy').append(node); // I can see the content, but I can't find a way to put it in the preview element.
  }
```

**Comment by crisbeto** [comment]
As you mentioned, it's because `cloneNode` won't clone the content that's on the canvas. Handling this within the CDK will be impractical, however you can work around it for your case by providing a custom preview element. [Here's an example from the docs](https://material.angular.io/cdk/drag-drop/overview#customizing-the-drag-preview).
