### ISSUE TITLE
MatTable / CdkTable use async pipe in mat-cell / cdk-cell

### ISSUE THREAD

**Issue by quen2404** [angular/material2#15329]
#### What is the expected behavior?

I need to display an information from an observable in a mat-cell, so i use the `async` pipe. But data are never rendered.

#### What is the current behavior?

The data are never rendered, and it seems that observable is recall after each end of subscription (see console in example).

#### What are the steps to reproduce?

Here is an example: https://stackblitz.com/edit/angular-material2-issue-async-mat-table

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

angular: `7.2.6`
material: `7.3.3`
OS: linux mint
typescript: `3.1.6`
browsers: `chrome`

#### Is there anything else we should know?

N/A

**Comment by Suresh918** [comment]
The issue is with the delay in the observable. If we remove delay it will work properly. Find the edited stackblitz : [](https://stackblitz.com/edit/angular-material2-issue-async-mat-table-djsj3f)

**Comment by andrewseguin** [comment]
It seems that the issue is that whenever the stream emits, the async pipe will trigger change detection, which causes the function to be called again, creating a loop of function -> emit -> CD -> function -> ...

If you cache your observables to avoid creating a new one for each function call, then the issue is resolved

https://stackblitz.com/edit/angular-material2-issue-async-mat-table-7xr8m5?file=app/app.component.ts
