### ISSUE TITLE
mat-sort sorting lower to upper alphabetical order issue.

### ISSUE THREAD

**Issue by amanpunj17** [angular/material2#15337]
#### What is the expected behaviour?
 sort would work like this:
a
ae
A
Ae
b
be
B
Be

#### What is the current behaviour?
A
B
C
a
b
c

#### What are the steps to reproduce?

Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
use
https://stackblitz.com/angular/dmykovoxxbv?file=app%2Ftable-sorting-example.ts
and change some of the names initial letter to lowercase

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular: 6.1.0
Material: 5.0.1
Browser: Chrome
TYpescript: 2.6.2

**Comment by Sriharish** [comment]
@amanpunj17 this is expected behavior since capital letters have lower ASCII values than lower case. Check out [Austin Mueller's tutorial](https://medium.com/@AustinRMueller/dynamic-tables-and-sorting-with-angular-material-7dea862cc93c) on dynamically sorting for different headers with a custom sort (or "compare") function.

**Comment by crisbeto** [comment]
This is the default sorting behavior. If it doesn't fit your use case, you can provide your own data source with custom sorting logic.
