### ISSUE TITLE
7.3.4 is not a patch

### ISSUE THREAD

**Issue by rcketscientist** [angular/material2#15462]
https://github.com/angular/material2/pull/15134#issuecomment-462063072

The submitter even noted the breaking nature of the PR, but you pushed it into a patch anyway.  Epic!

**Comment by biltongza** [comment]
I left this on the commit that changed this, but I'm going to add it here as well for visibility:

This is still a breaking change for us since FormControlLike is not exported. We depended on this being AbstractControl in one of our methods to mark all child controls as touched, and now the only option we really have is to cast the FormControlLike to AbstractControl. Is that the recommended option?
