### ISSUE TITLE
compareWith does not work with mat-selection-list

### ISSUE THREAD

**Issue by likwidgames** [angular/material2#15495]
#### Bug, feature request, or proposal:
[compareWith] is ignored when used on a mat-selection-list component.

#### What is the expected behavior?
It should run the selected compare function

#### What is the current behavior?
Function is completely ignored. Putting a function name that does not exist does not even return an error message.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-ddft7j

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on the latest Material version at the time of this writing:
"@angular/material": "^7.3.3"
See StackBlitz for other packages

**Comment by crisbeto** [comment]
@likwidgames your example is using a `mat-select`, whereas your issue is referring to `mat-selection-list`.

**Comment by likwidgames** [comment]
My bad. Had the wrong stackblitz URL there. I have updated the OP with the correct link.

**Comment by likwidgames** [comment]
> @likwidgames your example is using a `mat-select`, whereas your issue is referring to `mat-selection-list`.

My bad. Had the wrong stackblitz URL there. I have updated the OP with the correct link.

**Comment by crisbeto** [comment]
There are two issues with your demo:

1. You aren't passing in the `formControlObj` to the selection list which means that it can't get the selected value.
2. You aren't assigning a value to each of the selection list items.

[Here's a working example.](https://stackblitz.com/edit/angular-hnycl2?file=src/app/app.component.html) Note that this throws a "changed after checked" error which will be fixed by https://github.com/angular/material2/pull/15388.

**Comment by mtraynham** [comment]
@crisbeto actually I think there is a different bug here.  I've changed the stackblitz.  It seems deferring the `mat-list-options` to a later update never re-syncs the model.
