### ISSUE TITLE
cdkDrag does nothing when inside an *ngFor looping through a returned 2 dimensional array

### ISSUE THREAD

**Issue by wshaver** [angular/material2#15807]
#### What is the expected behavior?
cdkDrag works from inside an ngFor looping through an array with a nested array.

#### What is the current behavior?
Nothing happens. cdkDrag does not move or drag.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-a4ftm7-oectv4?file=app%2Fcdk-drag-drop-connected-sorting-example.html

```
<div *ngFor="let i of getNestedArray()">
  complete failure :(
  <div cdkDrag>1</div>
  <div cdkDrag>2</div>
  <div cdkDrag>3</div>
</div>
```
```
 getNestedArray(){
   return [[]];
 }
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
chrome browser, angular 7.1.0 and 7.2.0, material 7.1.0 and 7.3.7 

#### Is there anything else we should know?
Happy to explain more if this isn't clear. Had me stumped for hours. :(

**Comment by Airblader** [comment]
This is because calling `getNestedArray`, a function, creates the nested array from scratch on every change detection cycle. While this is also true for `getSimpleArray`, the difference is that the inner array is also recreated everytime, meaning it's a new reference.

This is a simple case of "do not call functions from templates". If you, for example, make the component use OnPush it works fine.

**Comment by crisbeto** [comment]
@Airblader's explanation is correct. Closing since this works as expected.

**Comment by wshaver** [comment]
Thanks for the detailed explanation, makes sense.
