### ISSUE TITLE
dialog imports and exports dialogconfig

### ISSUE THREAD

**Issue by CoderCat84** [angular/material2#1905]
I looks like dialog.ts both imports and then reexports MdDialogConfig and MdDialogRef.  For me this is causing an error when I try to build with webpack 2 due to it trying to re-add the module. The error is:

Uncaught TypeError: Cannot redefine property: MdDialogRef

 I'm pretty new to modules in typescript but it seems weird to me that a component would import and then export something

**Comment by jelbourn** [comment]
This is known as a "re-export" and is pretty common. AFAIK it hasn't been a problem with any Webpack and this in the past. All of our angular-cli based projects, such as [this sample](https://github.com/jelbourn/material2-app) use webpack without this problem. 

Going to close this for now as I suspect the issue lies in your environment.

**Comment by CoderCat84** [comment]
actually looks like it might be related to this:

https://github.com/webpack/webpack/issues/2850

it wouldn't happen in the example you linked because you are importing individual components i.e. import { MdSomething } from "angular/material" whereas I import the entire thing i.e. import "@angular/material"  which causes the index.d.ts to be used in the dialog folder (I do this because I'm building a webpack dll and want the entire thing recompiled instead of adding each piece individually"
