### ISSUE TITLE
tooltip: Should hide previously opened tip before showing a new one

### ISSUE THREAD

**Issue by quanterion** [angular/material2#1960]
Next opened tooltips do not close the old ones. So If move mouse along the tool bar with multiple actions I get a disgusting picture with multiple overlapping tooltips
![tooltip](https://cloud.githubusercontent.com/assets/6149211/20522272/74acca42-b0c0-11e6-9b14-2e802192dcf2.png)

Environment:
Material: alpha-10
Angular: 2.2.1
Browser: Chrome latest

**Comment by fxck** [comment]
There are currently two problems with tooltips, one is that is doesn't hide immediately and second that when any of the parent components have change detections strategy set to `OnPush` tooltip doesn't hide at all. Your problem will disappear when the first one is fixed(I think the fix is already in master, just not released).

**Comment by andrewseguin** [comment]
This is now fixed in master because the delay only shows on mobile now, triggered by a longpress
