### ISSUE TITLE
please add md-divider to md-menu

### ISSUE THREAD

**Issue by riankol** [angular/material2#2017]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
I would like to use a md-menu-divider, or make the existing md-divider work within md-menu. This is not in the design doc, but it will be very handy.

#### What is the current behavior?
There isn't one available.

#### What are the steps to reproduce?
I would like one just like in md-list, the md-divider

#### What is the use-case or motivation for changing an existing behavior?
At the moment I use an `<hr/>` element to have a divider in the menu, but the original styling of the `<hr/>` element isn't very nice, so I have to add styling to the element. A md-menu-divider with the same styling as the md-divider will be a prefered.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular Material 2.0.0-alpha-10

**Comment by jelbourn** [comment]
@kara is this something you wanted to add?

**Comment by bradrich** [comment]
@riankol In the meantime, you could use a standard HTML hr element.

**Comment by andreasrueedlinger** [comment]
What is the intended use of md-divider? Just for md-list? Because it might as well be useful in md-card?
With the current version you can use md-divider also outside of md-list but it is only shown if list.css is loaded.
Is it possible to move the divider css to a file which is loaded in all use cases?
