### ISSUE TITLE
Material2 should allow for the use of the new inheritance feature of Angular 2.3.0

### ISSUE THREAD

**Issue by alexw10** [angular/material2#2194]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
Talked with @robwormald about this in Angular2 gitter for a bit today.
The new Inheritance feature put into Angular2 (https://github.com/angular/angular/commit/f5c8e09) I think should be utilized by Material2
Allowing for extending of components with Material2's events being inherited to a extended component.

#### What is the current behavior?
Current behavior is host { } behind used but @HostListeners should be used in their place.
Possibly @HostBinding (not quite sure on this one if you have insight would be great) as well.

#### What is the use-case or motivation for changing an existing behavior?
Updating the events that are being used in the host: {} property to HostBindings allows extends to take in the default behavior of whatever Material2 implements which allows for new functionality to automatically be propagated down to extended classes.

#### Which versions of Angular, Material, OS, browsers are affected?
Need to be on Angular 2.3 or greater for the inheritance functionality I describe above to work.

#### Is there anything else we should know?
**I am willing to go through the repo and update the components that need this update if you guys think what I am saying is viable.
Wanted to make sure to bring it up before I do that to make sure I don't do it for no reason/maybe I am thinking incorrectly.**

**Comment by alexw10** [comment]
Any thoughts on this anyone?

**Comment by jelbourn** [comment]
Our preference for `host` stems from avoiding `HostListener` due to issues with Angular Universal; applying a decorator to a function causes the type to be preserved. When the type of an argument is something like `KeyboardEvent` or `MouseEvent`, that type will be preserved in the compiled JS, which will in turn make Angular Universal unhappy because those symbols don't exist when prerendering. 

TypeScript 2.2 introduces better support for mixins and we're going to be exploring that as an avenue of making component behaviors more reusable (vs. extending entire components). This will, however, lead to more use of the directive metadata for things like `inputs` and `outputs`.
