### ISSUE TITLE
Remove @types/protractor@4.0.0 from devDependencies

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#2384]
Protractor now comes with internal types

When `npm install` or `yarn` this warning shows:

```
warning @types/protractor@4.0.0: This is a stub types definition for Protractor (https://github.com/angular/protractor). Protractor provides its own type definitions, so you don't need @types/protractor installed!
```

**Comment by DevVersion** [comment]
We had some issues with that, because accidentally the `chord` declaration (which is used by our e2e tests) has been removed in the typings. See https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4cf3256fe813b0121cc69f8b794ee6bb68905971

Waiting for a new protractor version, which gives us access to https://github.com/DefinitelyTyped/DefinitelyTyped/commit/123690bb2e0f9dac2371084369a8ecf8976cbb34
