### ISSUE TITLE
Md-Input Readme

### ISSUE THREAD

**Issue by bkarv** [angular/material2#2529]
#### Bug, feature request, or proposal:
 Implementing md-input by following readme: 
```
<md-input-container>
  <input mdInput>
</md-input-container>
```
I get the following error:
"md-input-container must contain an md-input directive. Did you forget to add md-input to the native input or textarea element?"

This is fixed by replacing mdInput with md-input. Is there a typo  in the readme????

Using  Angular Material 2.0.0-beta.1

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by ChuckkNorris** [comment]
Noticed this issue as well.

It looks like the selector was [updated 3 days](https://github.com/angular/material2/commit/93b0bc9da74723ba65fb6250df432dad39f1a5a6) ago to match the directive formatting convention (mdInput instead of md-input). Until this change is pushed to NPM, just revert to the old selector.

```
<md-input-container>
  <input md-input placeholder="Name">
</md-input-container>
```

**Comment by EladBezalel** [comment]
@arciisine, @ChuckkNorris thanks for the help!

**Comment by leocaseiro** [comment]
Thanks @ChuckkNorris,

I lost a few hours on that...

**Comment by magemello** [comment]
So I suppose the https://material.angular.io/ documentation doesn't get updated in real time, if not what is the best place to get latest doc?
