### ISSUE TITLE
npm registry is out of date

### ISSUE THREAD

**Issue by Nodarii** [angular/material2#256]
* **Do you want to request a *feature* or report a *bug*?**
Configuration issue 

* **What is the current behavior?**
Some components in the npm registry are missing and some of them are out of date. 
The last publish to npms was 3 weeks ago

* **What is the expected behavior?**
All components are published and up to date to the git.

* **What is the motivation / use case for changing the behavior?**
failure to use some components

**Comment by dapids** [comment]
+1

**Comment by fxck** [comment]
I suppose it's waiting for the alpha.2 release. 

But I do agree that the releases should be more rapid. Why not release with every single completed component(there were at least three since the last beta). Especially when it's something as important as inputs.

But at the end of the day, that's not really an issue, I don't mind waiting that much, what I find saddening is lack of communication towards community. What's the state of the project? How accurate are those milestones? Are there people in google fully committed to this, or is it just a little side project while the focus is on more important work(like angular1 material)? Are there no rapid releases because of blockers in angular2, or because of the ng2 animation that is in the works? Because the testing infrastructure is not yet set up properly?

> These components will serve as an example of how to write Angular code following best practices.

This is probably the most important thing for me, and I'm looking forward to seeing how you handle overlays, dialogs, selects.. but at this rate, I feel like I'm not getting those anytime soon.

**Comment by iloveyo123u1** [comment]
+1

**Comment by jelbourn** [comment]
alpha.2 should be coming today; the team got a little behind due to vacations + sickness.

**Comment by jelbourn** [comment]
Running into some issues getting the source maps correct for releases (#212). Publishing alpha.2 is slipping to tomorrow. 

Also, @fxck, there are several of us on the Angular team who work on Angular Material full time, plus some 20% contributors across Google and community contributors. Our milestones should be generally accurate +/- a few days (you know how engineers are at estimating). The milestones themselves should give you a general idea of what we're _currently_ working on, and the open issues are what's coming up.  While we're in the early part of our alpha, the releases aren't going to be super rapid, as we don't think anyone should be using the components for anything more than a toy/experiment during this phase. 

We should probably put some of that into a FAQ.

**Comment by Nodarii** [comment]
@jelbourn Thank you so much for such expanded version!

I think it's right moment to close the issue. Closing...

**Comment by fxck** [comment]
@jelbourn 

> While we're in the early part of our alpha, the releases aren't going to be super rapid, as we don't think anyone should be using the components for anything more than a toy/experiment during this phase (early alpha).

I know, right, alpha duh. But people will use it. There simple are no high quality components around yet, unlike when material1 came out for angular1. So alpha or not, this is still the best option. Not to mention that it will be included in ToH(https://github.com/angular/material2/issues/199) as well as @gdi2290's starter(https://github.com/AngularClass/angular2-webpack-starter/issues/443) and other starter kits. So yeah, it's gonna be used by quite a few people even in early alphas. Just saying though, thanks for the answer.

**Comment by Nodarii** [comment]
Agree with, @fxck! Would be great to have every successful build published to npm with some sub-version.
