### ISSUE TITLE
Fastclick

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#261]
Some devices still have a 300ms delay between a touch event and a click event being fired, so we'll need  a fastclick implementation to prevent this.

**Comment by tgrosh** [comment]
Any progress on this implementation? I am finding an issue being able to click (for example) checkboxes when I include the fastclick.js library in my ng2 / material project.

**Comment by mgol** [comment]
Do you mean just the Android Browser or something else? iOS 9.3+, Chrome for Android & recent Windows Phone don't need it. If any FastClick solution gets developed it's important to be able to opt out of it if none of the supported platforms in a project need it.

**Comment by wbhob** [comment]
See Ionic's `tappable` directive

**Comment by mackelito** [comment]
I guess this will be a major deal for PWA´s.. I was kind of surprised to see a delay when running chrome on iOS 10.3.1.

**Comment by mgol** [comment]
@mackelito Some basic conditions need to be met to disable the delay; they're mostly common between various mobile operating systems. You either need specify "width=device-width" in a viewport or "touch-action: manipulation" in CSS.

**Comment by mackelito** [comment]
@mgol I currently have this in my index.html `<meta name="viewport" content="width=device-width, initial-scale=1">`
Is the initial-scale messing things up?

**Comment by mgol** [comment]
It shouldn't IMO (unless you zoom in) but it's probably better to be explicit and specify:
```css
:root {
    touch-action: manipulation;
}
```
instead of relying on heuristics that may not always work. This is described in the document linked to in the original post.

**Comment by mackelito** [comment]
Just tried it an I´m still seeing a lag when clicking things? :(

**Comment by geelus** [comment]
Hey guys, I'm having the same exact problem when used the "Add to homescreen" feature in Safari. (fullscreen webapp using <meta name="apple-mobile-web-app-capable" content="yes">)
Using chrome/safari produces no lag for me as well.

This is really important and because of this issue, my "Cordova" app is running really sluggish and I can say it's not because material 2 is slow but only because of this delay.

**Comment by jelbourn** [comment]
Closing this since the whole thing isn't really necessary w/ modern mobile browsers.
https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away

**Comment by geelus** [comment]
Hi Jelbourn
This should not be closed because it's still a major issue on iPad and iPhone.
Here is to see the issue in practice:

1- Navigate to a page with <meta name="viewport" content="width=device-width"> which is designed for mobile on any iPad or iPhone (using Safari)
2- Create an icon on screen using the "Add to home screen" option.
3- Close Safari and run the app using the icon on your screen.

You can see that this issue still exists and unless you would like to ignore this issue, IMO this should not be closed.

Thanks, 
Morteza
