### ISSUE TITLE
MdMenu : keep menu open on item click

### ISSUE THREAD

**Issue by Robouste** [angular/material2#2612]
#### Bug, feature request, or proposal:
feature request

#### What is the expected behavior?
It would be great to have an option to keep the menu open when we click a menu item 

#### What is the current behavior?
On item menu click, the menu closes

#### What are the steps to reproduce?
[Plunkr](http://plnkr.co/edit/NK36sG)

#### What is the use-case or motivation for changing an existing behavior?
Putting checkboxes in the menu for example

#### Which versions of Angular, Material, OS, browsers are affected?
All

**Comment by nayfin** [comment]
I would like to utilize this feature to allow menu to take text inputs. Perhaps some new directives:

`opens-on="focus | hover | click"` 
`closes-on="defocus | hover-off | click-off | select-item"`

This would let us get very specific with the menu behavior. Would need to be able to take one or all values.

**Comment by nayfin** [comment]
I just found this in the ReadMe:

`Not yet implemented
- ‘prevent-close' option, to turn off automatic menu close when clicking outside the menu ` 

Which isn't quite what we are looking for, but it's close and a good indication that similar features are being considered. 

From what I've read of the source we just need to prevent click events on `md-menu-items` from propagating up to the menu. If anyone has some pro tips before I get started I'm happy to hear them. I'll try to put together a splunkr over the weekend and submit a PR once it's working.

**Comment by nayfin** [comment]
@Robouste [Here's an ugly workaround](http://plnkr.co/edit/6qzKZX?p=preview). I'll turn it into a directive soon and update. For some reason using this with `md-menu-item` keeps menu open but doesn't allow inputs or checkboxes to register clicks or become focused. Take out the `md-menu-item` directive and everything works fine, just doesn't look quite as nice.

**Comment by Robouste** [comment]
@nayfin Thank you, it seems to do the trick. But I choose the bootstrap dropdown, more customizable (for now !)

**Comment by randallmeeker** [comment]
I have an input in my menu and this worked find
`<input class="input-log" (click)="$event.stopPropagation()" type="text" />`

**Comment by ccadieux** [comment]
Being able to turn this off would be great. We implemented a menu very similar to the google inbox account menu and ran into this issue. We had to add a click handler and stopPropagation on the entire menu.

**Comment by jelbourn** [comment]
Chatted w/ @kara about this and we decided that we don't want to add this as a feature to md-menu. This is largely because turning it on would be detrimental to the a11y experience (see https://www.w3.org/TR/wai-aria-practices-1.1/#menu), and we want to generally avoid adding APIs that go counter to a11y best practices.

**Comment by hghammoud** [comment]
For those who are waiting for this to be merged, this is how i did it to implement a multi-select columns in a table (i didnt want the input part of select).  

I basically removed the md-menu-item directive and used the class mat-menu-item for the styling.


    <md-menu #appMenu="mdMenu">
        <div *ngFor="let column of columns" class="mat-menu-item" style="overflow: visible;">
            <md-checkbox [(ngModel)]="column.show" (click)="$event.stopPropagation()" >{{column.name}}</md-checkbox>
        </div>
    </md-menu>
    <button md-button color="primary" [mdMenuTriggerFor]="appMenu">Select columns</button>

Hope this helps.

**Comment by mikila85** [comment]
@jelbourn 
Dont know what you guys talking about..
[a11yproject.com](https://a11yproject.com/patterns) -> Dropdown
Sends you here:
[Codepen](https://codepen.io/svinkle/pen/aEVwWd)

Clearly shows when clicking menu it doesnt close.

**Comment by sarbull** [comment]
```ts
import {Directive, HostListener} from '@angular/core';

@Directive({
    selector: '[click-stop-propagation]'
})
export class ClickStopPropagation {
    @HostListener('click', ['$event'])
    public onClick(event: any): void {
        event.stopPropagation();
    }
}
```

```html
<div click-stop-propagation>Stop Propagation</div>
```

source: https://stackoverflow.com/a/41001184/1527666

**Comment by jpike88** [comment]
> turning it on would be detrimental to the a11y experience

The irony in this stumps me. So by catering to a tiny subset of users that most devs here aren't even targeting with their products (which by the way, MAKES NO SENSE in this particular context), we have to come up with weird workarounds to unlock proper functionality....

The only reason I'm even posting in this issue is that the angular material library has failed to provide some sort of popover component that animates from the button that was clicked, or instead opens as a full-screen overlay on narrow screens. Such a fundamental component that's been around on mobile and web forever. 

https://developer.apple.com/design/human-interface-guidelines/ios/views/popovers/

Apple could teach you guys a lesson about usability and listening to the needs of developers
