### ISSUE TITLE
checkbox animating initial value

### ISSUE THREAD

**Issue by fxck** [angular/material2#2783]
I think it should only animate when user toggles the values.. it's especially noticable when you have checkbox inside some ngIf condition(like when it's inside tabs)

http://plnkr.co/edit/8AnsenWT2PORBaC162yu?p=preview

**Comment by DevVersion** [comment]
I looked into this - We could use the `_onInteractionEvent` to update the transition classes only on user interaction.

An interesting case is the `indeterminate` state, because I'm not really sure how we should treat that (indeterminate is never per interaction -so transition would be obsolete). 

@jelbourn Any thoughts?

**Comment by jelbourn** [comment]
@matsko is there a standard way to do this?
