### ISSUE TITLE
Bug: Md-menu overlapTrigger not working

### ISSUE THREAD

**Issue by bsteffl** [angular/material2#2824]
#### What is the expected behavior?
To set the value of `overlapTrigger	="false"` to allow menu to appear below trigger.

#### What is the current behavior?
Trigger position does not seem to be working to position menu below trigger button. Doesn't work on default nor explicitly applied.

#### What are the steps to reproduce?
```
<button md-button [mdMenuTriggerFor]="menu">
          Button Text
</button>

<md-menu #menu="mdMenu" overlapTrigger="false">
          <button md-menu-item> Refresh </button>
          <button md-menu-item> Settings </button>
          <button md-menu-item> Help </button>
          <button md-menu-item disabled> Sign Out </button>
</md-menu>
```
![image](https://cloud.githubusercontent.com/assets/10760551/22348911/05c33472-e3d3-11e6-84ff-6f132963fb80.png)

#### What is the use-case or motivation for changing an existing behavior?
Allow for positioning of menu below button trigger.

#### Which versions of Angular, Material, OS, browsers are affected?
Version 2.0.0-beta.1

#### Is there anything else we should know?
Documentation is misleading under [Customizing menu position](https://github.com/angular/material2/tree/master/src/lib/menu#customizing-menu-position) it describes the default behavior to be "below its trigger". Then later on in [Menu attributes](https://github.com/angular/material2/tree/master/src/lib/menu#menu-attributes) the default is set to true as in overlapTrigger is true.

Related to [Issue2611](https://github.com/angular/material2/issues/2611)

**Comment by kara** [comment]
@bsteffl  The `overlapTrigger` option was just added to master a few days ago, so it's not yet available in a public release.  From your version listed above, it seems like you are using our last release from December.  As soon as our next version comes it, you should be able to use it.

You can play with the `overlapTrigger` option in our plunker template now though. See example usage here: 
http://plnkr.co/edit/O43ebtrFNEGOmvpweAUD?p=preview

Regarding documentation, I'd suggest using our documentation site [here](https://material.angular.io/components/component/menu) rather than the READMEs. It will give you the info on whatever is in the last release. The READMEs will be updated whenever new functionality is added to master, so they may have features that aren't in your version.

**Comment by bsteffl** [comment]
@kara Thank you!

**Comment by HoumanKml** [comment]
I have the same issue, does not work on beta 6 either.

**Comment by willshowell** [comment]
@HoumanKml can you reproduce it in a plunker?

**Comment by HoumanKml** [comment]
@willshowell Sure:

https://plnkr.co/edit/IxUpyfcVlVHu7FdfAoT1?p=preview

It is the 'basic menu' example from `https://material.angular.io/components/component/menu`, where I have added `overlapTrigger="false"` to the `md-menu` tag.

**Comment by willshowell** [comment]
@HoumanKml add brackets to your binding. As you have it, you are setting `overlapTrigger` to `"false"` as a string

**Comment by HoumanKml** [comment]
@willshowell  Ah, I see! Thanks, it is working! Maybe that is also why @bsteffl code was not working either?
