### ISSUE TITLE
md-input Disabled property is not working with Databinding [disabled]

### ISSUE THREAD

**Issue by bhavankris** [angular/material2#2897]
#### Bug, feature request, or proposal:
there is a bug we try to use disabled with databinding i.e [disabled] we are able to enter  able to enter the content

#### What is the expected behavior?
it should be disabled but here it looks like disabled but the issue is that we can enter the text

Sample code 
html:
<md-input-container class="example-full-width" >
      <textarea md-input placeholder="Description of Recovery" [disabled]="value" ></textarea>
      </md-input-container>

ts:
value=true;

but the issue that we are able to enter the content but input looks like disabled

**Comment by kara** [comment]
@bhavankris It seems from your code that you're using the old version of mdInput. Since we've updated it to wrap with md-input-container, the disabled property should work (see plunker example of usage here: http://plnkr.co/edit/9fWU47mDjtZBlxjpVMPE?p=preview). If you're still seeing problems with disabling in the new version of mdInput, feel free to open a new issue with a plunker demo.

**Comment by giorgosde** [comment]
Indeed that [disabled] is working with mdInput but it does so only for the initial value. It doesn't detect changes in the given attribute. So, in a case that **disabled="true"** by default, even if I set it on false inside the code, this doesn't been detected by [disabled].

`  <input mdInput [placeholder]="value"    [ngModel]="model" [disabled]="disabled" type="text">`

**Comment by rafaelzuckerberg** [comment]
I used this way 
<input matInput placeholder="Email" [ngModel]="franchise.user_email" formControlName="email" readonly>

and work perfectly
