### ISSUE TITLE
The getting started doc on the website is not up to date

### ISSUE THREAD

**Issue by avatsaev** [angular/material2#2939]
#### Bug, feature request, or proposal:

Checked the code in the repo, seems to be fine, not deployed yet?

http://i.imgur.com/GgpYgz4.png

https://material.angular.io/guide/getting-started

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

**Comment by emin93** [comment]
I don't see what the issue here is? In the documentation they start by installing the Angular CLI and creating a new project with it. If you scroll down a bit, you'll find the part where they install material:
![bildschirmfoto 2017-02-06 um 16 17 21](https://cloud.githubusercontent.com/assets/5310475/22652739/e301d6f6-ec87-11e6-9d61-fe2694e14779.png)

**Comment by avatsaev** [comment]
The doc you mentioned is not up to date, i created an ossie for that on their repo a few days ago, they updated the code but didn't deploy yet

**Comment by avatsaev** [comment]
It's @anglular/cli not angular-cli

**Comment by emin93** [comment]
Ah now i see it, thanks for clearing that up.

**Comment by avatsaev** [comment]
Yeah my faut, just realised I wasn't clear enough

**Comment by kara** [comment]
I just labelled this, then re-read and realized that it's fixed in master. This change to `@angular/cli` will be pushed out with the next public release.
