### ISSUE TITLE
Proposal: Rich text-editor

### ISSUE THREAD

**Issue by LoganDupont** [angular/material2#2949]
#### Bug, feature request, or proposal:
Do the Angular Material Team have any thoughts about creating a rich text-editor?

#### What is the expected behavior?
The user should be able to set a text in bold, italic, create a link, create a (un)ordered list, add an image,...
A good example is the [ng-wig](https://github.com/stevermeister/ngWig) in AngularJS created by @stevermeister but it need some optimizations.

#### What is the current behavior?
Not implemented yet

**Comment by msegers** [comment]
I don't expect this to get into the Material Design core. It would require so much design (as it would have to be embedded in the material design spec.).

That being said, it's probably best to focus on a third party wysiwyg like your proposition, because developing one which works well design-wise with material would totally be nice.

**Comment by frankspin89** [comment]
I don't see any reason why a rich text-editor has to be part of material design package? 

Like @msegers said, maybe it's better to focus on a third party editor. I would suggest looking at 

- http://getcontenttools.com/
- https://www.froala.com/wysiwyg-editor
- http://ckeditor.com/
- https://www.tinymce.com/

**Comment by jelbourn** [comment]
See #4444
