### ISSUE TITLE
Feature Request: Use Angular Material inside index.html <app-root> tag

### ISSUE THREAD

**Issue by nottinhill** [angular/material2#2988]
When our entire site loads, I want to display a md spinner. How can this be achieved? I tried putting this

`<md-progress-spinner mode="indeterminate"></md-progress-spinner>`

into `<app-root></app-root>` tags, but it does not display. Any other ideas?

**Comment by emoralesb05** [comment]
Thats because `angular` hasnt loaded the App `module` yet so it doesnt know what `md-progress-spinner` is at that point. 

You would need to use something thats is not `angular` if you want to show any thing before the modules are loaded.

When you build in `AoT` that loading screen is only there for a bit, so i wouldnt put too much effort on this (maybe just an img or something).

**Comment by grizzm0** [comment]
Your best shot would be a gif-spinner that's tiny in size.

**Comment by nottinhill** [comment]
Nice, thanks for test. I guess it's not possible then with material or even with a gif. Case closed.
