### ISSUE TITLE
Input placeholder bug on Microsoft Edge (and IE11)

### ISSUE THREAD

**Issue by elmeerr** [angular/material2#3077]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
md-input placeholder transition animation on focus occurring smoothly

#### What is the current behavior?
md-input placeholder animation on focus occurring in a weird way on Edge/IE11

#### What are the steps to reproduce?

Access https://material.angular.io/components/component/input on Edge or IE11
Clear the input
Leave the input
Click on the input to get focus on it
Note that the placeholder get a little bit higher when the animation ends (see on Chrome/Firefox to notice the difference) 

#### What is the use-case or motivation for changing an existing behavior?
Should work the same way that works on Chrome/Firefox

#### Which versions of Angular, Material, OS, browsers are affected?
The recent one.

#### Is there anything else we should know?
No.

Regards,

**Comment by dahaupt** [comment]
Good catch, even in Chrome it is not perfectly smooth in the end of the transition.

**Comment by kara** [comment]
@dahaupt @elmeerr Thanks for testing! The docs site runs on the version of Material from the last release. Given that this problem seems to be fixed on master, it doesn't seem like there's any further work to be done. If you can still repro from our plunker template or the demo app, please feel free to re-open.
