### ISSUE TITLE
BUG: md-input does not lift when setting form value

### ISSUE THREAD

**Issue by chriseenberg** [angular/material2#3101]
#### What is the expected behavior?
I expect the placeholder to lift above the text when there is an input, even when done programmatically.

#### What is the current behavior?
The placeholder stays down when setting value of an input field programmatically through from.controls.

#### What are the steps to reproduce?
Create a form with the form builder, then set a value like this: 
Code to reproduce:
`this.form = this.fb.group({
            'email': [null]
})`

`<md-input-container class="form-full-width">
                            <input md-input placeholder="Email address" [formControl]="form.controls['email']">
                        </md-input-container>`

`this.form.controls['email'].setValue("testingapp@testingapp.com");`

#### What is the use-case or motivation for changing an existing behavior?
I want to be able to set a value of an input field and have it displayed right when i load some data.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular cli 1.0.0-beta.25.5, material: ^2.0.0-beta.1, Angular version: ^2.3.1

#### Is there anything else we should know?
I may be doing stuff wrong, as i would expect this bug to be caught sooner? please excuse me if this bug has already been reported.

Kind regards Chris

**Comment by fxck** [comment]
using OnPush by any chance? 

https://github.com/angular/material2/issues/3005

**Comment by chriseenberg** [comment]
It does seem to be similar case, though i don't quite understand the conversation to its fullest. Is there a fix for this or do i need to wait for an update in angular material?

**Comment by kara** [comment]
If you're using 2.0.0-beta.1, you are probably seeing the setValue issue that has [since been fixed in master](https://github.com/angular/material2/pull/2455). Testing in plunker with the master build, it seems to be working now: http://plnkr.co/edit/Z3AR9NqqD5cq8ymUF2ye?p=preview. As soon as we release, you should be able to upgrade to get the fix.

The exception is with an onPush change detection strategy, for which there is already an issue.
