### ISSUE TITLE
md-input placeholder doesn't fade when loading formgroup value via promise from service

### ISSUE THREAD

**Issue by atul221282** [angular/material2#3117]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Placeholder from md-input to move up when setting formgroup from back-end api promise.

#### What is the current behavior?
md-input placeholder is still getting displayed behind the actual text and not moving up. I found the reason for this issue and it is md-empty class not getting removed from label in html produces by md-input-container directive

#### What are the steps to reproduce?
Create formgroup from FormBuilder api in angular2 set the value of formgroup from backend api or use setTimeout to mock it. Try setting the value like this as per angular docs `this.myForm.controls["user"].setValue(this.user, { onlySelf: true });`

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://stackoverflow.com/questions/42249684/md-input-placeholder-doesnt-fade-when-loading-formgroup-value-via-promise-from
Created plunker also
Plunker template: http://plnkr.co/edit/skGVKxNiDe0477OseE9D

#### Which versions of Angular, Material, OS, browsers are affected?
angular 2.4.0
angular material 2.0.0-beta.1
OS - Windows10,
Browser - Chrome, IE Edge, IE11

#### Is there anything else we should know?
If I use ngModel instead of form group it works fine but when I use simple input(not angular material), with placeholder ngModel and formgroup both work fine
![ky1bg](https://cloud.githubusercontent.com/assets/4570393/22999605/3f977b22-f42c-11e6-9404-b44a4eb05fb9.png)

**Comment by kara** [comment]
If you're using 2.0.0-beta.1, you are probably seeing the setValue issue that has [since been fixed in master](https://github.com/angular/material2/pull/2455). Testing in plunker with the master build (rather than the material bundle from NPM), it seems to be working now: http://plnkr.co/edit/Z3AR9NqqD5cq8ymUF2ye?p=preview. As soon as we release, you should be able to upgrade to get the fix.

The exception is using setValue with an onPush change detection strategy, for which [there is already an issue](#3005).

**Comment by atul221282** [comment]
yeah looks good in master thanks for the prompt reply

**Comment by teamtaheny1** [comment]
having this same issue in beta10.  was working great in beta8.

**Comment by s-f-a-g** [comment]
Same here with beta 10
