### ISSUE TITLE
bug(dialog): dialog jumping/"entering" every time input focus is changed

### ISSUE THREAD

**Issue by YeomansIII** [angular/material2#3124]
#### **Bug**
Dialog jumping/"entering" every time input focus is changed

#### What is the expected behavior?
The dialog should stay where it is and not be affected by change in input focus.

#### What is the current behavior?
On iOS (Safari and Chrome) a modal will "jump" or replay the enter animation whenever a new input is focused within the dialog. Below is a gif of the current behavior.
![jumpy dialog on ios](https://cloud.githubusercontent.com/assets/3809115/23012493/86f433a8-f3f4-11e6-8079-5bd675d9a190.gif)

#### What are the steps to reproduce?
Create a dialog with multiple input elements in it and open it on an iOS device. Change focus by tapping on the different inputs.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.7
Material 2.0.0-beta.2
iOS 10, Chrome, Safari

**Comment by crisbeto** [comment]
@YeomansIII this is a known issue of modals on touch devices in general. The browser scrolls to the focused input and tries to center it on the screen, which causes everything to shift. Depending on the device, this appears less janky (e.g. an iPhone 7 doesn't have this jump, but I can definitely see it jumping with an iPhone 6).

I'm not sure we can do too much about it since this on the OS level and there are no APIs to prevent it. At best we could disable the automatic focusing of inputs on mobile. This will avoid the keyboard popping up immediately, but won't help when shifting focus between inputs.

**Comment by jelbourn** [comment]
Closing this since I'm not sure there's anything we can do about it on our side.
