### ISSUE TITLE
How to customize sass variables in _variables.scss?

### ISSUE THREAD

**Issue by huug** [angular/material2#3152]
When you override the default value af a variable in app.scss like this:
```
$md-body-font-size-base: rem(1.1);
@import '~@angular/material/core/theming/all-theme';
```
It has no effect on the font-size like in md-card:

```
md-card-subtitle {
  @extend %md-card-section-base;
  font-size: $md-body-font-size-base;
}

md-card-content {
  @extend %md-card-section-base;
  font-size: $md-body-font-size-base;
}
```

Is not better to define a base font-size on the body and use relative font-sizing like in the old-days? (https://developer.mozilla.org/en/docs/Web/CSS/font-size)

**Comment by ciesielskico** [comment]
Shouldn't you override the default value AFTER importing material variables?

**Comment by myrddraall** [comment]
I doesn't have any effect because the variables are not marked with `!default`. this means that the vars in the _variables file overwrite your variable not the other way around. This should really be changed.

**Comment by afriedma** [comment]
any chance this can be included in the next beta?  I need to override $mat-tooltip-target-height to auto, so it can span multiple lines.

**Comment by aldo-roman** [comment]
Hi @myrddraall,

I'm currently inspecting the _variables.scss file and it do declares !default variables:

https://github.com/angular/material2/blob/master/src/lib/core/style/_variables.scss
``` scss
@import '../typography/typography';


// Typography
$mat-body-font-size-base: rem(1.4) !default;
$mat-font-family: Roboto, 'Helvetica Neue', sans-serif !default;
```

I runned into the same problem while trying to set a different `md-toolbar` height on 
https://github.com/angular/material2/blob/master/src/lib/toolbar/toolbar.scss

**Comment by loganmzz** [comment]
I have found a work around. You can override variables, then extends with placeholder selector.

Examples with buttons:
```scss
@import '~@angular/material/button/_button-base.scss';
$mat-button-padding: 4px 4px !default;
button.mat-button {
  @extend %mat-button-base;
}
```

**Comment by rotan-hanrahan** [comment]
I've observed that the Material Design components support themes where you are essentially only setting the color attributes, but have no support for adjusting things like heights, widths, font sizes and much more. It seems natural to want to control these too. However, if one naively attempts to override via Sass variables then one is in for a disappointment.

The MD components append their styles to the `<head>`, and these styles are essentially "baked in". As a trivial example, consider the MD Icon, whose source appears to be `node_modules/@angular/material/icon/icon.js` and a little over 200 lines into that file you will find this:

`styles: [".mat-icon{background-repeat:no-repeat;display:inline-block;fill:currentColor;height:24px;width:24px}"],`

In some template of your application, include a `<md-icon>` and then inspect the DOM of your running application and you will find the following has appeared in the `<head>`:

`<style>.mat-icon{background-repeat:no-repeat;display:inline-block;fill:currentColor;height:24px;width:24px}</style>`

In the MD component source files you will see icon.scss, which contains:

`$mat-icon-size: 24px !default;`

However, this is not involved in the compilation of your app. I assume it was involved in the original compilation of the MD resources. What gets incorporated into your app is what is already in the aforementioned icon.js, and no amount of experimentation with $mat-icon-size in your own Sass files will have any effect on this.

Unfortunately, even if you include some `.mat-icon { ... }` rule in your Sass file to directly adjust the .mat-icon rule, it won't work because the MD styles are appended to the children of `<head>` and they will come after your own CSS rules and therefore have higher precedence.

You have limited options to overcome this. You could use "!important" (which is a sledgehammer best avoided). You could find a way to dynamically move your own `<style>` or `<link>` in the head down to the bottom so that it has precedence over the MD injected styles, and you need to make sure you do this after the MD injections have taken place. You could wait weeks or months until MD has theming ability beyond just the palette.

As a temporary hack during HMR I have configured the sass-loader in my webpack config as `style-loader?insertInto=#injectedStyle` and I have included the following in my HTML template:

`<body><span id="injectedStyle"></span>...`

This means that the `<link>` injected during my build will appear in that `<span>` instead of being in the `<head>`, and therefore any MD-injected styles will always be before my link-referenced styles. Of course, putting this into the body is "bad", but it works and is good enough during HMR until I can figure out a more robust approach that will work for a development build, including AoT.

What I would really prefer is that the theme mechanism was expanded to go beyond just the palette, but I'm not familiar enough with the implementation to determine right now what's involved.

(Actually, what I would really, really prefer is for some guru to point out that all I have to do is [insert magical incantations here] and the problem is solved.)

**Comment by craigsnyders** [comment]
Furthermore since `2.0.0-beta.3` we can no longer deep import, so we can't even reference any $vars defined in component sass files.  

In `2.0.0-beta.2` I was using `$mat-toolbar-height-desktop` from `@import '~@angular/material/toolbar/toolbar';` so that I could create my own component which matches the responsive height adjustments that `md-toolbar` uses.

**Comment by rotan-hanrahan** [comment]
@craigsnyders you'll find those Sass vars in the material2 source but not in what's installed for you to use in your own app. The only flexibility you have is in choosing the colour theme. This is a pity, because (as my summary below shows) there are many variables whose values you might want to use, or amend, in your particular application. You could clone your own copy of angular/material2 and make your own prebuilt theme with your own values for the variables just for your own app, but keep in mind that it's all still in beta and can (will) change unexpectedly!

**A sorted list of the defaults found in angular/material2 ( https://github.com/angular/material2 ) on 2017-04-23**:

$mat-autocomplete-panel-above-offset: -24px !default; 
$mat-autocomplete-panel-below-offset: 6px !default; 
$mat-autocomplete-panel-max-height: 256px !default; 
$mat-body-font-size-base: 14px !default; 
$mat-button-border-radius: 2px !default; 
$mat-button-line-height: 36px !default; 
$mat-button-margin: 0 !default; 
$mat-button-min-width: 88px !default; 
$mat-button-padding: 0 16px !default; 
$mat-button-toggle-border-radius: 2px !default; 
$mat-button-toggle-line-height: 36px !default; 
$mat-button-toggle-padding: 0 16px !default; 
$mat-card-border-radius: 2px !default; 
$mat-card-default-padding: 24px !default; 
$mat-card-header-size: 40px !default; 
$mat-card-mobile-padding: 24px 16px !default; 
$mat-checkbox-size: $mat-toggle-size !default; 
$mat-dialog-border-radius: 2px !default; 
$mat-dialog-max-height: 65vh !default; 
$mat-dialog-max-width: 80vw !default; 
$mat-dialog-padding: 24px !default; 
$mat-elevation-property: box-shadow !default; 
$mat-elevation-transition-duration: 280ms !default; 
$mat-fab-border-radius: 50% !default; 
$mat-fab-padding: 16px !default; 
$mat-fab-size: 56px !default; 
$mat-fast-out-linear-in-timing-function: cubic-bezier(0.4, 0, 1, 1) !default; 
$mat-fast-out-slow-in-timing-function: cubic-bezier(0.4, 0, 0.2, 1) !default; 
$mat-font-family: Roboto, 'Helvetica Neue', sans-serif !default; 
$mat-icon-button-border-radius: 50% !default; 
$mat-icon-button-line-height: 24px !default; 
$mat-icon-button-size: 40px !default; 
$mat-icon-size: 24px !default; 
$mat-input-floating-placeholder-scale-factor: 0.75 !default; 
$mat-input-hint-min-space: 10px !default; 
$mat-input-wrapper-spacing: 1em !default; 
$mat-linear-out-slow-in-timing-function: cubic-bezier(0, 0, 0.2, 0.1) !default; 
$mat-menu-font-size: 16px !default; 
$mat-menu-item-height: 48px !default; 
$mat-menu-overlay-max-width: 280px !default;   // 56 * 5 
$mat-menu-overlay-min-width: 112px !default;   // 56 * 2 
$mat-menu-side-padding: 16px !default; 
$mat-menu-vertical-padding: 8px !default; 
$mat-mini-fab-padding: 8px !default; 
$mat-mini-fab-size: 40px !default; 
$mat-progress-bar-full-animation-duration: 2000ms !default; 
$mat-progress-bar-height: 5px !default; 
$mat-progress-bar-piece-animation-duration: 250ms !default; 
$mat-progress-bar-primary-indeterminate-scale-step-2: cubic-bezier(0.334731, 0.12482, 0.785844, 1) !default; 
$mat-progress-bar-primary-indeterminate-scale-step-3: cubic-bezier(0.06, 0.11, 0.6, 1) !default; 
$mat-progress-bar-primary-indeterminate-translate-step-2: cubic-bezier(0.5, 0, 0.701732, 0.495819) !default; 
$mat-progress-bar-primary-indeterminate-translate-step-3: cubic-bezier(0.302435, 0.381352, 0.55, 0.956352) !default; 
$mat-progress-bar-secondary-indeterminate-scale-step-1: cubic-bezier(0.15, 0, 0.515058, 0.409685) !default; 
$mat-progress-bar-secondary-indeterminate-scale-step-2: cubic-bezier(0.31033, 0.284058, 0.8, 0.733712) !default; 
$mat-progress-bar-secondary-indeterminate-scale-step-3: cubic-bezier(0.4, 0.627035, 0.6, 0.902026) !default; 
$mat-progress-bar-secondary-indeterminate-translate-step-1: cubic-bezier(0.15, 0, 0.515058, 0.409685) !default; 
$mat-progress-bar-secondary-indeterminate-translate-step-2: cubic-bezier(0.31033, 0.284058, 0.8, 0.733712) !default; 
$mat-progress-bar-secondary-indeterminate-translate-step-3: cubic-bezier(0.4, 0.627035, 0.6, 0.902026) !default; 
$mat-progress-spinner-constant-rotate-duration: $mat-progress-spinner-duration * 0.55 !default; 
$mat-progress-spinner-duration: 5250ms !default; 
$mat-progress-spinner-sporadic-rotate-duration: $mat-progress-spinner-duration !default; 
$mat-progress-spinner-stroke-width: 10px !default; 
$mat-progress-spinner-viewport-size: 100px !default; 
$mat-radio-size: $mat-toggle-size !default; 
$mat-select-arrow-margin: 4px !default; 
$mat-select-arrow-size: 5px !default; 
$mat-select-panel-max-height: 256px !default; 
$mat-select-trigger-font-size: 16px !default; 
$mat-select-trigger-height: 30px !default; 
$mat-select-trigger-min-width: 112px !default; 
$mat-slide-toggle-bar-border-radius: 8px !default; 
$mat-slide-toggle-bar-height: 14px !default; 
$mat-slide-toggle-bar-width: 36px !default; 
$mat-slide-toggle-height: 24px !default; 
$mat-slide-toggle-ripple-radius: 23px !default; 
$mat-slide-toggle-spacing: 8px !default; 
$mat-slide-toggle-thumb-size: 20px !default; 
$mat-slider-focus-ring-size: 30px !default; 
$mat-slider-min-size: 128px !default; 
$mat-slider-padding: 8px !default; 
$mat-slider-thickness: 48px !default; 
$mat-slider-thumb-arrow-gap: 12px !default; 
$mat-slider-thumb-border-width-active: 2px !default; 
$mat-slider-thumb-border-width-disabled: 4px !default; 
$mat-slider-thumb-border-width: 3px !default; 
$mat-slider-thumb-default-scale: 0.7 !default; 
$mat-slider-thumb-disabled-scale: 0.5 !default; 
$mat-slider-thumb-focus-scale: 1 !default; 
$mat-slider-thumb-label-size: 28px !default; 
$mat-slider-thumb-size: 20px !default; 
$mat-slider-tick-color: rgba(0, 0, 0, 0.6) !default; 
$mat-slider-tick-size: 2px !default; 
$mat-slider-track-thickness: 2px !default; 
$mat-snack-bar-button-margin: 48px !default; 
$mat-snack-bar-max-width: 568px !default; 
$mat-snack-bar-min-width: 288px !default; 
$mat-snack-bar-padding: 14px 24px !default; 
$mat-tab-animation-duration: 500ms !default; 
$mat-tab-bar-height: 48px !default; 
$mat-toggle-padding: 8px !default; 
$mat-toggle-size: 20px !default; 
$mat-toolbar-font-size: 20px !default; 
$mat-toolbar-height-desktop: 64px !default; 
$mat-toolbar-height-mobile-landscape: 48px !default; 
$mat-toolbar-height-mobile-portrait: 56px !default; 
$mat-toolbar-padding: 16px !default;

**Comment by jelbourn** [comment]
We don't consider the variables to be part of the public API for Angular Material at this time. The issue with overriding them is that it would force sass compilation to happen downstream, disallow the components from being able to use `styleUrls`, and generally make the getting-started workflow more complicated. 

Ultimately css custom properties is the way we want to address this, but supporting IE11 makes this not feasible presently.

**Comment by yogeshgadge** [comment]
@jelbourn Wondering if the sass compilation be enforced downstream using angular-cli that is for only those who create custom theme and want to take control of sizes etc. in their own hands.

What I am suggesting is - regardless of angular-cli - if we can provide a "easier" way for sass compilation to occur at the application build time which produces bundles that the styleUrls can use ?

**Comment by dima-gusyatiner** [comment]
I would rather have a top-level `style.scss` file and `_variables.scss`.
This approach works fine, but just as @rotan-hanrahan mentioned - material2 injects a `<style>` tag for each component specific css, resulting in overriding of my top-level layout.
