### ISSUE TITLE
Radio buttons are not vertically centered

### ISSUE THREAD

**Issue by Ploppy3** [angular/material2#3192]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Radio buttons should be vertically centered.

#### What is the current behavior?
Radio buttons are not vertically centered.

#### What are the steps to reproduce?
http://plnkr.co/edit/cfjy3NwNrVJylAb1xrgd?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Material 2.0.0-beta.3

#### Is there anything else we should know?
I'm pretty sure it's an issue as they are centered literally everywhere else.
- MaterialJs
- Material Design Lite
- Android

**Comment by JacobBrandt** [comment]
The checkbox is really not much different than the radio but it doesn't have this alignment issue.  The two have a very subtle html structural difference for the label content and of course the parent group container for the radio.  The breakdown in their appearance is of course the styling but what's concerning is that they have a different naming convention.  I think we can help reduce issues like this in the future with some consistent naming conventions.  I'd like to help resolve this where the two are essentially the same.  This means a small adjustment to the radio containing a span instead of a div for the label content and then changing the radio to use similar names for its html elements that the checkbox used.

Before I dive in though I would like to hear from the team whether or not someone is looking into this yet and/or their thoughts on this approach.

**Comment by JacobBrandt** [comment]
Just noticed slide toggle is also not visually consistent with checkbox or radio.  It's label content has a font-size: 14px and font-weight: 500 that neither of them have.  Wondering if that should also be looked into modified as well.

**Comment by jelbourn** [comment]
Related to #2124

**Comment by fxck** [comment]
![image](https://cloud.githubusercontent.com/assets/1303561/26775471/6543703e-49d5-11e7-851e-df0d278657be.png)

@jelbourn is this the same issue?

**Comment by Ploppy3** [comment]
@fxck that's the issue that I'm reporting.

**Comment by fxck** [comment]
I couldn't tell, the plunker you linked doesn't work anymore.

**Comment by Ploppy3** [comment]
@fxck because they broke it once more.
