### ISSUE TITLE
Toolbar height in app header

### ISSUE THREAD

**Issue by s3ppo** [angular/material2#3233]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Toolbar height switches when android keyboard appears in chrome for mobile

#### What are the steps to reproduce?

place Toolbar on top of app header -> place input field under it -> click input field -> when android keyboard appears, the toolbar switches from portrait to landscape and the height of the toolbar jumps
u can see it on my demosite. https://atippr.moniholz.at click in the loginform an watche the toolbar on top,  when the keyboard appears

#### Which versions of Angular, Material, OS, browsers are affected?
beta-2

#### Is there anything else we should know?
![capture _2017-02-22-01-41-59](https://cloud.githubusercontent.com/assets/17125438/23192114/e22e522e-f8a1-11e6-9e2b-647aace23b8c.png)
![capture _2017-02-22-01-42-09](https://cloud.githubusercontent.com/assets/17125438/23192129/f58b3a6c-f8a1-11e6-90fa-4cde64264f61.png)

**Comment by joejordanbrown** [comment]
Adding overflow hidden to the body fixes this issue with onscreen keyboards pushing up the toolbar.

```
body {
    overflow: hidden;
}
```

**Comment by s3ppo** [comment]
thanks for your answer, i tried this, but no effect :(

**Comment by joejordanbrown** [comment]
Looking into this more the problem is with how media queries calculate the orientation: portrait and landscape. So when the virtual keyboard is opened, it resizes the viewport and the media queries for the md-toolbar switch from portrait 56px to landscape 48px.

@DevVersion I notice you created the pull to add the responsive sizing to the toolbar #2157. Are there plans to use alternative media queries instead of using the orientation?
