### ISSUE TITLE
Md-card - Proposal: Add height property

### ISSUE THREAD

**Issue by da45** [angular/material2#3349]
####proposal:
User can define md-card height, max-height & min-height

#### What is the current behavior?
Cannot define md-card height, 

#### Which versions of Angular, Material, OS, browsers are affected?
All version

**Comment by willshowell** [comment]
@da45 You should be able to style `md-card` just like any other element

http://plnkr.co/edit/z09NRuIAcn9cYkTqsZdI?p=preview

Is this what you mean?

Also, if you ever want to style an element that you don't have access to due to view encapsulation, you can use [`/deep/` ](https://angular.io/docs/ts/latest/guide/component-styles.html#!#-deep-).

**Comment by da45** [comment]
Yes, thanks a lot
