### ISSUE TITLE
md-tab click event or anyo ther event not working

### ISSUE THREAD

**Issue by dharveshmydeen** [angular/material2#3397]
i cannot trigger any event while clicking 
i want to know index value of the tab when i click some function in md-tabs-group
i cannot use any click function in md-tab
i need some unique value while changing or focusing tabs

**Comment by andrewseguin** [comment]
@dharveshmydeen It helps us tremendously when the issue template is used. It should includes details regarding actual vs. expected behavior as well as steps to reproduce the problem. When we have that information, we can look into making the right changes to the library to help you out. Feel free to open a new issue or reopen this issue once you have the template with the provided details.
