### ISSUE TITLE
Tooltip weird behavior

### ISSUE THREAD

**Issue by AntiCZ** [angular/material2#3456]
If I use Toolip normaly(mouse hovers) and click on the tooltip -> disappear. This is weird. Tooltip should  
disappear after mouseleave/mouselout not on the click.

When I try use methods show() and hide() so mouse hovers also works. I dont know how disable mouse hovers and only listen show() and hide() | toggle()

For calling directive methods I use

```
@ViewChild(MdTooltip) tooltip:MdTooltip;
 ...
onClick(){
  this.isTooltipVisible ? this.tooltip.hide(300) : this.tooltip.show(300); 
}
```

And with mouse hovers is not possible select text in the tooltip bacause mouse hovers ingnore tooltip content as a part of the tooltip.

**Comment by thomaspink** [comment]
Possible solution would be a property/function for enabling&disabling the `mouseenter` and `mouseleave` listeners. Maybe also `longpress` and `touchend`. 

@jelbourn @DevVersion @kara Your opinion on that? If you'd like the feature i will create a PR

**Comment by AntiCZ** [comment]
@thomaspink Should be nice. Tooltip is little bit user unfriendly for now.

**Comment by DevVersion** [comment]
@thomaspink Please wait for @andrewseguin's feedback on this. He worked a lot on the tooltip component.

**Comment by thomaspink** [comment]
@DevVersion Thanks for the response
@andrewseguin If you have finished your work, pls let me know if this is still up :)

**Comment by andrewseguin** [comment]
In the future, please use the issue template because it helps us understand your expected use case compared to current behavior. It sounds like this issue involves several different requests.

(1) Clicking should not make the tooltip disappear
(2) Unable to disable mouseenter/mouseleave to show and hide the tooltip
(3) Cannot select the text in the tooltip

I'll try to address them one by one:

(1) The material design spec states that a tooltip will disappear if a user takes an action. We interpret this as inclusive of the user clicking on the page.

(2) Can you provide some use cases that would help us build a convincing argument for an API to disable mouseenter/mouseleave? This seems to be counter-intuitive for users and not a part of the material design spec.

(3) When shown, the tooltip covers up the surrounding user interface and should not keep a user from interacting with these elements. I'm not familiar with tooltips that let the user select their text. You may want to reconsider if your goals are met by using tooltips or if another user experience is better suited.

**Comment by AntiCZ** [comment]
I am sorry for my late reaction.

1) Yes, but if you have delay 300ms and you click between 0-300ms nothing happend or tooltip disappear.

2) If I want use only click evenets. This is normal setting of tooltips. I use hover only on links and buttons(CSS effects). I hate if I am moving with mouse on the page and suddenly tooltip here, some box rise up there etc.

3) Selecting text is not the best exapmle. But tooltip is the text like other content of the page and you can select normal text on the page. Better example is the link in the tooltip. Now is not possible add link in the tooltip. Imagine it is possible. But you cant click on it. Typical example: "some short info....... More info you find here(link with target blank)"

**Comment by M-Adoo** [comment]
In my case, I want show tooltip when user click a component, some people don't know long press to display it.

**Comment by andrewseguin** [comment]
Clicking a tooltip no longer causes it to disappear. If there are other feature requests or issues please open a new issue individually so we can investigate and discuss.
