### ISSUE TITLE
How to update value in Progress spinner in real time?

### ISSUE THREAD

**Issue by ajkyru** [angular/material2#3464]
I mean: how to update value every second (not by radio buttons, inputs, e.t.c) ?

**Comment by dahaupt** [comment]
@ajkyru For normal questions please use this chat: https://gitter.im/angular/material2.

If you need a timer to increase a value after time you could try this: http://stackoverflow.com/questions/35813310/how-to-create-timer-in-angular2 
I just googled "Angular2 create timer".

Feel free to close this issue yourself, because it's no issue in this repository.

**Comment by dahaupt** [comment]
Here is a plunk for this I created quickly:
http://plnkr.co/edit/TeROn5OdfKQsj1QivS5f?p=info

@kara Any idea why `md-progress-spinner` and `md-spinner` have a different behavior?
