### ISSUE TITLE
when applying md-button on a button, (click) is not triggered

### ISSUE THREAD

**Issue by maxime1992** [angular/material2#3478]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Even if a button has the `md-button` attribute we should be able to bind the click event.

#### What is the current behavior?
Checkout this [line](https://gitlab.com/linagora/petals-cockpit/blob/ab7f5d5816e41f399b2fdd72e1692d4b51082484/frontend/src/app/features/cockpit/workspaces/petals-content/petals-service-unit-view/petals-service-unit-overview/petals-service-unit-overview.component.html#L26) of HTML : 
```
<button
*ngFor="let possibleState of getPossibleStateActions(serviceUnit.state)"
(click)="changeState(possibleState.newStateAfterAction)"
[disabled]="serviceUnit.isUpdatingState"
>
  {{ possibleState.actionName }}
</button>
```

the `changeState` function is called.

<hr>

**But if I add `md-button` or `md-raised-button` on the button, the design is the one expected but clicking on the button never triggers `changeState` function.**

<hr>

#### What are the steps to reproduce?
```
git clone https://gitlab.com/linagora/petals-cockpit.git
git checkout ab7f5d5816
cd frontend
yarn
ng serve
```

I did try to reproduce on Plunkr **but I couldn't**.
I didn't check the version on Plunkr but maybe Angular is running on `2.x` and my project is running `4.0.0-rc.2`.

#### Which versions of Angular, Material, OS, browsers are affected?
`4.0.0-rc.2` (didn't try under that version)

**Comment by maxime1992** [comment]
Similar problem today. I wanted to create a tooltip and it was not showing up.

I really didn't understand why and in ended up moving my span with the tooltip **before** my `*ngFor` :  
Tooltip is working.

Here's the code :
![image](https://cloud.githubusercontent.com/assets/4950209/23742594/c2da0dd8-04ad-11e7-8bf1-a12f3eee9621.png)

(exact same line except that the second one is within an `*ngFor`.

**Comment by christophechevalier** [comment]
Hello everyone.

@crisbeto

It's been 3 weeks since the issue was opened, and there is no news.  
Is this bug being resolved ?

Thanks guys. :octopus:

**Comment by crisbeto** [comment]
I haven't had the chance to look at it yet. I'll check it out tonight.

**Comment by crisbeto** [comment]
@maxime1992 I wasn't able to reproduce it locally with a similar HTML structure. Can you try to do another Plunkr? [Now our template uses Angular 4 as well.](https://goo.gl/DlHd6U)

**Comment by maxime1992** [comment]
@crisbeto couldn't repro in the Plunkr :disappointed: 

If you want to try in our repo : 
```
git clone git@gitlab.com:linagora/petals-cockpit.git
cd petals-cockpit/frontend
yarn
ng serve
```

Open your browser at : [http://localhost:4200/workspaces/idWks0/petals/service-units/idSu0](http://localhost:4200/workspaces/idWks0/petals/service-units/idSu0)

Open the file
`src/app/features/cockpit/workspaces/petals-content/petals-service-unit-view/petals-service-unit-overview/petals-service-unit-overview.component.html`

Change those lines :
```
<button
  *ngFor="let possibleState of getPossibleStateActions(serviceUnit.state)"
  (click)="changeState(possibleState.newStateAfterAction)"
  [disabled]="serviceUnit.isUpdatingState"
>
```

By :
```
<button
  md-button
  *ngFor="let possibleState of getPossibleStateActions(serviceUnit.state)"
  (click)="changeState(possibleState.newStateAfterAction)"
  [disabled]="serviceUnit.isUpdatingState"
>
```
(notice the `md-button` attribute on the `button`)

With the button like that : 
![image](https://cloud.githubusercontent.com/assets/4950209/24393207/7b02c204-1397-11e7-9abb-efa8fdec4e53.png)

The click works and you'll see the UI updated

With the material button, click doesn't work : 
![image](https://cloud.githubusercontent.com/assets/4950209/24393183/61c8232e-1397-11e7-80e8-c43a6f543a48.png)

**Comment by crisbeto** [comment]
Your issue comes from the fact that the button actually gets re-rendered on `mouseup`. It just happens so fast that you can't notice that the button got swapped out. You can break it in the same way if you add a blank `mouseup` to a regular button:

```
<button
  *ngFor="let possibleState of getPossibleStateActions(serviceUnit.state)"
  (click)="changeState(possibleState.newStateAfterAction)"
  [disabled]="serviceUnit.isUpdatingState"
  (mouseup)="noop()"
>
  {{ possibleState.actionName }}
</button>
```

What happens in this case is that the button ripple effect triggers change detection on the `mouseup` event (this has actually been fixed in https://github.com/angular/material2/pull/3066) and because `getPossibleStateActions` returns a completely new array every time, `ngFor` will destroy the button and re-create it. Since it was destroyed before you released the button, the click event won't end up firing at all. This is something that you should fix in your app by making `getPossibleStateActions` return the same array or assign its result to a property.

Here's a similar issue from a month ago.

**Comment by maxime1992** [comment]
It sounds like I could have post my question on StackOverflow now but thank you @crisbeto, I really appreciate the (detailed) explanation ! :smiley: :beers:

**Comment by victornoel** [comment]
@crisbeto there is something I didn't understand in your explanation/workaroud.

What I understood is that you say that `getPossibleStateActions` should return the same array every time it is called (or at least if the set of actions contained in the array does not change).

My question is: is it needed to return the same array with `getPossibleStateActions` ONLY because the mousup event is broken (and fixed in #3066), or are you saying that `getPossibleStateActions` should always manage to return the same array (for the same set of possible action of course)?

Thank you for your time :)

**Comment by crisbeto** [comment]
The `mouseup` thing is just a symptom that this does work as expected. When `getPossibleActions` returns a new array every time, `ngFor` will re-render the entire repeater every time you do something on the page that triggers change detection, which is very inefficient considering that nothing has changed. You can see how often this happens if you add a `console.log` in `getPossibleStateActions`.

**Comment by victornoel** [comment]
@crisbeto that's the thing, if we put a `console.log` in the method (and put back the `md-button` and let the method return a new array every time), it is triggered only when the page is loaded, and when we click on a button… whatever we do around that has no impact apparently (even the `mouseup` actually does not trigger that!).
Note that the component is a "dumb" component with the `OnPush` change detection, that may be why.

But, could you really confirm something to me: do we agree that once #3066 is applied, the original problem should be solved EVEN IF `getPossibleActions` returns new arrays every time?

**Comment by crisbeto** [comment]
Yes, I believe that it should be fixed once #3066 is in. You can try out the latest build with this:

```bash
npm install https://github.com/angular/material2-builds.git
```

**Comment by victornoel** [comment]
ok, thanks for your help :)

**Comment by victornoel** [comment]
For the record (if someone comes around here with the same problem), another solution is to exploit `trackBy` of `*ngFor` with a function indexed on the input of `getPossibleActions` (since it is a pure function, we know its result won't change if its input doesn't).
Like this, even the `mouseup` event won't replace the button or stuffs like this.
