### ISSUE TITLE
Swiping should work when HammerJS is loaded async

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#3507]
see https://github.com/angular/material.angular.io/issues/120

**Comment by crisbeto** [comment]
@mmalerba to continue the discussion: I can't get it to fail locally (probably because of caching or fast internet) just by setting it to `async` and moving it to the end of the body. I think that we may open ourselves up to some race conditions if we only defer to checking for Hammer the first time that it's requested. It might be better to let users supply the Hammer URL and let us load it (via an injection token). 

cc @jelbourn

**Comment by mmalerba** [comment]
I got it to fail only on firefox when it wasn't cached, but yes its kind of race condition-y

**Comment by crisbeto** [comment]
My concern for adding an injection token is that it's a potential security vulnerability that will let people load all kinds of scripts.

**Comment by crisbeto** [comment]
Actually, I see why I went with doing it in the constructor last time: Angular checks for the supported events on load (see https://github.com/angular/material2/blob/master/src/lib/core/gestures/gesture-config.ts#L11) and if they are defined, but there's no Hammer, it throws an error. I don't think we can do much about it in either case.

**Comment by jelbourn** [comment]
Not sure if installing an event plugin would be possible at run-time with AoT

**Comment by crisbeto** [comment]
Nope, doesn't look like we can do anything about it, apart from what we're doing already.
