### ISSUE TITLE
After Adding Custom Theme my Material Components Aren't Functioning

### ISSUE THREAD

**Issue by darrenbrett** [angular/material2#3559]
My dev environment:
@angular/cli: 1.0.0-rc.1
node: 7.4.0
os: darwin x64

I am using less compilation in my Angular-cli app. But, from my understanding, as long as I have a custom theme with an scss extension, that should still work when creating a custom theme. My custom theme, located in my src folder, looks like this:

```
@include md-core();

$app-primary: md-palette($md-indigo);
$app-accent:  md-palette($md-green, 500);
$app-warn:    md-palette($md-red);

$app-theme: md-light-theme($app-primary, $app-accent, $app-warn);

@include angular-material-theme($app-theme);
```

And I am importing this file in my root styles.css file, like this:
`
@import 'custom-theme.scss';`

And in my angular-cli.json file, I've addd this:

    "styles": [
      "styles.css",
      "custom-theme.scss"
    ]

After making the switch to this custom theme, my material components aren't working at all - neither the functionality nor the styling.

**Comment by andrewseguin** [comment]
Your problem is likely due to styling prefixes being renamed from `md-` to `mat-`. For example, `md-core` is now `mat-core`. 

Closing since this is more of a question on setup rather than issue with the library. If you need more help, feel free to reach out to our great community on gitter, Google Groups, stack overflow, and others.
