### ISSUE TITLE
[Tooltip] Tooltip should automatically determine position

### ISSUE THREAD

**Issue by seedy** [angular/material2#3569]
#### Bug, feature request, or proposal:
Feature request : tooltip auto positionning

#### What is the expected behavior?
mdTooltip linked to 
`<md-icon-button>`
with no tooltipPosition defined
should position automatically based on the given space,
or at least automatically setup its tooltipPosition

#### What is the current behavior?
Default tooltip shows up below the element and overflows the screen

#### What are the steps to reproduce?
Add a tooltip to a `<md-icon-button>` on the edge of your screen

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
[Plunker](http://plnkr.co/edit/zpVxJQzpUCYPfoANfC4G?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
Avoid developpers handling themselves the edge case with approximate ElementRef manipulation.

#### Which versions of Angular, Material, OS, browsers are affected?
"@angular/material": "^2.0.0-beta.2"

#### Is there anything else we should know?
I found my way getting around this issue, by manipulating ElementRef after the view is initialized :
```
ngAfterViewInit() {
    if(this.elRef.nativeElement.offsetLeft === 0){
      this.tooltipPosition = "right";
    }
  }
```
[workaround Plunker](http://plnkr.co/edit/SSRRxldfBo8W72NfJK9P?p=preview)

I'm not used to angular2 dom manipulations, any better option would be highly appreciated

**Comment by jnamesky** [comment]
Auto positioning so the tooltip will display on screen is a feature I know our team will be needing at some point in the near future.

**Comment by jelbourn** [comment]
@andrewseguin what is the current behavior of tooltip when there is no position set? If it's not using it already, overlay supports fallback positions.

**Comment by Goodwine** [comment]
@jelbourn The default is "below"
https://github.com/angular/material2/blob/cd55082a488e58a3f4948bba8e5d0a6771a57233/src/lib/tooltip/tooltip.ts#L67

Still I am very interested in having a tooltip handles positioning itself.
For example... if I choose "after", it gets rendered at the right (in LTR), but what if the element is on the right edge? well.. the tooltip goes out of the page.
It would be very helpful if the tooltip positions itself at the bottom (since it's "after") when there is no space at the right, and that it moves slightly to the left (so it's not centered anymore) so the entire tooltip fits rather than being cut.

**Comment by mbeckenbach** [comment]
position would be great in lots of use cases. Especially when creating responsive applications.

**Comment by andrewseguin** [comment]
Fallback positioning has been added to the tooltip
