### ISSUE TITLE
Problem with change object for md-radio-group 

### ISSUE THREAD

**Issue by educc** [angular/material2#3609]
#### Bug, feature request, or proposal:
I have an array of objects with options and his selected value. When change the object for the radio group sometimes show the check.

#### What is the expected behavior?
The radio button shows the option according to the model.

#### What is the current behavior?
The radio button doesn't show the option according to the model.

#### What are the steps to reproduce?
Go to : [https://plnkr.co/edit/2qyiClwIeHQsZocDWVTa?p=preview](https://plnkr.co/edit/2qyiClwIeHQsZocDWVTa?p=preview)

Click on "opt1" radio.
Click on "Question 2" button
Click on "Question 1" button (doesn't show check on radio)
Click on "Question 2" button
Click on "Question 1" button (show check on radio)

#### Which versions of Angular, Material, OS, browsers are affected?
Angular Version: 2.4.0
Angular Material Version: 2.0.0-beta.2

**Comment by jelbourn** [comment]
@tinayuangao could you investigate whether there's an issue here? Something _does_ seem odd in the plunker.

**Comment by tinayuangao** [comment]
@educc 

This is because in template `*ngFor="let item of current.alt"`,  `current.alt` is a variable. Every time current changes, the template will generate a new list of radio buttons. The new list of radio buttons and old radio buttons have different ids and same values so they have odd behaviors. 

One solution is to make `alt`s constant.
