### ISSUE TITLE
Dart transpilation

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#37]
- [x] Re-use facades from `angular/angular`
- [x] Dart output is generated from TS source
- [x] Dart output passes DartAnalyzer
- [x] Dart code is built and passes DartAnalyzer on Travis
- [ ] Demo site runs in Dartium with Dart source (alpha.2)
- [ ] Unit tests run in Dart (alpha.3)
- [ ] Unit tests run in Dart on Travis (alpha.3)
- [ ] E2E tests run against Dartium (alpha.4)

Where possible, extract as much as possible from `angular/angular` and use in both repos OR make improvements to `ts2dart` directly.

**Comment by jelbourn** [comment]
cc @yjbanov @vsavkin what else is missing here? I know this isn't a complete list.

**Comment by yjbanov** [comment]
That's a pretty good list already. Other things to consider:

- Run `dartanalyzer` with strong mode enabled (`--strong`)
- Dart code can be opened and edited in an IDE
- Since material components are heavy on styling, I'd recommend running e2e tests in non-Chromium browsers too

Like angular/angular this repo is setting itself up to swim against the current. Why not adopt a package layout that works for all languages?

```
/             - repository root
/bin/         - command-line user tools
/lib/         - importable source code
/lib/src/     - non-importable (package-private) source code
/web/         - sample web apps, e2e test apps
/test/        - unit-tests, webdriver tests
/tools/       - command-line project tools (shell scripts, etc)
package.json  - NPM config file
pubspec.yaml  - pub config file
```

**Comment by yjbanov** [comment]
Forgot to mention. A better way to run Dart tests than Karma is using [`package:test`](https://github.com/dart-lang/test). It is a well supported test API and a test runner that can run in all browsers, including PhantomJS. You'll need to use `package:guinness2` instead of `package:guinness`.

**Comment by zoechi** [comment]
Is this the issue to follow the progress about the first (alpha) release for Dart?

**Comment by jelbourn** [comment]
@zoechi There's some news on this front. The team decided yesterday that we will be able to achieve the most impact from our efforts by no longer supporting a Dart version of Angular Material (Angular itself is unchanged). We know this is unfortunate for those hoping to use the Dart version, but we've concluded that the effort and time required get a quality Dart output working will be better spent making a totally solid TypeScript / JavaScript version.

For Material Design components with Angular 2 Dart, we'd recommend looking into interop with Polymer or Material Design Lite.

**Comment by marcojakob** [comment]
@jelbourn Very, very disappointed to hear that. I love Dart and I thought Dart could have a bright future. A good and complete UI library was the missing piece for me to finally start big projects. But I'm tired of waiting (a long time) and hearing promises that are never fulfilled and projects that are cancelled.

Yes, I'm looking at you, [Dart VM in the browser](http://techcrunch.com/2015/03/25/google-will-not-integrate-its-dart-programming-language-into-chrome/), [Chrome Dev Editor](https://plus.google.com/+SriramSaroop/posts/6EwgknwKpeS), [DartEditor](http://news.dartlang.org/2015/04/the-present-and-future-of-editors-and.html), [Packages support for DartPad as replacement for DartEditor](https://github.com/dart-lang/dart-services/issues/43), and so on.

When will you announce that Angular 2 Dart will be discontinued as well, because, of course, it's too much work?

**Comment by zoechi** [comment]
unfortunate is quite some understatement

**Comment by tomas234** [comment]
I'm in the exact same situation. What a disappointment :(

**Comment by zoechi** [comment]
@jelbourn thanks for the honest response anyway

**Comment by wstrange** [comment]
This is a really terrible decision. Please reconsider.

**Comment by adaojunior** [comment]
I'm also disappointed, just starting a big angular 2 dart project. Even though we knew it would not be possible to use ng material (it may not be finished in time) we planned to use parts of it in the future.

**Comment by mswift42** [comment]
If even Google can't be bothered to support Angular2 Dart, what message does this send?

Interop with Polymer is not the answer, because according to [this](https://dart.academy/dart-angular-2-and-polymer-together/), it only works with Chrome. That leaves MDL, which might enable one to incorporate Material Design in an app, but is certainly not the ng2 componenty way of assembling an SPA.

Also, according to #199, you are going to make the Tour of Heroes use angular2-material. How will the Dart section of the tutorial then look?

**Comment by marcojakob** [comment]
@mswift42 Agree that interop with Polymer is not the answer. I was also waiting a long time to see if I could use Polymer in larger apps (and also did use it for a few things). But Google seems to have removed all resources from Polymer Dart (except for @jakemac53). The result was that Polymer JS 1.0 was released in May 2015 and now, almost a year later, we are still waiting for Polymer Dart 1.0 with updated official documentation (it's still a [draft on a GitHub wiki](https://github.com/dart-lang/polymer-dart/wiki)). This doesn't make me very confident to bet on Polymer Dart.

In the [Keynote of last years Dart Developer Summit](https://www.youtube.com/watch?v=FiXiI2Atexc) Lars Bak and Kasper Lund announced that **Angular 2.0 will be the preferred web application framework for Dart**. I hope they will quickly come up with a clear strategy and communication about how they plan to do this (which would include a good set of UI components).

Sorry that my frustration is showing through in my statements. I apreciate the awesome work of the Dart team. But I'm very frustrated about communication and being misled so many times.

**Comment by zoechi** [comment]
@mswift42 I haven't tried it myself but I assume that Polymer works on other browsers than Chrome when full web_components polyfills are loaded.

I also still don't see Polymer as a viable replacement for Angular Material.
I wouldn't expect this to work with WebWorkers for example.

**Comment by adaojunior** [comment]
I can't say for everyone else, but I certainly would prefer google to cancel polymer dart but keep angular projects in sync with the ts/js version.

**Comment by andresaraujo** [comment]
I'm also very disappointed with this decision, as zoechi said Polymer doesn't seem a viable replacement

**Comment by filiph** [comment]
To be clear: the Dart team _is_ working on bringing you high quality, pure-Dart Material components for Angular 2. (As you may know, Google is building [big things](http://news.dartlang.org/2016/03/the-new-adwords-ui-uses-dart-we-asked.html) with Angular2, Dart, and Material Design.)

I said this on the dartlang slack yesterday but completely forgot to also say it here. 

The fact that those components won't be coming from the angular/material2 team is, from the outside perspective, an implementation detail. It's just a way not to duplicate effort.

I'm sorry this implementation detail showed. In the ideal world, you'd just get the components immediately. Alas, this is not an ideal world. Please follow our [blog](http://news.dartlang.org/), [G+](https://plus.google.com/+dartlang/posts) or [Twitter](https://twitter.com/dart_lang) for updates on this.

**Comment by mark1010** [comment]
@fillph Let’s hope the Dart version of Material reaches parity with, and tracks, the TypeScript version.

**Comment by fallenreaper** [comment]
wow..  Good to know.

**Comment by ioancristea** [comment]
We want a Dart version!
The Dart programming is the best experience what I consumed for web programming. Material Design is a futuristic product and I want to be able in future to make the apps with this.
Please reconsider.
Please consider that fact
