### ISSUE TITLE
Update theme path

### ISSUE THREAD

**Issue by peluprvi** [angular/material2#3782]
#### Bug, feature request, or proposal:
I think after #3776, `core/theming/prebuilt` path need to be changed to `prebuilt-themes` in [some of those files](https://github.com/angular/material2/search?utf8=%E2%9C%93&q=%22core%2Ftheming%2Fprebuilt%22&type=).

I had to change my css path to :
```html
<link rel="stylesheet" href="../node_modules/@angular/material/prebuilt-themes/indigo-pink.css">
```

**Comment by DevVersion** [comment]
* Only the paths in the markdown files need to be updated
* @jelbourn didn't want to update it yet, because it would just confuse (the new paths isn't released yet)

Also the `core/theming/prebuilt` path is still valid inside of our `demo-app` or `e2e-app`. Just in releases this path will be invalid.

**Comment by jelbourn** [comment]
Everything should be updated everywhere now.
