### ISSUE TITLE
Write guide for building first Material app

### ISSUE THREAD

**Issue by kara** [angular/material2#383]
We need to have a guide that shows people how to create a new app using Material 2 and the Angular CLI.  There's been some confusion over how to write System.js config and how to build vendor files into the right folder.

**Comment by DavidPetit** [comment]
So how do we do it?

I am struggling with this step. Trying to follow what it's said on this page https://github.com/angular/angular-cli/wiki/3rd-party-libs#adding-material2-to-your-project and also here https://github.com/angular/mobile-toolkit/blob/master/guides/app-shell.md

The problem is that createPackageConfig is not recognized and I tried many other ways without success.

Can someone give me an exemple of a working system-config.ts file with material2 please?

**Comment by zigzag95** [comment]
Sorry but what about webpack?

**Comment by DavidPetit** [comment]
I found how to do it by looking at the file in one of Kara's repository here: https://github.com/kara/puppy-love/blob/master/src/system-config.ts

Hope it will help the other people searching for this and before the guide is available.

**Comment by szechyjs** [comment]
Agreed, this commit from Kara helped me get everything working.

https://github.com/kara/puppy-love/commit/9e58a62768aabbb342c38fcf63fbeea55787f37c
