### ISSUE TITLE
md-radio-button wrapped in a md-list-item ignores incoming changes to ngModel

### ISSUE THREAD

**Issue by rkrzewski** [angular/material2#3930]
#### Bug, feature request, or proposal:

Wrapping a md-radio-button in a md-list-item somehow with ngModel data binding. Events are going out, but data changes are not going in: the radio buttons don't assume initial state from the bound variable, clicking the buttons is updating the variable, but variable updates caused by 3rd-party events are not reflected in the buttons state. When the buttons are not wrapped in md-list-item all updates propagate as expected.

#### What is the expected behavior?

md-radio-button should accept incoming state changes regardless of being transcluded by other tags

#### What is the current behavior?

md-radio-button wrapped in md-list-item ignores incoming state changes

#### What are the steps to reproduce?

More verbose Plunker demonstrating a group of unwrapped radio buttons, a group of radio buttons wrapped in md-list-items, and a button triggering 3d-party model changes: https://plnkr.co/edit/MTx4G3cwRyQdVOxuoLo1?p=preview

A minimal Plunker demonstrating a single wrapped radio button that does not assume initial state correctly. Moving the radio outside of list item causes it to assume initial state correctly: https://plnkr.co/edit/CCu6PkZbOxPTov5ekl6o?p=preview 

#### What is the use-case or motivation for changing an existing behavior?

N/A, this is a bug as far as I can tell.

#### Which versions of Angular, Material, OS, browsers are affected?

Angular 2.4.1
Material 2.0.0-beta.2
Ubuntu Linux
Chromium 56.0, Firefox 52.0

**Comment by jelbourn** [comment]
This isn't exactly how the components are meant to be used. For both `md-list` and `md-radio-group` (generally _all_ components that use `@ContentChildren`), the children must be _direct_ children and cannot be nested in other elements. In this case, having the level of indirection makes the content children invisible to the parents. This is the expected behavior of Angular. 

If you want to use radio buttons inside of list items, the group is not actually necessary so long as the radio buttons all have the same `name` property.
