### ISSUE TITLE
BrowserModule can't be used when using BrowserAnimationsModule

### ISSUE THREAD

**Issue by JordyBaylac** [angular/material2#4006]
#### Proposal:
I think that in the [getting started documentation](https://material.angular.io/guide/getting-started), specifically step 2 we should see an indication like: 'When using BrowserAnimationsModule please, do not use BrowserModule, it can only be loaded once in your application, and BrowserAnimationModule has already imported it'.

**Comment by smasherprog** [comment]
This should be documented because I have been trying to get the new version of material to work only to have all sorts of import issues with the aminations and system.js

In the end I gave up and reverted to the previous version because it just wasnt working

**Comment by jotatoledo** [comment]
I had similar issues today while updated from beta2 to beta3. An updated example plnkr/app would be nice to have

**Comment by kblestarge** [comment]
Yep, removing the BrowserModule worked for me. Thanks @JordyBaylac

**Comment by kblestarge** [comment]
Spoke too soon. Without the BrowserModule, some of my lazy-loaded components don't work as expected. `*ngIf` doesn't seem to be working...

**Comment by jelbourn** [comment]
This isn't something that's exactly under Material's umbrella. The issue is that `BrowserAnimationModule` imports `BrowserModule` without also exporting it; `BrowserModule` exports `CommonModule` which contains `ngIf`, `ngFor`, etc., so to fix your problem you can just import `CommonModule` from `@angular/common`.

Feel free to open an issue for this on https://github.com/angular/angular/
