### ISSUE TITLE
Apply .mat-input-invalid on empty required fields at pristine

### ISSUE THREAD

**Issue by AlanCrevon** [angular/material2#4030]
#### Bug, feature request, or proposal:
Request

#### What is the expected behavior?
`.mat-input-invalid` class should be added to empty required fields on pristine.

#### What is the current behavior?
`.mat-input-invalid`  is added only if the field has validator and has been touched.

#### What is the use-case or motivation for changing an existing behavior?
Empty mandatory fields should be visible at first sight.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.0.1
Material2 Beta 3

#### Is there anything else we should know?
I love you. ;)

**Comment by jelbourn** [comment]
For this we follow the [material design spec](https://material.io/guidelines/patterns/errors.html#errors-user-input-errors), which calls for
> Show errors for incompatible values during or after a user interacts with a text field.

**Comment by AlanCrevon** [comment]
Ho... i see. Ok thanks for the answer. :)

**Comment by leblancmeneses** [comment]
Is there plan to add  md-is-error  https://github.com/angular/material/issues/1633   ?

There are some cases I want to show an error even if it is untouched.
Example:
Expense: input[type="number"]
Expense itemization: textarea where [required]="selectedEvent.miscExpenses && selectedEvent.miscExpenses > 0"

The user doesn't know that there is a problem with the form.  I would like to force a visual with md-is-error.

Otherwise, I have to begin adding tooltips to explain to the user why the button is disabled.
![tooltip](https://user-images.githubusercontent.com/730804/27569400-fddf430c-5abc-11e7-8df1-edcd416c7545.png)

**Comment by willshowell** [comment]
@leblancmeneses https://github.com/angular/material2/pull/4750 should accomplish what you need
