### ISSUE TITLE
Focus indicators on md-fab is really subtle

### ISSUE THREAD

**Issue by hansl** [angular/material2#420]
Hard to see the difference unless you really focus on it.

**Comment by jelbourn** [comment]
The [FAB spec](https://www.google.com/design/spec/components/buttons-floating-action-button.html#) describes the focus state for FABs as having an "ink wash", but it's not really clear what that means. I'll follow up with MD UX to see if there is some more guidance.

**Comment by traviskaufman** [comment]
Looks like the [only place](https://www.google.com/design/spec/search.html?q=ink+wash) we use the term "ink wash" is in that description. 

Essentially, a FAB focus behaves the same as a focus on a raised button (in fact in many aspects a FAB can be thought of as a raised button that's circular and has a higher elevation; the biggest differences are semantic. It gets its own section due to the importance and uniqueness of the component within a material app). That phrase should either be clarified or reworded within spec.

**Comment by jelbourn** [comment]
I've opened #467 to make our buttons match what the spec says, but I still find the focus indication to be quite subtle. I'mm close this issue with my PR, but I've also filed a bug with the Material Design UX team and revisit based in their answer.
