### ISSUE TITLE
Allow to customize when md-error is shown

### ISSUE THREAD

**Issue by coder925** [angular/material2#4232]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I would like to be able to customize when the *md-error* directive is visible.
E.g. when `ctrl.dirty && ctrl.invalid`.

#### What is the current behavior?
As per #3560 my understanding is that the *md-error* is only shown when the control is: `(isInvalid && (isTouched || isSubmitted))`

#### What are the steps to reproduce?
See my [Plunker](https://plnkr.co/edit/kBxsOfoxlwdLfm5ObWtD?p=preview).
- Name1 is using md-error. Error will only show after control been touched.
- Name2 is using an old workaround with md-hint. It can show error directly when dirty.

#### What is the use-case or motivation for changing an existing behavior?
For 99% of the time I believe the current implementation is the best behavior.

However, for special cases, you will need to be able to modify when errors are shown. For example instantly as the example from the [Angular documentation](https://angular.io/docs/ts/latest/guide/forms.html#!#show-and-hide-validation-error-messages).

#### Which versions of Angular, Material, OS, browsers are affected?
Angular v4.0.3
Material v2.0.0-beta.3

#### Is there anything else we should know?
I assume my request is not currently possible as [my question on StackOverflow](http://stackoverflow.com/questions/43500290/allow-md-error-to-show-the-error-message-even-if-control-is-untouched) did not get any suggested answers.

**Comment by jelbourn** [comment]
@kara might also have some thoughts on this

**Comment by willshowell** [comment]
@jelbourn, since you labeled #4750 as needing discussion, I'd like to illustrate my motivation for pushing for the change. In [this plunker](http://plnkr.co/edit/B5G7Kz75Nq9xsUvDWXiE?p=preview) you can see that validation must be performed at a group level since the `password` and `confirm` controls are dependent on one another. Per @kara's [suggestion](https://github.com/angular/angular/issues/5635#issuecomment-253372991), this is the best (if not only) way to achieve sibling validation.

Two workarounds must be put into place to emulate the correct behavior:
  1. `class.mat-input-invalid` must be bound to a custom error state matcher
  2. An `<md-hint>` must be styled like an `<md-error>`, thus losing entrance animations, and you must also bind it to the custom error state matcher with `*ngIf`

I recognize that this should be reused in md-select, but I'd hate to have to wait until https://github.com/angular/material2/issues/4672, when the tiny amount of logic could be copied as soon as #4754 lands. Would a typescript mixin work for this?

**Comment by jelbourn** [comment]
I agree that, conceptually, you should be able to change when the error shows. I'm just not sure this is a good way to go about doing that customization. Having it as an input on the control means that there's no good way to configure the behavior app-wide, which I think would be important.

**Comment by willshowell** [comment]
Dang, had not considered global config and I agree
