### ISSUE TITLE
has no exported member 'Renderer2'.

### ISSUE THREAD

**Issue by yubeen** [angular/material2#4276]
#### Bug, feature request, or proposal:

node_module/flex-layout has no exported member 'Renderer2'.

#### What are the steps to reproduce?
npm start

#### What is the use-case or motivation for changing an existing behavior?
Renderer2 is in angular4. 
but, I was no versions upgrade.
24day, suddenly made error 

#### Which versions of Angular, Material, OS, browsers are affected?

all versions - 2.3.1
OS : mac sierra

#### Is there anything else we should know?
I want no versions upgrade :) thanks

**Comment by fxck** [comment]
https://github.com/angular/flex-layout

**Comment by crisbeto** [comment]
Both Material and Flex layout require a minimum Angular version of 4.0. We can't support both 2.3 and 4.0, because some of the APIs aren't backwards compatible, in addition to the update being relatively simple to do on the user's side. You can either update your project to 4.0, or use older versions of Material and Flex layout.

**Comment by yubeen** [comment]
I watched there page but page not in solution.
I want no setup and no version upgrade
before 24day, no error
