### ISSUE TITLE
Bug: Dark Theme background not taking effect when Router-Outlet is used.

### ISSUE THREAD

**Issue by viztastic** [angular/material2#4333]
#### **Bug**

When a `router-outlet` is included in the root component, the `mat-app-background` doesn't seem to take effect.

#### What is the expected behavior?

When I toggle to a dark theme, I expect the background color to go dark.

#### What is the current behavior?

The background color remains white irrespective of whether `mat-app-background` is included.

#### What are the steps to reproduce?

The plunker doesn't let me repro the issue with SCSS, so have [created a simple repo here](https://github.com/viztastic/themetoggle_bug) that you can 
activate using `yarn` followed by `ng serve`. The screenshot below should also help.

Below is the dark theme activated, you can see the background remains white even though we added the `mat-app-background` to body. 

![image](https://cloud.githubusercontent.com/assets/8556736/25562663/c283219e-2dcf-11e7-8203-01811925a261.png)

#### What is the use-case or motivation for changing an existing behaviour?
I think the experience of adding `mat-app-background` should work irrespective of whether router-outlets are involved. 

#### Which versions of Angular, Material, OS, browsers are affected?

OS: Mac OSX
Dependencies including Angular, Angular-CLI below:

```json
"dependencies": {
    "@angular/animations": "^4.1.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.1",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
```

#### Is there anything else we should know?

Have tried various hacks such as applying `min-width:100vh` to various root tags to see if this had any bearing, to no effect.

**Comment by viztastic** [comment]
@andrewseguin I see you have self assigned this, is there anything I can help to further clarify my bug report? Desperately hoping it's a quickfix that can be included as part of the next release.

**Comment by littleninja** [comment]
I'm curious: your project was built with angular-cli and webpack (dependency)? Mine is too. I wonder if others who are *not* using webpack or angular-cli also have this issue.

**Comment by JaimeStill** [comment]
Perhaps conversation in #3298 is relevant?

**Comment by andrewseguin** [comment]
Looks like #3298 will be helpful here. If there is further issue here can you please re-open?

**Comment by arthur-clifford** [comment]
I know this bug is closed. But I recently ran into an issue where using the Router tech I wasn't able to set the background for the body tag in a way that would be honored.

I have enough css stuff happening that it may well be something I introduced, but what was interesting is that in order to get the body to actually honor the background I was setting I had to set:
body {
  display:inline-block;
  width: 100vw;
  height: 100vh;
}
That is, admittedly, a dirty hack, but it worked.
I don't know if the Router tech is at all relevant, however, the only element that would first honor the background color was the app router element and setting it's background to transparent didn't do anything.

So, if anybody is having a similar problem you might see if your body tag's behavior is fixed by this hack, and/or look deeper into why the body or other container for your app router may not be displaying as you expect.
