### ISSUE TITLE
<md-select> doesn't close when you click outside of dropdown.

### ISSUE THREAD

**Issue by IVIyg0t** [angular/material2#4343]
For some reason, my `md-select` doesn't close when you click outside of it.... It forces you to choose an option.  I'm not able to get this issue reproduced... So I'm not sure how to give you more info about that.  I tried disabling all the CSS that I could, but that didn't' seem to help.  I'm at the point of seeing if I can just create my own trigger to close the dropdown.  

Is there a way to programmatically close a `md-select` dropdown?

Thanks guys.

**Comment by willshowell** [comment]
As you can see from here https://plnkr.co/edit/7xvf8N4wKrg6yOY9XE9d?p=preview, the select does close when you select an item, tab out, or click on the backdrop.

If you're set on programmatically closing it, check the [api reference for md-select](https://material.angular.io/components/component/select). It has a `close()` method.

Also, support questions for your specific implementation should be asked in Gitter or Stack Overflow instead of github issues.

**Comment by jelbourn** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
