### ISSUE TITLE
Docs(autocomplete): regex filter search issue with character "?" and "$"

### ISSUE THREAD

**Issue by skyfremen** [angular/material2#4440]
#### Bug, feature request, or proposal:
Documentation Bug on custom filtering : https://material.angular.io/components/component/autocomplete

#### What is the expected behavior?
Able to filter with character starting with ? and $ 

#### What is the current behavior?
Application crashes when filtering with character starting with ?
Not able to filter with character starting with $

#### What are the steps to reproduce?
[Plunker Link](https://plnkr.co/edit/nmLXRZ1ZgyaMpOwnYLdS?p=preview)
**Search With > Result**
S > Shelley
? > Application Crash
$ > No Result

#### What is the use-case or motivation for changing an existing behavior?
NA

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 4.1.0
Material 2.0.0-beta.3
Chrome OS

#### Is there anything else we should know?
Came up with a solution to not use Regex. [Plunker Link](https://plnkr.co/edit/WCu5yUpiX9CAq87wB1I5?p=preview)
```
filter(name: string): User[] {
     return this.options.filter((s) => s.name.toLowerCase().indexOf(name.toLowerCase()) !== -1);
}
```

**Comment by willshowell** [comment]
I opted for something similar to this:

```ts
filter(val: string): string[] {
  const escapedVal = val.replace(/([.?*+^$[\]\\(){}|-])/g, '\\$1');
  return this.options.filter(option => new RegExp(`^${escapedVal}`, 'gi').test(option)); 
}
```

Perhaps @kara can weigh in on whether or not regex escaping is within the scope of the autocomplete docs.

**Comment by kara** [comment]
The reason the autocomplete in our demo has this default filter is due to accessibility concerns. See https://github.com/angular/material2/issues/3373 for more info. Essentially, it is confusing for users with screenreaders to hear options matching any letter in the word (rather than options that match starting with the first letter). I think it's outside the scope of the docs to explain how to escape particular Regex characters. That's a pretty broad topic that we wouldn't be able to cover sufficiently.
