### ISSUE TITLE
Proposal: $mat-body-font-size-base should be used in mixins from _theming.scss 

### ISSUE THREAD

**Issue by rdinicut** [angular/material2#4458]
#### Bug, feature request, or proposal:

in the build of material, in _theming.scss the value of `$mat-body-font-size-base`  is not used in any mixin and there is no programatic way to change the default font-size value for components. 
These scenario happens for other variables: `$mat-toggle-size` , `$mat-toggle-padding`, etc

#### What is the expected behavior?
You should be able to set the value of $mat-body-font-size-base and the material components should change their font-size based on that value

`@import '~@angular/material/theming';`

`//change default values for variables`
`$mat-body-font-size-base: 12px;`

`@include mat-core();`
`$primary: mat-palette($mat-blue);`
`$accent: mat-palette($mat-amber);`
`$theme: mat-light-theme($primary,$accent);`
`@include angular-material-theme($theme);`

#### What is the use-case or motivation for changing an existing behavior?
A lot of css values are hardcoded in the component style and you should be able to set them programatically

**Comment by kara** [comment]
What you're proposing with font-size sounds like a typography concern, rather than theming. We have an existing plan for changing things like font-size application-wide in the [typography design doc here](https://docs.google.com/document/d/1PK0Whj3buKnnT3-JUwHRJGypgp_y94lssqESVMnJnYk/edit). You can see the upcoming typography change in [this PR](https://github.com/angular/material2/pull/4162).

**Comment by rdinicut** [comment]
@kara $mat-toggle-padding does seem to be to be a typography issue and will still be a problem. It there a plan do have a similar aproach for layout variables?
