### ISSUE TITLE
Use basic css to show autocomplete md-option list instead of a popup with javascript calculating positions.

### ISSUE THREAD

**Issue by sabithpocker** [angular/material2#4477]
#### What is the expected behavior?
What about styling autocomplete `md-list`(dropdown) with CSS relative to the `input` field instead of a pop-up at root of document and list position initialised and updated with javascript? 
One such example is the autocomplete here in [MaterializeCSS](http://materializecss.com/forms.html)

#### What is the current behavior?
Currently items are shown in a modal/pop at root of document detached from the original `input`, and position is calculated with `Javascript`. The updated positions are being recalculated using `scroll` events. 

#### What are the steps to reproduce?
Just check the basic `md-autocomplete` example and Inspect the Element. 

#### What is the use-case or motivation for changing an existing behavior?
1. Let CSS do the positioning instead of Javascript.
2. No need to listen to scroll events as CSS does it automatically as we style it relative to `md-input`
3. Developers can opt to style the drop down list to be either floating above other content(`absolute` positioning) or flow static with other content (`static` positioning) in mobile devices for large lists.
4. Can swap classes to switch between showing drop-down above or below `input`.
5. Can make floating/inline switch using `@media-query`

#### Which versions of Angular, Material, OS, browsers are affected?
    "@angular/core": "^4.1.0",
    "@angular/material": "^2.0.0-beta.3",

#### Is there anything else we should know?
No.

**Comment by epelc** [comment]
I don't believe you can automatically position the autocomplete list above an input depending on screen size/position. If the input is near the bottom of the screen it needs to be able to show the autocomplete list above the input instead of below it.

The closest you could get to this without js would be to use window height media queries. But this doesn't account for the position of the input on your screen so it isn't perfect.

![image](https://cloud.githubusercontent.com/assets/5204642/25962947/9dc45fea-364d-11e7-8d3e-07a717184147.png)
> It does not automatically reposition if you resize the screen while the panel is open. See https://github.com/angular/material2/issues/4093

**Comment by crisbeto** [comment]
While using `absolute` to position the overlay works well with regards to repositioning, it's inconvenient in a lot more cases:
- The panel would be right next to the trigger in the DOM tree. This means that focus can go into it, if there are any focusable elements inside. In order to prevent it, we'd have to manually set `tabindex="-1"` on every single element that is potentially focusable.
-  The trigger would have to be `position: relative`, `position: absolute` or `position: fixed`, which means that we'd either have to ask the user to set it manually or we'd set it automatically. Both of these are unacceptable, because they're either inconvenient or can break the user's layout.
- We'd have to ensure that none of the parents have `overflow: hidden`, which will perform very poorly.

**Comment by jelbourn** [comment]
The infrastructure behind this approach handles repositioning and keeping the overlay on-screen. Attaching it directly to the body prevents clipping when the panel is inside of an `overflow: hidden` container (such as a dialog)

**Comment by sabithpocker** [comment]
Those sounds right! 
@crisbeto  @jelbourn  Thank you for the time and effort to explain these.
