### ISSUE TITLE
Can't select radio-button on same position after update values

### ISSUE THREAD

**Issue by DarkIsDude** [angular/material2#4535]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
Latest publish version

#### What are the steps to reproduce?
http://plnkr.co/edit/oDxXTwXfxvzsi5rtqsPQ?p=preview
Go on the Plunker, choose "Toto", then click on Next and then try to choose "Tutu". You can't...

#### Is there anything else we should know?
It's my first plunker... I hope it's good!

**Comment by donroyco** [comment]
I _think_ it's not a bug, because you use a `md-radio-group` and inside of that, **you use the same** `id` **for all of the items**. 

If you replace the `md-radio-button` line with this ([see this updated Plunker](http://plnkr.co/edit/PWE5CNKLAcBmqKZLlwtu)):
`<md-radio-button *ngFor="let v of value[selected]; let i = index;" value="v" [id]="i">{{ v }}</md-radio-button>` the value 'Tutu' is selectable, because every item is unique.

**Comment by DarkIsDude** [comment]
@donroyco thanks, that's work. Maybe you can explain this in doc?
But I don't understand, my id switch between `toto` and `titi` to become `tutu` and `tata`. So they are overtime unique... But with your code, the id don't change when you click on next... With me, the id change.

**Comment by tinayuangao** [comment]
The problem is you use `value="v"` instead of `[value]="v"` so all the 4 radio buttons have the same value string "v" instead of the value in variable `v`.

See update plunker: http://plnkr.co/edit/0GDHH9wJN0FCFFOYxB9j?p=preview
