### ISSUE TITLE
md-ripple effect ignores border-radius on mobile devices

### ISSUE THREAD

**Issue by simerlec** [angular/material2#4589]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

md-ripple should be contained inside the element with border radius on mobile devices

#### What is the current behavior?

md-ripple works on desktop browsers but behaves as if the parent element (the element which should ripple) is square on mobile devices.

#### What are the steps to reproduce?

Open the following plunkr on a mobile device and click on the card - furthermore the card seems to get bigger on click/touch (not sure if I should open another issue for this?)
http://plnkr.co/edit/Ztu6RU6sXDjS64VHeOyM?p=preview

Thanks

**Comment by willshowell** [comment]
If you're curious about investigating further:
- The ripple not respecting border radius is likely due to [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). I've personally had frustrations getting the stacking order to work consistently across desktop/mobile browsers. Try adding `z-index: 10` to md-card. I don't know if this is something that the ripple should handle automatically, or should be up to the developer...
- The card content has some funky [last child margin adjustments](https://github.com/angular/material2/blob/master/src/lib/card/card.scss#L184-L188) that are probably the cause of the size change (ripple element is appended as last item).

**Comment by simerlec** [comment]
Thanks for the fast response!

It is a stacking issue indeed, which can be fixed using your solution - I tried it on pad as well as smartphone and it works like a charm. It would be nice if the ripple took care of it by itself, sort of like "just add this directive and enjoy the perfect ripples" but as long as it can be fixed with such little effort I'm fine either way.

Considering the card content issue, I'll probably go with a fixed height which prevents the growth.

**Comment by DevVersion** [comment]
I don't think that this should be handled by the ripple service. As I always mention, the ripple service should be as simple as it could be.

Basically I want to avoid issues like in Material 1.x where services / components do too many things under-the-hood and developers won't be flexible anymore.

Also it kinda feels very browser specific what @willshowell said.
