### ISSUE TITLE
Progress circle not working in node env

### ISSUE THREAD

**Issue by kara** [angular/material2#459]
Because it uses `requestAnimationFrame`, it fails in Node (ex: app shell).   We probably need to think about how it's going to work in that context, given that it uses JS in animations now.

**Comment by jelbourn** [comment]
@josephperrott next time you're in 1055, we need to brainstorm a solution that will work in IE11 *and* server-side prerendering (may actually be impossible).

**Comment by jhades** [comment]
Hello all, i noticed this while running issue-zero. For what I could see in Angular Universal the way that this is usually made is via dependency injection? 

It looks like what is being done there is that instead of using the browser API directly, a service gets injected with a given interface. The interface  might be implemented differently across environments. For example the angular universal cookies service -> https://github.com/angular/universal/issues/273
in the browser it uses cookies, on the server it will read from the current HTTP request header.  

Or the HTTP service, in the browser it will use XMLHttpRequest, on the server it will trigger an HTTP route directly.  just mentioning this in the hope that it will avoid large refactorings in the future.

**Comment by jelbourn** [comment]
Tracking via #308
