### ISSUE TITLE
Tabs endless loading loop issue

### ISSUE THREAD

**Issue by seanbotha123** [angular/material2#4639]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Change tabs very quickly, each tab has large amounts of data to process. When switching between tabs too quickly the tabs go into an endless loop of loading.

#### What is the current behavior?
Goes into endless loading loop.

#### What are the steps to reproduce?

[http://plnkr.co/edit/O85thWJeQ0stFAOtojBR](http://plnkr.co/edit/O85thWJeQ0stFAOtojBR)

- open Plunker.
- run.
- click 'Click Me' button/ switch between tabs rapidly.
- loop.

I need to have a ngIf on my components to remove them from the DOM if the tab is not selected. Found the issue where a user was switching tabs quickly and the previous tabs were still loading.

Edit: I see this even happens when not using ngIf. http://plnkr.co/edit/bu2iWvGifGHs95JswBzL

**Comment by jelbourn** [comment]
@andrewseguin looked at the plunker, definitely something weird going on

**Comment by seanbotha123** [comment]
Hi guys,

Any feedback here yet?

**Comment by james-schwartzkopf** [comment]
I believe we are seeing the same issue.  In our case were are trying to store the active tab in ngrx/store.  Things work as expected as long as you switch tabs slowly, but if you change quickly it seems to get stuck in a loop.

It looks like the issue is multiple events piling up in the queue for the async selectChange event emitter?

**Comment by amcdnl** [comment]
Here is a updated plunker - http://plnkr.co/edit/UTgPtgPIKuHScfQKpVFp?p=preview

**Comment by finalxcode** [comment]
mark
