### ISSUE TITLE
[md-button-toggle] checked and class not always in sync

### ISSUE THREAD

**Issue by Lior-G** [angular/material2#4659]
#### What is the expected behavior?
When component md-button-toggle attribute "checked" = true, the class "mat-button-toggle-checked" should be present; regardless of if checked is due to user click or Angular data binding

#### What is the current behavior?
If a component md-button-toggle was set to "checked" = true via Angular data-binding, the class is present.
Then, on user click, it is deactivated; but if immediately re-checked with data binding, the class does not show active.

#### What are the steps to reproduce?

http://plnkr.co/edit/az8kOfiARPJXkvkZrefZ?p=preview

* Click on any non-disabled month
* Click on any other non-disabled month (at least 2 months away)
* At this time, Angular code checks all months in range.
* If click on any non-checked month, and then another month, everything is fine
* If click on a currently checked month, Angular re-checked the component to true. At this time, if inspect with console, we can see ng-reflect-checked="true", but class 'mat-button-toggle-checked' not present.

![screen shot 2017-05-18 at 4 06 04 pm](https://cloud.githubusercontent.com/assets/26391440/26221321/0dd62cc8-3be4-11e7-83d4-9c89af494d61.png)

* if you click on any other month, the range will be checked except the original month clicked.

#### What is the use-case or motivation for changing an existing behavior?
see steps to reproduce above

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.1.0-beta.1
@angular/material: 2.0.0-beta.3
typescript": ~2.3.2

#### Is there anything else we should know?
can't think of anything. Will answer questions on thread

**Comment by tinayuangao** [comment]
The problem is `[checked]="month.active"` and `month.active` is never changed during the actions. In your example, the `checked` value inside button-toggle is changed to `false`, but `month.active` is always `true` so change detection is not triggered and the `set checked = true` in button-toggle is not triggered after click action.

One solution may be change the `month.active` after button-toggle clicked, and trigger change detection manually. 

http://plnkr.co/edit/GX8B6P3MEwPEqGfkcUNw?p=preview
