### ISSUE TITLE
sidenav open/close missing animation

### ISSUE THREAD

**Issue by ocarreterom** [angular/material2#4910]
#### Bug, feature request, or proposal
Bug.

#### What is the expected behavior?
Open/close sidenav with animation.

#### What is the current behavior?
Open/close sidenav without animation.

#### What are the steps to reproduce?
Demo: http://plnkr.co/edit/WSshOLL8dNRjkzyB0Oy8?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/cli: 1.1.0
angular: 4.1.3
angular/material: 2.0.0-beta.6-52b6692
node: 7.9.0
os: darwin x64

**Comment by willshowell** [comment]
Yikes.. looks to have been introduced in #4894 (https://github.com/angular/material2/commit/52b6692472afc6797230e151dfe0563e59c25766)

(bug introduced between https://github.com/angular/material2-builds/commit/7a6b7003803eee45fec0c47a21f8b9c9497d8c6a and https://github.com/angular/material2-builds/commit/f6dc6ce9be904432c0754b78603adde3c4b44351)

cc @DevVersion

**Comment by willshowell** [comment]
It looks like because the inlined styles are comma separated?

https://github.com/angular/material2/blob/master/tools/gulp/packaging/inline-resources.ts#L43

Therefore the [transition styles](https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav.ts#L308-L311) come won't be read due to the comma causing parsing errors.

**Comment by DevVersion** [comment]
@willshowell Thanks for your investigation! I will look into it as soon as possible.
