### ISSUE TITLE
input type number allow any character in Firefox

### ISSUE THREAD

**Issue by robindijkhof** [angular/material2#4941]
#### What is the expected behavior?
With input type number I should see characters like 'aaa'

#### What is the current behavior?
I can type any cahracter

#### What are the steps to reproduce?
https://plnkr.co/edit/Fn3W5yPofeNFtXZCynpW?p=preview

Type 'aa' for example

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material beta-6
Angular 4.1.3
FireFox 53.0.3

**Comment by josephperrott** [comment]
Any character can be typed into the input field in Firefox due to the implementation choice within Firefox.  Firefox allows the entry of the non-number characters but notes it as invalid within the form.

You should be able to prevent the input of non-number characters by listening to events on the input.  `<input type="number" (keypress)="checkIfNumber($event)">`

**Comment by jelbourn** [comment]
[What @josephperrott said.](http://jsbin.com/qijumuyeka/edit?html,output)

**Comment by sadokmtir** [comment]
What he said does not work on mobile devices. That is really awful !!

**Comment by malaydasbob** [comment]
when the type="number" for input, it is enough information to force it to take numeric inputs. And it works perfectly in Chrome. Why do we have to make additional check (checkIfNumber) and do our own validation for firefox? It clearly does not work for firefox and it is a bug and should be registered as a bug and not be closed.

**Comment by Prafful-p** [comment]
Hello 
Any update on this bug
