### ISSUE TITLE
Select overlay in multiple mode needs to extend further

### ISSUE THREAD

**Issue by crisbeto** [angular/material2#4943]
This is based on the discussion from https://github.com/angular/material2/issues/4171: because the left offset of a select in multiple mode is larger, we need to increase the overlay width to allow it to overlap the entire trigger.

**Comment by naveedahmed1** [comment]
@crisbeto is there any update on the issue highlighted by @KevinGruber ? You have mentioned " We do the same on the single-selection md-select" but in my case single-selection md-select is working perfectly I am having this issue with multiple-selection md-select only.

**Comment by crisbeto** [comment]
I'm not completely sure what you mean @naveedahmed1. The multiple select is supposed to extend further to the left in order for the option labels to align with the trigger text.

**Comment by naveedahmed1** [comment]
I am referring to @KevinGruber comment https://github.com/angular/material2/issues/4171#issuecomment-305955498 , I am having exact same issue.

**Comment by crisbeto** [comment]
This should have been fixed and released already. What version of Material are you running?

**Comment by naveedahmed1** [comment]
I am using Angular 4.3.0 and Material 2.0.0-beta.8

**Comment by crisbeto** [comment]
Can you post a Plunkr that shows the issue, because really should've been fixed? You can use this as a base: https://goo.gl/DlHd6U

**Comment by naveedahmed1** [comment]
Please take a look at https://plnkr.co/edit/5B8z8czETUVmwKhyYoat?p=preview I added a container div with padding 15px to the example in docs.

**Comment by crisbeto** [comment]
Are you referring to the fact that the option label doesn't align with the trigger in this case? That's because there isn't enough space on the left to fit the panel without clipping it.

**Comment by naveedahmed1** [comment]
If you notice in plunker the popup menu is shown slightly to the left of the select list probably because of the checkboxes. Shouldn't the width of the options be reduced to accommodate checkboxes instead of increasing width of the list item which as a result moves popup menu to the left.

If I remove the padding from the Div in the plunker, both select with single selection and multiple selection works perfectly.

With padding added to Div, the select with single selection works perfectly whereas multiple selection causes this issue.

**Comment by naveedahmed1** [comment]
@crisbeto I have updated the plunker and added another div with border and without any padding, to give you a more clear idea. https://plnkr.co/edit/5B8z8czETUVmwKhyYoat?p=preview

**Comment by crisbeto** [comment]
I'm still not completely sure what you're referring to. The panel is more to the left on the multiple select, because the select design spec requires for the option label to align with the trigger label. This means that it has to be pulled to the left for a mutli select, because there's a checkbox.

**Comment by naveedahmed1** [comment]
I understand that select design spec requires for the option label to align with the trigger label. But does the same rule applies for multi select as well, where we have checkboxes with each option label? Shouldn't we align the checkboxes with the trigger label in this case instead of aligning option label with trigger label? or may be we could put the checkboxes on the right of the option label?

**Comment by crisbeto** [comment]
The spec doesn't have a particular design for multi-select, but in either case it's supposed to be aligned with the trigger. The checkboxes are on the left per convention and for feature parity with Material 1.
