### ISSUE TITLE
Md-Select cannot set default options when using a Multiple Select

### ISSUE THREAD

**Issue by KyleMcNutt** [angular/material2#4993]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Ideally when the array that you pass into `ngModel` on `md-select` is used in order to select all of the `md-option`'s that match.

#### What is the current behavior?
Currently no options are selected from the array at all.

#### What are the steps to reproduce?
Set `multiple` on your `md-select` and then pass in a subset of the full list of options to the `ngModel` on the `md-select`.

Here is a plunk showing how this behavior doesn't currently work:
http://plnkr.co/edit/aUh0OJUtevRUekcVcovV

#### What is the use-case or motivation for changing an existing behavior?
My use-case would be that I normally use `multiple` with `md-select` but would like to continue to have default values in that form, for cases when a user might be editing pre-existing values.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
N/A

#### Is there anything else we should know?
It's possible that maybe I'm just doing this wrong? But otherwise I couldn't find documentation to support this use case.

**Comment by crisbeto** [comment]
I looked into it @KyleMcNutt. Everything works as expected. Your Plunkr doesn't work, because the items are compared by reference, not by value. Since the value inside the `selectedItems` isn't a part of the `items`, it won't be selected. [Here's a working version of your Plunkr.](http://plnkr.co/edit/gb9ziko0pGDB9ppSCWxN?p=preview) There are a couple of ways to work around it:
1. Ensure that the items and the preselected value are referencing the same object.
2. Select the items by id and map them the their full value before you send them to the server.

**Comment by KyleMcNutt** [comment]
@crisbeto Sure enough, thanks for the help! This behavior should probably be documented somewhere as to avoid this confusion in the future?
