### ISSUE TITLE
Time Picker

### ISSUE THREAD

**Issue by mhmalik** [angular/material2#5224]
#### Bug, feature request, or proposal:
Time Picker is missing, i think it must have that feature

**Comment by Cleudi** [comment]
As this issue was closed immediately - does this mean that a time picker won't be implemented at all?

**Comment by willshowell** [comment]
@Cleudi likely because it doesn't really follow the issue template. There doesn't seem to be an official tracking issue for the timepicker, but this https://github.com/angular/material2/issues/675#issuecomment-298271222 indicates one will be implemented in the future.

**Comment by SteveDunlap13** [comment]
For those looking for a angular5/material2 / latest flex time picker, I banged one out last night for a personal project. Feel free to rip it to your needs. https://github.com/SteveDunlap13/MaterialTimeControl

**Comment by bam-dreymers** [comment]
@SteveDunlap13 - Good timing Steve, just what I was looking for, Thanks!!

**Comment by torabian** [comment]
We have implemented time picker which is compatible with angular material and can be used in different version of angular:
https://github.com/owsolutions/amazing-time-picker

**Comment by NAHaley** [comment]
@SteveDunlap13  that was excellent!  Just what I was looking for.  

Would you have time  to make the class WMatTimePickerComponent implement MatFormFieldControl?

So that it can be wrapped in <mat-form-field></mat-form-field>

I have been working on it using the ideas presented on the Angular site for making a custom control here:
https://material.angular.io/guide/creating-a-custom-form-field-control

I am close, but am running into an Injection problem.

**Comment by alan345** [comment]
Hi @NAHaley, did you manage to get something with custom control for an input type "time" ? thanks

**Comment by Splaktar** [comment]
This is being tracked in https://github.com/angular/material2/issues/5648

**Comment by torabian** [comment]
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.
