### ISSUE TITLE
[Sidenav] - add support for 'backdrop' as optional input

### ISSUE THREAD

**Issue by Lior-G** [angular/material2#5300]
#### Bug, feature request, or proposal:
I would like to suggest to have 'backdrop' as an optional input for Sidenav compoment.
Default would be true for 'mode' = 'over' or 'push', and false for 'side'

#### What is the expected behavior?
if 'backdrop' input is provided, to overwrite the default; and show/hide backdrop accordingly

#### What is the current behavior?
Backdrop exists for 'mode' = 'over' or 'push', and does not exist for 'side'

#### What are the steps to reproduce?
current documentation on Sidenav:
https://material.angular.io/components/sidenav/overview

#### What is the use-case or motivation for changing an existing behavior?
Give user the flexibility to not have 'backdrop' on 'mode' = 'over' or 'push' or do have it on 'side'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "4.2.0-beta.0",
"@angular/material": "^2.0.0-beta.3",
"typescript": "~2.3.2"

#### Is there anything else we should know?
this change would be appreciated

**Comment by Lior-G** [comment]
I noticed this is related (not duplicate) to https://github.com/angular/material2/issues/4482

**Comment by kaylucas** [comment]
I'm looking for the same feature. We're using the sidenav for a mapping application where the sidenav is opening over the map. If the backdrop could be disabled this would give the user the ability to pan/click items on the map while having the sidenav open. Now it's disabling the map usage and users have to click out of it. I could use the 'side' mode but it's not working very well on mobile and it makes the map look strange because it compresses the width.

**Comment by thw0rted** [comment]
This is supported by [the spec](https://material.io/guidelines/patterns/navigation-drawer.html#).  The same sidenav should be usable for "permanent", "persistent", or "temporary" navigation drawers.  Right now the "over" mode works well for "temporary" but I don't see any way to do "persistent", which is what I think @kaylucas is looking for.

**Comment by TobiasVdb** [comment]
+1
