### ISSUE TITLE
MdDialog scroll in another context

### ISSUE THREAD

**Issue by crtl** [angular/material2#5302]
#### feature request, proposal:
I dont want to scroll the `md-dialog-content` but the whole dialog so the scrollbar is outside of the dialog.

#### What is the expected behavior?
Scroll the entire dialog and not only the `md-dialog-content`.
I created a small example with the expected behaviour. You can find it [here on codepen](https://codepen.io/TheM/pen/KqqJEX).

#### What is the current behavior?
`md-dialog-content` is scrolled inside the dialog.

#### What is the use-case or motivation for changing an existing behavior?
The developer should have to decide how the dialog is scrolled to match it with a specific use case.

#### Is there anything else we should know?
I've read in the changelog that there is a new `ScrollStrategy` API to affect the scrolling of overlays but I cannot find any documentation and the `MdDialogConfig` does not support the `scrollStrategy` option.

So it is possible to change the scrolling behaviour for the dialog at the current version?
If so then how?

**Comment by julianobrasil** [comment]
Have you try it without md-dialog-content like said this issue: #5002?

**Comment by crtl** [comment]
Sure, but md-dialog-container has its scrollbar inside the dialog and not outside.
Please look at the example I hope it clarifys what I mean.

**Comment by m98** [comment]
@crtl This repository is for Material 2, for questions related to Angular 1 Material, please [fill issue here](https://github.com/angular/material)

**Comment by crtl** [comment]
@m98 this is not angular 1 related. I just used an Angular 1 example to describe the targeted behaviour.

**Comment by julianobrasil** [comment]
@ctrl, if you put the content outside `<md-dialog-content>`, the dialog do not show any scrollbar inside. The bad news is that it's parent do not show it either.

![image](https://user-images.githubusercontent.com/25405143/27826392-32798308-6089-11e7-97bc-cdacbc0cd9ee.png)

**Comment by m98** [comment]
@julianobrasil Cool! It's almost done :smile: 

it seems to be a bug, or maybe there is an option for this?

**Comment by julianobrasil** [comment]
I think that dialog was not planned to work with large contents _outside md-dialog-content tag_. You can try playing around panelClass (the frame div that contains dialog) to see what do you get. Take a look in this @willshowell comment: https://github.com/angular/material2/issues/3239#issuecomment-311343941

**Comment by m98** [comment]
According to Material design system 

> For scrollable lists of options, the dialog title remains pinned to the top. This ensures that a selected item remains visible with the title, regardless of the item’s position in the list. Otherwise, the title scrolls off with the content. Actions always remain in place when content scrolls.
([source](https://material.io/guidelines/components/dialogs.html#dialogs-behavior))

**Comment by m98** [comment]
@jelbourn If scrollable dialogs are not already planned I can take to do it.
Here is the expected behavior:
![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3bFJtSEZCdlliM1U/components_dialogs_updates8.png)

Maybe the user can activate it by setting a certain attribute, such as `scrollable="true"` then we can check if the content height is longer than the current dialog size, show light scroll for the content, and on the mobile devices user can use gesture to scroll.

**Comment by julianobrasil** [comment]
@m98, scrollable dialog, are planned. You just have to put the content inside <md-dialog-content>:

![image](https://user-images.githubusercontent.com/25405143/27831467-39ecab8e-60a1-11e7-8a46-11aa028186ce.png)


What is not planned is something that looks like the example linked on the issue description (the vertical scrollbar in the backdrop panel instead of in the content part):

![image](https://user-images.githubusercontent.com/25405143/27831530-82be7f22-60a1-11e7-9565-b65369896e53.png)

But I think it can be achieved with the using of backdropClass option.

**Comment by m98** [comment]
@julianobrasil scrolling whole dialog is not what material design system says:

> For scrollable lists of options, the dialog title remains pinned to the top. This ensures that a selected item remains visible with the title, regardless of the item’s position in the list. Otherwise, the title scrolls off with the content. Actions always remain in place when content scrolls.
([source](https://material.io/guidelines/components/dialogs.html#dialogs-behavior))

**Comment by crisbeto** [comment]
There's no plan for allowing the entire dialog to be scrollable out-of-the-box, because it doesn't match the Material spec. If you want scrollable content, you can style the dialog yourself or use `md-dialog-content`. I've been planning on spending some time refactoring the dialog to help with cases like https://github.com/angular/material2/issues/3239.
