### ISSUE TITLE
md-tab without header

### ISSUE THREAD

**Issue by eqbalsajadi** [angular/material2#5529]
To use tab as multi-page component just add following css code:

```
md-tab-group[no-header] > md-tab-header{   
    display:none;
}
```

And add no-header attribute in md-tab-group component

```
<md-tab-group no-header>
...
</md-tab-group>
```

**Comment by eqbalsajadi** [comment]
@donroyco @Chan4077 
Why not!? I'm using this patch to show a wizard form 

for example in this code it is working perfectly:
```
<md-tab-group no-header #tabGroup2>
    <md-tab label="Page1">
        ...
        <button (click)="tabGroup2.selectedIndex=1">Next</button>
    </md-tab>
    <md-tab label="Page2" fxLayout="column">
        ...
        <button (click)="tabGroup2.selectedIndex=0">Back</button>
    </md-tab>
</md-tab-group>
```

**Comment by donroyco** [comment]
@eqbalsajadi There are many other _better_ ways to achieve this kind of functionality. 

Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are stack overflow, gitter, mailing list, etc.

**Comment by eqbalsajadi** [comment]
@donroyco I though this is feature request + solution

anyway sorry for that

**Comment by willshowell** [comment]
@eqbalsajadi Due to the volume of issue reports and limited resources to triage them, the team asks that you follow the issue template when filing a new issue. For feature requests, this means describing in detail the current limitations and your motivation/use-case. A standardized template helps them quickly identify duplicate requests and prioritize fixes and features.

Since you mentioned wizard form, you may be interested in https://github.com/angular/material2/issues/508 where there is already lots of discussion about tab reuse and accessibility concerns.

**Comment by eqbalsajadi** [comment]
@willshowell I got it. i forgot issue label. thank you
