### ISSUE TITLE
How to show other month? [datepicker]

### ISSUE THREAD

**Issue by nguyennk** [angular/material2#5543]
#### Bug, feature request, or proposal:
Question

#### What is the expected behavior?
Show other month days if there is empty field in current month
example: https://jqueryui.com/resources/demos/datepicker/other-months.html

#### What is the current behavior?
blank

#### What are the steps to reproduce?
Just create any datepicker

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular4 + Material Angular IO

**Comment by jelbourn** [comment]
Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are stack overflow, gitter, mailing list, etc.

**Comment by willshowell** [comment]
@jelbourn Though this was posed as a question, I think it's a valid feature request.

The linked datepicker displays days in previous/next months as grayed out, and they are still selectable.

![screen shot 2017-07-07 at 10 18 28 am](https://user-images.githubusercontent.com/6475576/27961785-f1dc7dec-62fd-11e7-87f9-6bda0dfcc9f7.png)

Here is another example from macOS reminders where clicking on one of the prev/next month's days moves back/forward a month.

![screen shot 2017-07-07 at 10 21 18 am](https://user-images.githubusercontent.com/6475576/27961832-163cb83c-62fe-11e7-8daa-53f9bbcd70cc.png)

Of course, this may explicitly be against the spec, with no chance of support. But it would be nice to know for sure since there isn't exactly a public spec for datepickers, beyond the brief note in [full screen dialogs](https://material.io/guidelines/components/dialogs.html#dialogs-full-screen-dialogs)

**Comment by jelbourn** [comment]
Yeah, the spec we're working from (unfortunately still not public) calls for only days from the current month to be shown.

**Comment by lil25** [comment]
Hey guys
Any updates?
