### ISSUE TITLE
Add e2e tests for icons

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#560]

**Comment by jesselpalmer** [comment]
Hey @jelbourn, Do you mind if I take a shot? Or are you already working on this?

**Comment by jelbourn** [comment]
Go ahead, not currently assigned

**Comment by jesselpalmer** [comment]
How would you feel about leaving e2es out for icons since there is no real behavior to test, at least for the time being. It looks like all of the cases are covered via unit testing. Personally, I always try to limit e2es in favor of unit testing since they tend to be slow and flakey. Here is a good article on the subject if you are interested: http://googletesting.blogspot.com/2015/04/just-say-no-to-more-end-to-end-tests.html. If you feel differently I will go ahead and write tests if you would like.

**Comment by jelbourn** [comment]
At the very least there should be some smoke-level e2e tests.

**Comment by jesselpalmer** [comment]
Gotcha
