### ISSUE TITLE
Problem generating a list of cards.

### ISSUE THREAD

**Issue by mangoklie** [angular/material2#5613]
Hello, I have the following problem here: I want to make a list of cards, I design my card everything ok bu when I combine this component with the list the card overlap so I get to see the last one only.

This is the html code I used:

```
<md-list class="sidelist">
  <md-list-item *ngFor="let property of properties">
    <md-card>
      <img md-card-image [src]='property.images[0]'>
      <md-card-title>{{property.id}}</md-card-title>
      <md-card-subtitle>{{property.status}}</md-card-subtitle>
      <md-card-content>{{property.address}}</md-card-content>
    </md-card>
  </md-list-item>
</md-list>
```

I get the same results using both Chrome, and Firefox. 

Am I missing something ?

**Comment by julianobrasil** [comment]
Can you put It in a plunker?

**Comment by julianobrasil** [comment]
@mangoklie , I think you should be using `md-grid-list` (with `cols="1"`), because, according to docs, `md-list` "_wraps and formats a series of line items_". The height of the `md-list-item` is limited, that's why cards are overlaping. Basically any element with enough height (greater than 48px) will overlap. Take a look at the css of the `md-list` https://github.com/angular/material2/blob/master/src/lib/list/list.scss

**Comment by mangoklie** [comment]
I solved it this morning, I put the cards inside a sidenav element  which turned out to be what I wanted. Thanks for your suggestions. @julianobrasil
