### ISSUE TITLE
material\typings\index.metadata.json issue

### ISSUE THREAD

**Issue by RobJacobs** [angular/material2#5642]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
index.metadata,json seems to be missing exports causing angular cli build to throw an error: ERROR in PortalModule is not an NgModule

#### What are the steps to reproduce?
npm install angular/material2-builds angular/cdk-builds and compare the @angular\material\typings\index.metadata.json file with the file generated from the beta8 release: npm install @angular/material @angular/cdk  If I use the index.metadata.json from the beta8 release with the master branch install, my project builds fine.

**Comment by jelbourn** [comment]
This is due to a bug in Angular: https://github.com/angular/angular/issues/17888

We released beta.8 using a version of Angular that has the fix. Until that fix makes it to a release that our build server is using, the material2-builds will have this problem. You can work around it by directly importing symbols like `PortalModule` from `@angular/cdk` instead of their re-export from `@angular/material`.
