### ISSUE TITLE
memory leak Progress spinner

### ISSUE THREAD

**Issue by rudzikdawid** [angular/material2#5676]
#### Bug, feature request, or proposal:
Memery leak, using ``<md-progress-spinner>``

#### What is the current behavior?
![performance](http://i.imgur.com/3SG3KU2.jpg)
![memory alocation timeline](http://i.imgur.com/3LiytYp.jpg)

#### What are the steps to reproduce?
https://material.angular.io/components/progress-spinner/overview
chrome devTool, Performance, record memory profile

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
fedora 25
chrome 59
material 2.0.0-beta.8

**Comment by josephperrott** [comment]
Note: Overall I don't believe this will be an issue as with #6551 we will be moving back to a CSS based solution which eliminates what we are seeing.

From looking at the screenshot provided it appears that the progress spinner is not fully "leaking", but rather it is cycling as the stack builds and clears from on interval.  I believe this is caused by how requestAnimationFrame requires variables to be accessed via closures.  

### You can actually see this doing the following in a chrome devtools:
- Open up the `about:blank` page.
- Start a a recording in the performance tab and then execute:
```js
var keepGoing = true;
function ourTestMethod() {
  if (keepGoing) {
    requestAnimationFrame(ourTestMethod);
  }
}
outTestMethod();
```

- After about 10 seconds flip the value of `keepGoing`
```js
keepGoing = false;
```
- After another 5-10 seconds end the performance measuring.

### The resulting perfomance will look similar to this:
![image](https://user-images.githubusercontent.com/10864441/29879867-2d24ea4c-8d5b-11e7-9cbd-52e3c9024fbe.png)

Even using the about blank page, running no other scripts, not altering any values, nor causing any renderings, we see the same growth cycle of the JS Heap with garbage collection occuring at ~4200ms and ~9200ms clearing the heap.
