### ISSUE TITLE
md-switch: Toggle state with arrow keys

### ISSUE THREAD

**Issue by RemKolomna** [angular/material2#572]
Wouldn't be it good from accessibility point of view to toggle switch state using Arrow Left and Arrow Right keys, just like a slider component?
BTW: It doesn't implemented in Material1, but it feels so natural for mouse hater like me! If it doesn't make sense, feel free to close it.

**Comment by jelbourn** [comment]
I think using the arrow keys here would actually hurt accessibility because they're normally used by the screen reader itself. Do you have any examples of a similar component doing this?

**Comment by RemKolomna** [comment]
Yeah, in Windows Metro UI

**Comment by DevVersion** [comment]
Ah, you mean the Native Metro UI implementation.

![image](https://i.gyazo.com/b1fe39069806f79a2fa099b5bb54f16f.gif)

I don't think we can compare the Native UI with the Web Platform.

I just tested those native switches for Windows 10, and it seems not to be a problem for the `Narrator (not for web)`. With Narrator you change the current control by pressing <kbd>tab</kbd>, instead of the Arrow keys.

**Comment by jelbourn** [comment]
Closing this because I believe it would play well with web browser + screen-reader.
