### ISSUE TITLE
When used in together with md-button-toggle-group setControl function raises error on second call (There is no FormControl instance attached to form control element with path

### ISSUE THREAD

**Issue by Cyberdada** [angular/material2#5720]
#### Bug, feature request, or proposal:

When calling setControl a second time on a FormArray, which is tied to a mdButtonToggleGroup I get the following error:

There is no FormControl instance attached to form control element with path: 'roles -> 1 -> role'

Note: if I switch out the md-button-toggle-group for a md-radio-group, no error is raised.

#### What is the expected behavior?
No error should be raised.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

https://plnkr.co/edit/WAq2GkeNzfQSOcGuzyDr
In the plunker push the topmost editor toggle button.
note that the application works, but I get an ugly error.

#### What is the use-case or motivation for changing an existing behavior?
My understanding is that you should be able to use setControl to reinitiate a formArray without getting an error.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular:    4.2.6
Material:    2.0.0-beta.8
Typescript: 2.4.1

Tested in Chrome  59.0.3071.115
and edge 40.15063.0.0

#### Is there anything else we should know?
I first thought it was an Angular bug,  so bug is first raised there: 
https://github.com/angular/angular/issues/18027

**Comment by willshowell** [comment]
A couple of notes:

1. There's a lot going on in your plunker. When filing issues, it's best to distill it down to the minimum required code (in this case, component logic) that still demos the issue. I've done so here https://plnkr.co/edit/ZOjKolDGVtaB4TnAMadI?p=preview
2. Did you see https://github.com/angular/angular/issues/14057? There's a workaround in the [final comment](https://github.com/angular/angular/issues/14057#issuecomment-308270313) that applies here. Instead of `formControlName="role"`, you can (for some reason) use `[formControl]="formRoles.at(i).controls['role']"`.  Perhaps reading through that issue could be of some help.

**Comment by Cyberdada** [comment]
After upgrading to angular 4.3.6, and material 2.0.0-beta.10 
This bug has disapeared, so closing issue :)
