### ISSUE TITLE
Touch UI for me-datepicker has no effect in mobile.

### ISSUE THREAD

**Issue by JarekToro** [angular/material2#5834]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The date picker calendar should take up more screen real estate when touch ui mode is enabled.

#### What is the current behavior?
Touch ui mode works only in large displays, once you get to the size of a phone. It shrinks back to the regular date picker.

#### What are the steps to reproduce?
You can go on your phone (I have an iPhone7) go the example on https://material.angular.io/components/datepicker/overview. And look at the touch-ui example it doesn’t work. Just reverts back to the regular pop up.

No plunker needed as it’s displayed on the example page.

#### What is the use-case or motivation for changing an existing behavior?
To make it work :)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
What I’ve used
2.0.0 beta8
Angular 4.3.0
iOS safari

**Comment by mmalerba** [comment]
The touch UI does appear to be working, it's just constrained to max of 80% of viewport width & height, which doesn't come out to much bigger than the popup. I can create a PR to bump it a little higher, maybe 90%, 100% wouldn't look good since the calendar would be touching the edge of the viewport

**Comment by JarekToro** [comment]
Perfect!
