### ISSUE TITLE
Planned features for md-table

### ISSUE THREAD

**Issue by AmirTugi** [angular/material2#5882]
I would like to know what features are currently planned for the md-table.
As mentioned [here](https://github.com/angular/material2/issues/581#issuecomment-313548195), it seems to me that there a few features in the spec that are not currently planned:
* Contextual-header (as in [here](https://material.io/guidelines/components/data-tables.html#data-tables-tables-within-cards), under 'alternative headers')
* [Row selection](https://material.io/guidelines/components/data-tables.html#) (along with an overall checkbox to de/select-all)

The latter is rather easy to implement, maybe I'll even help implementing it.
The former, though, I think should be handled by you.

If anyone has more features to propose, maybe raise them here as I haven't seen any discussion regarding this.

**Comment by willshowell** [comment]
Both of those will be included in an docs example soon! https://github.com/angular/material2/issues/5848#issuecomment-316147124

**Comment by andrewseguin** [comment]
I've opened up issues for table features that we'd love to see added, please feel free to open more issues for any features you would like to see and we can discuss on each issue. Closing this since it will be difficult to have a discussion here on each issue.

#5885, #5886, #5887, #5888, #5889, #5890, #5891 

Note that a contextual header will likely be included as part of a simple table but will be highly opinionated. Every project has its own idea of how the header should look and behave, which can be seen even in the Material spec where there are several versions of how it can look. It will unlikely be an official component.

Also, selection is already supported through the [`SelectionModel` ](https://github.com/angular/material2/blob/master/src/lib/core/selection/selection.ts). Check out the example in the PR linked by @willshowell for an example of using it

**Comment by matheo** [comment]
@andrewseguin Any idea why the `md-table` is not refreshing its contents in this case:

I have my table to list my items (`/admin/users` route)
with action buttons to a form (`./create` and `[row.id, 'edit']` routes), all fine.

But when I navigate back, like with a Cancel Button with `routerLink="../"`
the table doesn't load anything, not even the headers and doesn't invoke the DataSource.connect() either. I'm missing something? my component seems to load Ok, but `md-table` needs something here :(

**Comment by benb7760** [comment]
@matheo This is already reported as #5593 and has a PR #5775

**Comment by matheo** [comment]
@benb7760 How sweet, thanks a ton!
