### ISSUE TITLE
Use of MdIcon requires adding HTTP_PROVIDERS to parent component.

### ISSUE THREAD

**Issue by gregbown** [angular/material2#591]
I am using Angular 2 rc1 and Material 2 alpha.5.
After adding an instance of the md-icon-button in my template I got errors:
EXCEPTION: No provider for Http! followed by EXCEPTION: No provider for ConnectionBackend.
Adding HTTP_PROVIDERS to my component in the bootstrap or the providers at the component level resolved the errors however I didn't see this in any of the examples?

**Comment by kara** [comment]
This is in the Getting Started Guide:

https://github.com/angular/material2/blob/master/GETTING_STARTED.md#additional-steps-for-md-icon-setup

Do you think more detail would help?

**Comment by jonathan-casarrubias** [comment]
@kara shouldn't the MdIcon component do that internally? it is kind of odd request to ask the developer that will implement the component to add an http provider for an Icon Component..

Is there a specific reason the end developer should set the HTTP_PROVIDERS when trying to use a simple icon component? I believe is a bad experience. But I want to assume there is a specific reason for this, so I would like to know why if any, so I can explain that when my teams/trainees ask me.

Cheers @jonathan-casarrubias

**Comment by DennisSmolek** [comment]
So for everything beyond the standard material fonts the md-icon's use the `MdIconRegistry` to load from local/remote sources. To do this they `@Injectable` the class and use the official http repo. Because of this it has to be provided for BEFORE calling, either as a viewProvider or during the bootstrap. 

When they call: `constructor(_http:http)` the string "http" has to be registered as a provider, otherwise it doesn't know what "http" is and fails. 

Unfortunately there isn't an easy way to get around that and use the standard DI, maybe call it as a singleton and not through injection? I dont know. Another way might be a "plus" directive, md-icon is relegated to just the icon font and md-icon-plus (or whatever) is what needs the `MdIconRegistry`

**Comment by jelbourn** [comment]
Working as intended for now (within the bounds of what Angular enables). There's currently no real way for a service to bring its dependencies with it.

**Comment by gregbown** [comment]
My apologies @kara. Thank you all.
