### ISSUE TITLE
MdSelect overlapTrigger input parameter

### ISSUE THREAD

**Issue by JaimeStill** [angular/material2#5913]
Proposal.  

`MdSelect` should have an `overlapTrigger` input parameter like `MdMenu`.

Usage:  

``` html
<md-select [overlapTrigger]="false">
    <!-- md-options -->
</md-select>
```  

Something like this:  

![proposed-select-overlay](https://user-images.githubusercontent.com/14102723/28436314-85b16a76-6d64-11e7-9326-58eb8514eca4.png)

**Comment by kara** [comment]
In the case of the select, the Material Design spec is pretty clear that the selected item should always overlap the trigger and not duplicate the selected item (see the "don't" images [here](https://material.io/guidelines/components/menus.html#behavior-figure-caption-4)). Because of that explicit instruction, we aren't likely to add this feature to the select.

**Comment by JaimeStill** [comment]
I understand not having duplicate select items in the overlay itself, but this would be an option that allows for the overlay to always be positioned underneath the select element for smaller lists. The duplication of "Green" in the above example is not a duplication in the overlay list, but rather the currently selected item in the context of the select element.

**Comment by kara** [comment]
@JaimeStill It sounds like perhaps we're looking at different images. This one in the "Dont" section specifically calls out that the overlay should always overlap the trigger.

![image](https://user-images.githubusercontent.com/3871688/28473060-19183072-6df8-11e7-96c9-6ff1b19a6baa.png)
> Don't.
> Menus are positioned over their emitting element.

**Comment by JaimeStill** [comment]
Thank you for your time and consideration @kara.
