### ISSUE TITLE
SnackBar without duration doesn't show

### ISSUE THREAD

**Issue by etiennecrb** [angular/material2#6222]
#### Bug, feature request, or proposal:
Bug in MdSnackBarModule with the following simple code:
```typescript
this.snackBar.open('hello');
setTimeout(() => {
   this.snackBar.open('world');
}, 2000);
```

#### What is the expected behavior?
A snackBar with "hello" should be opened, 2 seconds later it should be dismissed and a snackBar with "world" should be opened.

#### What is the current behavior?
A snackBar with "hello" is opened, 2 seconds later it is dismissed and **the snackBar with "world" doesn't appear**.

#### What are the steps to reproduce?
[Demo](https://plnkr.co/edit/vaM6mbPW2SGyvcalgOMa?p=preview)

Weirdly, it works if I define a duration for the "world" snackBar: [demo](https://plnkr.co/edit/n5Lrfdwy9eA5ft12VUXp?p=preview).

#### What is the use-case or motivation for changing an existing behavior?
It's not consistent to have to define a duration in some cases, not in others.

**Comment by pfeigl** [comment]
I'm seeing the same problem. Looking at https://github.com/angular/material2/blob/master/src/lib/snack-bar/snack-bar.ts#L83 it seems like the intentional behavior would be to close the open one and once the closing animation is done, open up the new snackbar.

Effectively this doesn't seem to work as expected. 

Could it be connected to this change https://github.com/angular/material2/commit/2732bb4fbb953b3778b9b7de6d592fa861b9644d ?
