### ISSUE TITLE
[Bug] Textarea, ReactiveForms display:none, text in textarea not appears

### ISSUE THREAD

**Issue by NoMoreLoad** [angular/material2#6268]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I hide textarea with display:none class while fetching data from API and showing it, when it will complete, I've expect to see control with filled text, that was fetched from API.

#### What is the current behavior?
Control is displaying, but it's text is empty. But if you try to type something - text will appears. It only happens with display:none. With visability: hidden it works as expected.

#### What are the steps to reproduce?

https://embed.plnkr.co/qd7k7F/

#### What is the use-case or motivation for changing an existing behavior?
visability:hidden did not free space, that object takes in DOM, but display:none did.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/cli: 1.2.7
angular: 4.3.3
angular/material: 2.0.0-beta.8
angular/cdk: 2.0.0-beta.8
node: 8.2.1
os: 10 x64
TypeScript: 2.4.2 in project where bug was found (with strict: true), 2.2.1 in plunkr with default settings

#### Is there anything else we should know?
Sorry for my English)

**Comment by mmalerba** [comment]
This appears to be a result of the `mdTextareaAutosize` getting incorrect measurements due to the fact that you're hiding the textarea with `display: none`. Is there a reason you can't just use `ngIf` for this? (e.g. https://plnkr.co/edit/LxfczxmIFB8UDnc5AcQP?p=preview) If not possible then try hiding via visibility hidden and pushing off-screen instead

**Comment by AhmedHasnaoui** [comment]
I have a similar issue on beta 8, setting text of my textarea in a reactive form.
When the component is rendered the text area seems to be empty but if you type something the text area shows the text and grows to the correct size.
I tried fixing this using resizeToFitContent() after view init, but there is no effect...is this fixed in a newer version?
