### ISSUE TITLE
Enter key events in input elements affect unrelated buttons

### ISSUE THREAD

**Issue by nikclayton** [angular/material2#6301]
#### Bug

Have a `<button>` with a `(click)` handler set. Have an `<input>` element nearby. Press `ENTER` in the `<input>` element and observe that the button's `(click)` handler gets called as well.

#### What is the expected behavior?

The `(click)` handler should not be called.

#### What is the current behavior?

The `(click)` handler is called.

#### What are the steps to reproduce?

I've put three examples at http://embed.plnkr.co/7DhGuQH2zC76RpX2geGH/.

The first form shows the problem.

The second form demonstrates that the problem is in Angular Material2, as it does not appear if you don't use the Angular Material form components.

The third form demonstrates that replacing `(click)` with `(mouseup)` works around the problem.

#### What is the use-case or motivation for changing an existing behavior?

The existing behaviour appears to be a bug -- events in one control should not affect controls that it is not wrapped by.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

The code versions are identical to the one in the default Plunker template:

* OS: Ubuntu 14.04
* Browser: Chrome 60.0.3112.78 (Official Build) (64-bit)

**Comment by crisbeto** [comment]
Material doesn't attach any keyboard handlers that would do this. Your first two examples behave that way, because you have a button inside a form which defaults to `type="submit"`. If you want to prevent that behavior, you can add `type="button"` to the buttons. The second example doesn't exhibit the same behavior, because you're attaching the click handler to a span, if you switched it to a button, it behaves the same. [Here's a forked Plunkr where I switched out the span with a button.](https://plnkr.co/edit/GgHMkTpKa9kBjhgL5RXp?p=preview)
