### ISSUE TITLE
Align TemplatePortal with ComponentPortal and support context in TemplateRef Dialogs

### ISSUE THREAD

**Issue by shlomiassaf** [angular/material2#6310]
#### What is the expected behavior?
`TemplatePortal` should accept a context which then allows using the `MdDialogConfig.data` as context for a dialog opened using a `TemplateRef`.

#### What is the current behavior?
`TemplatePortal` does no accepts context.
It does accept `locals` but these were added within the first commit and never used.

#### What is the use-case or motivation for changing an existing behavior?
There are several...

First, `TemplatePortal` is not aligned with `ComponentPortal`. Since both provide the same logical functionality it makes sense to return the same logical object: `ComponentRef`, `EmbeddedViewRef`. In addition, `TemplatePortal` does not allow sending data (context) to the template. There is a place holder (`locals`) property but it is never used. `TemplatePortal` is not responsible for the structure of the context so `locals` as `Map<string, any>` is not a proper type, instead a generic type is more suited. The consumer of `TemplatePortal` should decide about the structure (e.g. using `$implicit`? what local to expose etc...)

Once `TemplatePortal` support context, `MdDialog` can provide same experience for both **Component** based dialogs and `TemplateRef` based dialogs.

`MdDialog` will auto crete the context have the `MdDialogConfig.data` as `$implicit` and an extra property `dialogRef` exposed (which holds `MdDialogRef`).

This create a powerful combination of a template that has access to injected data (context) and local template variables of its **parent** template.  
It allows passing template references throughout the application with the ability to have data injected. It's a more declarative approach with a lot of power.

For example, using the `demo-app` code, **without changing TS code** we can provide the same functionality (almost) that the **demo-jazz-dialog** component provide just by changing the html only.

```html
<ng-template let-data let-dialogRef="dialogRef">
  I'm a template dialog. I've been opened {{numTemplateOpens}} times!

  <p>It's Jazz!</p>

  <md-input-container>
    <input mdInput placeholder="How much?" #howMuch>
  </md-input-container>

  <p> {{ data.message }} </p>
  <button type="button" (click)="dialogRef.close(lastCloseResult = howMuch.value)">Close dialog</button>
  <button (click)="dialogRef.updateSize('500px', '500px').updatePosition({ top: '25px', left: '25px' });">Change dimensions</button>`
</ng-template>
```

This template uses bindings from 3 sources, the context, local template variables of the parent component and the component instance itself.

With simple structured directives it will be possible to create template driven UI blockers, modal etc... that accepts data and are set elsewhere.

 I'v started to work on this change, [see the diff](https://github.com/angular/material2/compare/master...shlomiassaf:refactor-TemplatePortal?expand=1)

The change is not big but having TemplatePortal now with a generic required some mods, and it's also a breaking change so it's needs discussion.

Please comment.

cc @jelbourn 
Thanks.

**Comment by jelbourn** [comment]
Yeah, this was the original intent, but it was never fleshed out since we didn't run into a feature that needed it and eventually it was forgotten. Happy to accept a PR.

**Comment by shlomiassaf** [comment]
@jelbourn I have [something ready](https://github.com/angular/material2/compare/master...shlomiassaf:refactor-TemplatePortal?expand=1)

Before I move on, I would like to get some feedback on the API.

### TemplatePortal / BasePortal and friends:

> Tried to keep API changes to minimal, since its a "low level construct" it will only accept a context and does not care for it's content.

  - `TemplatePortal` becomes `TemplatePortal<C>`
  -  User of `TemplatePortal` will provide the context and weather to set `$implicit` or not.
  - ` abstract attachTemplatePortal(portal: TemplatePortal): Map<string, any>;` will not return `EmbeddedViewRef<C>;` (and of course all implementors)
  - `locals` is removed from `TemplatePortal`, `context` is added instead. It will be used for both locals and implicit per user design.
  - `TemplatePortal` constructor now accepts a 3rd parameter, context, which is **optional**.


### Dialog:
> Try to provide same experience when using a component and a `TemplateRef`

  - `MdDialogContainer.attachTemplatePortal` is now generic and returns `EmbeddedViewRef<C>`
  - `MdDialog` handles `TemplateRef` dialogs a bit different: 
  `dialogContainer.attachTemplatePortal(new TemplatePortal<T>(componentOrTemplateRef, null!, <any>{ $implicit: config.data, dialogRef }));` It sets the data as the default context and the dialog ref as a specific local variable template. 

Dialog will not allow setting locals, this is to create same behaviour with component approach and also because it complicates the API and type support.

Template can access the context like this: `<ng-template let-data let-dialogRef="dialogRef">`

Please share your comments before I move on.

Thanks.

**Comment by simeyla** [comment]
Hi @shlomiassaf. I'm late to the commenting here, but would love your input on the following omission in the API.

The more commonly used `[ngTemplateOutlet]` directive has `ngTemplateOutletContext` that passes through a context to its template. Is there a reason why the `cdkPortalOutlet` directive does not have an equivalent property?

I have several template of 'expensive' content, which includes videos and images. I have created a responsive design manager that moves this content around based upon the screen width. Portal is perfect because I don't have to regenerate the content every time. So I want to display my template in a `cdkPortalOutlet`, but it needs a 'context' to provides it with 'responsive parameters'. (For simplicity lets just say this is the width the image should be displayed as).

So I capture my content into a `cdkPortal` [(as shown here)](https://stackoverflow.com/questions/51803125/angular-cdkportaloutlet-to-set-context-on-an-embedded-template-view) but then I just don't see an easy way to provide it with the contextual data it needs since there is no `context` parameter.

An important goal of mine is not to regenerate the DOM nodes when the context changes. The way `ngTemplateOutlet` behaves is to only regenerate the view when the 'shape' of the context changes. So this would allow me to update the parameters and have them passed through.

But maybe this isn't what 'context' should be used for in the first place - and I should be injecting a simple service?

In any case very curious why the `cdkPortalOutlet` directive ([current source here](https://github.com/angular/material2/blob/master/src/cdk/portal/portal-directives.ts)) doesn't have a `cdkPortalOutletContext` parameter?
