### ISSUE TITLE
md-select : selected value doesn't change after md-option text is changed using fxHide

### ISSUE THREAD

**Issue by dhuallanca** [angular/material2#6353]
#### Bug, feature request, or proposal:

Bug
#### What is the expected behavior?
Selected value should change according to md-option values.
Whether md-option is updated selected value should change

#### What is the current behavior?
Selected value doesn't change the value after fxHide is called and md-option values are changed 

#### What are the steps to reproduce?
1. Open a browser 
2. Change the size of the browser to (lt-md) 
3. md-option should hide some information in responsive (lt-md)

https://plnkr.co/edit/L5XWZW7ew4gym47nPHaZ?p=preview

#### What is the use-case or motivation for changing an existing behavior?
For responsive design, I need to hide some elements in mdoptions.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular": "^4.3.3",
    "@angular/flex-layout": "2.0.0-beta.8",
    "@angular/material": "^2.0.0-beta.8",

#### Is there anything else we should know?
For responsive design I hide an element (food.value) in md-option, however the selected value doesn't refresh the change in md-option

**Comment by BobBDE** [comment]
Well not sure that's possible, because the selected value comes from the object put in the attribut "value" of the md-option. In your plunkr you have :  [value]="food.value", so the food.value will be assign to "selectedValue" whether you are in a small screen or not. 
To solve your problem you could whether : 
- create 2 "p" tag in to show the "selectedValue" with a Fx condition
- have 2 set of md-option with an ngIf condition on the screen size (not sure if the fxHide just hide the value or delete it from the DOM)

**Comment by willshowell** [comment]
The viewValue of the trigger is calculated from this

```ts
  // option.ts
  get viewValue(): string {
    return (this._getHostElement().textContent || '').trim();
  }
```

And since fxHide doesn't actually remove the text from the DOM, it is still read as a part of `textContent`. To customize the trigger display value,  https://github.com/angular/material2/pull/3341 will be merged soon.

**Comment by dhuallanca** [comment]
the problem is solved using md-select-trigger.
