### ISSUE TITLE
Update documentation to remind devs to include MdIconModule please?

### ISSUE THREAD

**Issue by pchristou** [angular/material2#6413]
Please could Step 6 of the <a href="https://material.angular.io/guide/getting-started">Material Documentation<a> include the fact that you need to include the MdIconModule? This slipped me up for an hour and I think it'd slip many others up too. 

Thanks!

**Comment by julianobrasil** [comment]
@pchristou , the step 3 already says you have to "_Import the NgModule for each component you want to use_".

**Comment by julianobrasil** [comment]
At the docs site, in the api tab of each component, you will find the `NgModule` name you have to import, at the top, like:

`import {MdRadioModule} from '@angular/material'`

**Comment by pchristou** [comment]
@julianobrasil fair point but if purely following the tutorial, it's not clear that the icons even have a module, especially when reading step 6. If folk disagree then that's fine but I'm simply sharing my experience and suggesting what I think would be an improvement. 

If it slipped me up, I'm sure there'll be at least a handful of others who had the same issue. For instance: https://stackoverflow.com/a/44079085/479619

**Comment by julianobrasil** [comment]
Well, I'm not sure whether the getting started section is intended to be a more detailed guide on any specific component than it already is (also not saying that your point wouldn't make the getting started more clear). Maybe someone from the material team can tell better whether it should or should not be more specific about `mdIcons` in setp 6 of the guide.

**Comment by jelbourn** [comment]
@pchristou feel free to send a PR that turns `md-icon` in the getting started guide a link to https://material.angular.io/components/icon/api. Other than that I don't think other changes are necessary

**Comment by fpolig01** [comment]
Just want to add that this tripped me up as well. It seemed the the icons were something separate.

**Comment by misaunde** [comment]
From observing this thread, it appears clear this is not a problem for **members** or **contributors**.
They understood perfectly MdIconModule must be included even though it wasn't explicit mentioned in the setup guide.

It's also clear that the people confused by this issue are new users of the library (the people the setup guide was actually written for). Due to the fact that the icons differ in such a way that they require a link to be added to index.html, I believe this is what led myself and others to conclude that the icons were different and in fact completed with this step. Why wouldn't you add the extra line to remind people new to this library and your way of doing things to add MdIconModule in their module?

Just a couple more examples:
https://github.com/angular/material2/issues/5863
https://github.com/angular/material2/issues/7948
