### ISSUE TITLE
datepicker input cannot change day with 

### ISSUE THREAD

**Issue by davidrensh** [angular/material2#6418]
#### Bug, feature request, or proposal:
datepicker input cannot change day.

#### What is the expected behavior?
It should allow the end user change date in input box. Not calendar only

#### What is the current behavior?
datepicker input cannot change day. It happens when you work with  [(ngModel)]="startDate" (ngModelChange)="startDateChange($event)". it will show null on console with plunker

#### What are the steps to reproduce?

Plunker: [https://plnkr.co/edit/XJkfze8c0V7MtigKRLV6?p=preview](https://plnkr.co/edit/XJkfze8c0V7MtigKRLV6?p=preview)
step 1. select any date in calendar
step 2. change day to value higher than 12 (13,14..)
step 3. console will show startdatechange e  null null

**Comment by julianobrasil** [comment]
It happens because you probably is in a region that use date format like **dd/mm**/yyyy. Without any custom `DateAdapter` implementation, the datepicker expect a date formated like **mm/dd**/yyyy. So there's no month above 12.

See this plunker with a custom `DateAdapter` configured to a language (Portuguese) that works with dd/mm/yyyy: https://plnkr.co/edit/FlgGpjqyDlypas0VZJzo?p=preview

**Comment by mmalerba** [comment]
Yep, as @julianobrasil stated you will need a custom `DateAdapter` for now. We have some issues filed to improve the situation: #6030, #5972
