### ISSUE TITLE
How to update version material?

### ISSUE THREAD

**Issue by arisbro8** [angular/material2#6596]

**Comment by Chan4077** [comment]
@arisbro8 What do you mean?

**Comment by arisbro8** [comment]
my version material is 2.0.0-beta.1 
how to update version to material: 2.0.0-beta.8

**Comment by Nodarii** [comment]
@arisbro8,
Here is [getting-started guide](https://github.com/angular/material2/blob/master/guides/getting-started.md)
You can run `npm install --save @angular/material @angular/cdk` to install latest stable version
And run `npm install --save angular/material2-builds angular/cdk-builds` to install "nightly-builds" (non stable)

**Comment by Chan4077** [comment]
@arisbro8 As what @Nodarii mentioned, I would also like to include that you also have to do the following:
1. Since Angular Material no longer supports Angular 2.X versions, update your dependencies using this command:
```bash
npm update
```
2. Also, install `@angular/animations` which has been separated from `@angular/core` from Angular 4 onwards, along with `@angular/cdk`.
```bash
npm i --save @angular/{animations,cdk} # This is a way to install multiple dependencies
```
For more info, refer to the [Getting started guide](https://material.angular.io/guide/getting-started). (By the way, I'm assuming that you use `npm` for your app.)

**Comment by tytskyi** [comment]
@arisbro8 Also see https://github.com/angular/material2/blob/master/CHANGELOG.md

There are breaking changes since version you have.

**Comment by arisbro8** [comment]
@Chan4077 @Nodarii @tytskyi my problem now is 

`WARNING in ./~/@angular/cdk/@angular/cdk/a11y.es5.js
662:39-53 "export 'InjectionToken' was not found in '@angular/core'`
and
`WARNING in ./~/@angular/cdk/@angular/cdk/table.es5.js
326:12-21 "export 'Renderer2' was not found in '@angular/core'`

**Comment by tytskyi** [comment]
@arisbro8 because latest material does not support Angular2, see `CHANGELOG.md` for details and what versions are supported

**Comment by Chan4077** [comment]
@arisbro8 Try running this command to install all required dependencies:
```bash
npm i --save @angular/{animations,cdk,common,core,material,platform-browser,platform-browser-dynamic}
npm i -D @angular/compiler-cli
```

**Comment by kara** [comment]
Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are stack overflow, gitter, mailing list, etc.

**Comment by arisbro8** [comment]
@kara @Chan4077 @tytskyi @Nodarii 
Thank you very much
