### ISSUE TITLE
 Need first and last page button in paginator

### ISSUE THREAD

**Issue by davidrensh** [angular/material2#6665]
#### Bug, feature request, or proposal:
proposal: need first and last page button |<  >| beside next previous button. It should be |< < > >|
It can be configurable if developer want to turn off ??

#### What is the current behavior?
No such thing

**Comment by jelbourn** [comment]
[Our paginator is based on the Material Design spec](https://material.io/guidelines/components/data-tables.html#data-tables-tables-within-cards), which doesn't have the extra buttons. 

We generally expect that people will mostly make a custom paginator specific to their apps (since there is actually no coupling between the table, data source, or the paginator).

**Comment by dhniels** [comment]
Is there a reason why the design spec leaves this out? It seems like it would be good to at least have the option. I know for our application, it would be a positive improvement UX-wise for our users.

**Comment by andrewseguin** [comment]
@dhniels You'll be happy to know that the next release will contain this functionality. We had an external contributor @lharries develop the functionality in this PR https://github.com/angular/material2/pull/9603
