### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by jakpaw** [angular/material2#6688]
When is the next release planned? It's been 2 months since the last one and not all changes are available in https://github.com/angular/material2-builds.

**Comment by DevVersion** [comment]
@jakpaw What is missing the `material2-builds`?

**Comment by jakpaw** [comment]
@DevVersion For example this commit: https://github.com/angular/material2/commit/8bb54ca4565a7d55d4f74ca0af4c8e7e02efb462

**Comment by DevVersion** [comment]
@jakpaw That's interesting. Those gaps in the `material2-builds` repository might be caused by various CI flakes. Anyway you should be still able to get 8bb54ca installed by just using the HEAD of `material2-builds`.

But I suppose you want to install a specific commit (e.g 8bb54ca) of the builds right?

**Comment by jakpaw** [comment]
@DevVersion Yes, it would be best if I could install a specific commit. I think I tried to install HEAD of `material2-builds` and the changes still weren't there, but I'm going to check again.

**Comment by rafaelss95** [comment]
@DevVersion still about the next release(s), I want to suggest(request) something here...

In many libs/frameworks there's a section in `CHANGELOG` of non-released changes. Can we have the same here?

I think it could help a lot... for us (who use the material2 to know what will be changed in the next version) and (maybe) up to you because you could write the changes gradually.

See this [example](https://github.com/collectiveidea/audited/blob/master/CHANGELOG.md).

**Comment by jelbourn** [comment]
Released beta.10 today. So far we've been doing one beta release per calendar month (albeit cutting it close for August). They'll be more frequent going forward. 

As for changelog, we generate them from the commit messages. GitHub can show you all of the commits from a release, e.g.:
https://github.com/angular/material2/compare/2.0.0-beta.8...master
