### ISSUE TITLE
md-select default value is not support object?

### ISSUE THREAD

**Issue by wizardnet972** [angular/material2#6724]
#### Bug, feature request, or proposal:
I want to display selected value in md-select, the value is an Object. not string.

#### What is the expected behavior?
to display the correct option from the select.

#### What is the current behavior?
not display. 
in the plunker should be: "United States"  at the begging.

#### What are the steps to reproduce?
here:
https://plnkr.co/edit/nCJLd5?p=preview

**Comment by donroyco** [comment]
This is not a bug. Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are [stack overflow](https://stackoverflow.com/questions/44596888/set-default-value-on-md-select-when-value-is-an-object-angular4-angular-material), gitter, mailing list, etc.

**Comment by alex321** [comment]
As pointed out by @donroyco, this is not a bug. Even though the `Object` you passed to `selectedCountry` looks like `countries[1]`, they are different objects so the select wouldn't know which option to display.

In order to select any of the options, you have to select one of the objects you passed to the select, i.e. an `Object` from the `countries` list. Here's an updated plunker: https://plnkr.co/edit/GmlISyGT3BSBWxAryEiD?p=preview

**Comment by willshowell** [comment]
You can now pass a `compareWith` function to MdSelect. See https://material.angular.io/components/select/api

**Comment by wizardnet972** [comment]
@willshowell YEAH!!! U R D BEST! :)
