### ISSUE TITLE
Text inside Tabs is blurry in IE11

### ISSUE THREAD

**Issue by jsspider** [angular/material2#6944]
#### Bug, feature request, or proposal:
Bug.
#### What is the expected behavior?
Text should not be blurry.

#### What is the current behavior?
Text is blurry.

#### What are the steps to reproduce?
Can be seen on the material component page.
https://material.angular.io/components/tabs/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Windows, IE11

#### Is there anything else we should know?
Is probably caused by the transform: translate3d(0%, 0px, 0px) style rule on .mat-tab-body-content element.
Was not present in beta.8

**Comment by julianobrasil** [comment]
It's slightly blurred (not sure if the blurring is visible in the pictures bellow because of images resolution).

Chrome:
![image](https://user-images.githubusercontent.com/25405143/30217808-a78976b6-948d-11e7-9054-3a229675bfe5.png)

IE11:
![image](https://user-images.githubusercontent.com/25405143/30217790-97ac75f4-948d-11e7-9390-f81b3b6ff0d5.png)
