### ISSUE TITLE
bug(drawer): mat-sidenav-opened/mat-drawer-opened not set when open

### ISSUE THREAD

**Issue by karlhaas** [angular/material2#7043]
#### Bug:
mat-sidenav-opened/mat-drawer-opened not set when open after upgrade to latest release

#### What is the expected behavior?
CSS class mat-drawer-opened set when sidenav is open

#### What is the current behavior?
CSS class mat-drawer-opened not set

#### What are the steps to reproduce?
https://material.angular.io/components/sidenav/examples

#### What is the use-case or motivation for changing an existing behavior?
that's the question :)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.6
Material/CDK: 2.0.0-beta.10 and material2-builds.git#32daeb981986c3f925ac59a58cd95023f971b431

**Comment by willshowell** [comment]
It looks like `.mat-drawer-opened` is set on the `md-sidenav-container` when the sidenav mode is set to "over" or "push". It does not get added with "side" mode.

**Comment by demiro** [comment]
To me it happens the same when I have the <md-sidenav-container fullscreen> in app-component
and then the sidenav in another... it doesn't get triggered.... how can I do it programatically?

**Comment by josephperrott** [comment]
I believe this is working as intended.  As @willshowell mentioned, `.mat-drawer-opened` is only added in `over` and `push` modes.  As you can see [here](https://github.com/angular/material2/blob/master/src/lib/sidenav/drawer.ts#L455), it is watched for if `mode !== 'side'`.

If you are seeing different can you provide a plunker showing the issue you are seeing?  I am not quite sure I follow what you are seeing.

**Comment by willshowell** [comment]
@josephperrott I could have sworn this was a regression, but just looked through the blame and it does seem this behavior has been in place for >1 year.

That said, there is specific effort in the drawer class logic to prevent `.mat-drawer-opened` from getting added to the drawer when in `'side'` mode, but as you can see, the effect is blocked in the CSS anyway. Perhaps this issue can be repurposed to having `.mat-drawer-opened` always be added to open drawers, as that would be the expected behavior without having to dive into the source.

https://github.com/angular/material2/blob/3571f68a2de0833ee4741af8a0eb24d1da174f38/src/lib/sidenav/drawer.scss#L114-L120



Note, it is used in one other instance, but could easily be blocked in CSS too if necessary:


<details>
<summary>Source</summary>

https://github.com/angular/material2/blob/3571f68a2de0833ee4741af8a0eb24d1da174f38/src/lib/sidenav/drawer.scss#L39-L46

</details>

**Comment by snapnurse-joshuamatthews** [comment]
@josephperrott  I am not seeing the class being added in beta 12. Seems related to the nav container and the nav element being housed in different components.

**Comment by snapnurse-joshuamatthews** [comment]
I got mine working. The issue is transclusion. Because the sidenav takes all content after the sidenav element and turns it into the sidenav-content element, and because I had a <ng-content> inside of the sidenav container, it was wiring up all of the content as the sidenav-content and not seeing the <mat-sidenav> that is the first element in the transclusion. Maybe this is something that can be fixed?

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
