### ISSUE TITLE
The mat-elevation mixin should include z-index

### ISSUE THREAD

**Issue by viridium** [angular/material2#7088]
When using mat-elevation, we get correct shadows, but not z-index. For that, it would seem we're on our own. Can the mixin include reasonable z-index values?

**Comment by josephperrott** [comment]
I agree it would be great if we could do this conceptually.  We do not do this because not all components live in the same stacking context as they have different ancestor paths, the `z-index` values would not appear to be consistently respected.

**Comment by viridium** [comment]
I guess you're right. If the root context has two components with elevations X and X+1, and the component with elevation X is its own context with a child with relative elevation Y (>1), then how does one make the components appear correctly stacked as: X+Y, X+1, X.

**Comment by mhebrard** [comment]
I guess that is a problem of implementation.
see [stackBlitz](https://stackblitz.com/edit/angular-material2-issue-qdfzxx)
clone of Material Design / [Measuring elevation](https://material.io/design/environment/elevation.html#elevation-in-material-designl)

Conceptually, the div A and C are both at z-index 8dp. but if I use `mat-elevation-z8` then the elevation are wrong.
That is because mat-elevation expect the relative elevation instead of displaying the comprehensive z-index...

That is sad to dump the calculation to the developer...
