### ISSUE TITLE
Angular Material2 - Roadmap

### ISSUE THREAD

**Issue by agaurav** [angular/material2#710]
#### Proposal:
As per [milestone](https://github.com/angular/material2/milestones) & [google group threads](https://groups.google.com/forum/#!searchin/angular-material2/roadmap/angular-material2/IKwThcSp3hU/BhddsuNzBQAJ) , it seems this project is currently lagging bit behind. Also  https://github.com/angular/material2/issues/11 has been closed but there is still a structured roadmap & devlopment guide missing.

Given that angular2 is close to production release it will be really great if we can have some estimates on when to expect a beta version, the estimate on respective design docs seems to be not updated recently.

Going through google group threads and other forums I think the angular2 community will really appreciate the following:

- Better project organization and pace with explicit roadmap and deadlines (Atleast for when should we expect the apis to be frozen for the essential components)

- If possible then involve others from the community toward contributing (Even a very brief development wiki on the internal working & wiring of the framework will be a real help).

**Comment by DerekTBrown** [comment]
+1

**Comment by roughsoft** [comment]
+1

**Comment by JanickRoss** [comment]
+1

**Comment by jelbourn** [comment]
alpha.6 is slightly delayed due to some unforeseen work that came up over the last couple of weeks. Situations like this are exactly why we aren't able to commit to a more specific date. We announced at ng-conf that we're aiming at a beta for this year, but promising something more than that will potentially just disappoint everyone if it is delayed. The milestones will be updated next week when we meet again and reschedule the delayed work. 

As far as contributing, we're very open to contributions, and there have been quite a few PRs from community members. Check out our [contributing guide](https://github.com/angular/material2/blob/master/CONTRIBUTING.md) and [dev environment guide](https://github.com/angular/material2/blob/master/DEV_ENVIRONMENT.md).

**Comment by zigzag95** [comment]
@jelbourn are you planning to upgrade to last angular rc in alpha.6?

**Comment by jelbourn** [comment]
@zigzag95 Yes, sometime next week

**Comment by agaurav** [comment]
Delays are part of all projects and but having specific dates help others plan accordingly with a slack for tham as well as push admin to try hard once they are crossed. As for contributions, a brief guide on usage of the core libs would have been very helpful though now I am going through the source, the code comments are very well written.

A beta by end of the year will fit my migration plans for angular 2 well, thanks.

**Comment by DerekTBrown** [comment]
Have to agree- this project is not contributor friendly.  I would love to contribute to various components within this project, but I am continually told these components have already been assigned to other people, who are not visibly working on the project.  Canonical example:

https://github.com/angular/material2/issues/45

**Comment by fxck** [comment]
+1 ! 

I'd really appreciate something similar to angular weekly meeting notes, to give us a weekly update on what's actually going on.
