### ISSUE TITLE
MdSort not firing mdSortChange when md-table loaded from inside ng-container

### ISSUE THREAD

**Issue by jloosli** [angular/material2#7155]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Table with sorting example runs like in https://material.angular.io/components/table/overview#sorting

#### What is the current behavior?
When loading the table via ng-container, `mdSort.mdSortChange` isn't firing an event, so no sorting happens.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U
See: https://plnkr.co/edit/8QvJZHpk5rp98Sxi0VQv?p=preview

This is based on the Plunker from the docs, but wrapping the table with a ng-template and passing the data via the context. 

#### What is the use-case or motivation for changing an existing behavior?

I have a few instances where I have essentially two versions of the same table on the page (archived vs. non-archived). By using ng-template and adjusting the dataset via the context, I can keep one copy of the table in the template, but use it in two different places.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.5.0-beta.0
node: 6.11.3
os: linux x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/service-worker: 1.0.0-beta.16
@angular/cli: 1.5.0-beta.0
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
typescript: 2.5.2

#### Is there anything else we should know?
That covers it.

**Comment by josephperrott** [comment]
This is working as expected because the `mdSort` attribute is not a `ViewChild` as it lives within the `<ng-template>`.  You would likely need to delay your initialization of your `DataSource`, or write your `DataSource` to allow for delayed attachment of the `MdSort`, once it is available. 

However, rather than changing between two scaffolded versions of the same table, you should create multiple `DataSource` and simply connect and disconnect them as appropriate.  I made a quick example [here](https://plnkr.co/edit/z4gNwuDDyuFKAWWtzDGZ), click toggle to swap between the two `DataSource`s.
