### ISSUE TITLE
Md-menu is not working when using *ngFor with newly created arrays.

### ISSUE THREAD

**Issue by popovicsandras** [angular/material2#7165]
#### Bug, feature request, or proposal:
Bug. Md-menu is not working when using *ngFor with newly created arrays.

#### What is the expected behavior?
Md-menu should work with *ngFor properly.

#### What is the current behavior?
[See Plunker](https://plnkr.co/edit/oCGxFB?p=preview)

#### What are the steps to reproduce?
[See Plunker](https://plnkr.co/edit/oCGxFB?p=preview)

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
https://plnkr.co/edit/oCGxFB?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.1
Material: 2.0.0-beta.10
OS: macOS Sierra
TS: 2.4.2
Browsers: Only tested in Chrome 61.0.3163.91

**Comment by crisbeto** [comment]
Everything works as expected @popovicsandras. Your code doesn't work, because you're returning a completely new array every time the getter runs (which means every Angular change detection cycle). Since there's a `mousedown` handler on the menu items, it means that the `items1` array will be re-rendered when you press down and you'll get a new set of menu items by the time you've stopped pressing which will interrupt the click handler.
