### ISSUE TITLE
mdSnackBar requires additional page action to working with global http error handling

### ISSUE THREAD

**Issue by rbriguetto** [angular/material2#7233]
#### Bug, feature request, or proposal:
Bug

#### What is the current behavior?
When using mdSnackBar in a global error handling class to show http erros, mdSnackBar.open() dont show de message until another action on page is done (component focus, button click, etc).

#### What are the steps to reproduce?

Click on "Global Handling" button, the error is shown only after change focus to input component.
Click on "Local Handling" button, the error is shown instantly.

http://plnkr.co/edit/qgjBA7NmjhoXg5EYmapA?p=preview

Best Regards,

**Comment by josephperrott** [comment]
This is actually working as expected.  The executions in `ErrorHandler` are not invoking a change detection cycle.  Because execution of the `handleError` method in your `GlobalErrorHandler` occur outside of change detection, the snackbar will not show as "opened" until the next change detection cycle runs.

For handling errors generically for `HttpRequest`s, I would recommend using an `HttpInterceptor`
