### ISSUE TITLE
Multiple mdAutocomplete Instances on One Page

### ISSUE THREAD

**Issue by OmarAlmootassem** [angular/material2#7268]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When tabbing around multiple autocomplete fields and then choosing an option from one of the autocomplete fields, the model of the input in focus should get updated.

#### What is the current behavior?
Say there are 2 inputs with autocompletes that have different models. If you focus on the first one with a mouse and then tab to the second one, then on the second one you select one of the autocomplete options, the model for the first input gets updated instead of the second input.

If you switch between the autocompletes using a mouse click, they function perfectly.

#### What are the steps to reproduce?
1. Focus on the first input with mouse
2. Tab to another input
3. Select an autocomplete option
4. The first input gets updated instead of the one in focus

Plunker template: http://plnkr.co/edit/ZkhGO1T5s2IubavablcJ?p=preview

#### What is the use-case or motivation for changing an existing behavior?
As a bug fix to better support multiple autocomplete components on one page.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.3.4+
Material 2.0.0 beta.10+

**Comment by crisbeto** [comment]
A couple of notes:

1. It seems like you named all of your autocomplete instances `auto`. I recommend giving them unique names to avoid issues in the future.
2. It looks like the autocomplete doesn't clear itself out on tab, if there were no options in the list, which causes it to open once the list is populated. This is definitely an issue on our end and I've submitted a fix at #7270. Until the fix is merged, you can work around it by having a separate variable for each autocomplete. [Here's a forked Plunkr.](http://plnkr.co/edit/OIZIG6rJY2PQJtBlPW06?p=preview)
