### ISSUE TITLE
feature(autocomplete): add @Input() disabled property

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#7269]
#### Bug, feature request, or proposal:

The autocomplete should have a disabled input. Sometimes you want to mark the associated input as readonly (you do not want the disabled styles applied to the input) and do not want the autocomplete to fire up when you click on the component (in the cases you have some minimal default options)

#### What is the expected behavior?

To have an `@Input() disabled` in autocomplete. As the Datepicker has a disabled property, to keep the consistency, the autocomplete should have one too.

#### What is the current behavior?

Without the `@Input() disabled` you have to clear up the array, what is a not so difficult task, but it would be more consistent if it had a disabled property, like Datepicker.

**Comment by crisbeto** [comment]
I'm not sure that adding another input is the way to solve it. What about not opening the autocomplete for readonly inputs in the first place?

**Comment by julianobrasil** [comment]
Yep. Differently from the Datepicker, not opening the autocomplete makes sense for the autocomplete.

**Comment by Upimage** [comment]
Sorry, guys, but the latest change breaks all my forms in my application. I use a readonly input when ever the user should choose form a list of values instead of typing a new value. There are some rare situations in my application when the user can type a new value into the same input. While I can use a md-select for readonly and an autocomplete for edits, this solution results in more code and more complicated HTML. 
Please, add an "readonly/disabled" flag to the autocomplete element instead of disabling the autocomplete when the input is readonly.

**Comment by julianobrasil** [comment]
@Upimage, I think this can help you: #3334

Specifically, I'd take a look at @willshowell's solution: https://github.com/angular/material2/issues/3334#issuecomment-319191915

**Comment by kamok** [comment]
Using `readonly="{{disabled}}"` kinda works. But it doesn't have the goodies that the regular `disabled` does, such as visual and cursor effects. Kinda whack to have to implement those css manually.
