### ISSUE TITLE
chips: placeholder disappears

### ISSUE THREAD

**Issue by mmalerba** [angular/material2#7481]
#### Bug, feature request, or proposal:
Placeholder disappears after typing 2 characters into chip input

#### What is the expected behavior?
Placeholder doesn't disappear

#### What is the current behavior?
Placeholder disappears

#### What are the steps to reproduce?
1. Go to this plunker: http://plnkr.co/edit/qHQlWKfGSyvIhgm6MUop?p=preview
2. Type 2 characters into the input

#### What is the use-case or motivation for changing an existing behavior?
Existing behavior is incorrect

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
master

**Comment by julianobrasil** [comment]
Yeah... I replaced your code with [material.angular.io](https://material.angular.io/components/chips/overview) example code: http://plnkr.co/edit/onlnaLR0y5DoRIHCJ4IX?p=preview

And noticed:

1. Missing floating placeholder
2. When the floating placeholder appears, it is behaving a little bit strange
3. It's ignoring matChipInputSeparatorKeyCodes==ENTER
4. After the third fruit added the input caret is not visible anymore due to the limited input width. If you increase the mat-form-field width, you can add more fuits
6. The chips go off mat-form-fied limits without wraping (sometimes you are able to add a lot of off-limit chips - its easy to see this in [material.angular.io](https://material.angular.io/components/chips/overview))

![image](https://media.giphy.com/media/l378A49zcbllRxxxm/giphy.gif)

**Comment by amcdnl** [comment]
Confirmed the issues.

If you add the following CSS, you can achieve the no-wrapping issues:

```
.mat-form-field-type-mat-chip-list {
  .mat-form-field-flex {
    flex-wrap: wrap;
  }
  .mat-form-field-prefix, 
  .mat-form-field-suffix {
    max-width: 100%;
  }
}
```

However, when you do this the input breaks into its own separate line leaving an awkward space.

![img](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/ff91b87d-9887-4243-8d9e-d0a44e3979d1/2017-10-03_09-41-41.png)

I think this component will need to be re-worked in order to make this work nicely, so I'm giving this pretty high effort to fix.

**Comment by mmalerba** [comment]
It looks like part of the issue is that the example page is out of date. We changed the `mat-chip-list` to work with `mat-form-field` without needing to cram it in the `matPrefix`. New style is like this: http://plnkr.co/edit/kc3bxAZRgHS0JbGl3qSX?p=preview

**Comment by amcdnl** [comment]
I've made the PR to fix the placeholder and PR to fix the invalid example. :)

**Comment by puppeteer701** [comment]
Why was placeholder removed if there are values in chips?

**Comment by amcdnl** [comment]
@puppeteer701 - can you show an example?
