### ISSUE TITLE
(Bug) Snackbar animations too fast

### ISSUE THREAD

**Issue by TheRedD0t** [angular/material2#7495]
Will be fixed through #6791.

**Comment by willshowell** [comment]
I know you're not finished, but related discussion in https://github.com/angular/material2/pull/6791

**Comment by TheRedD0t** [comment]
Damn, sorry, I searched if there's already a open issue but seems as I forgot to search through the PRs. Thank you @willshowell!
Does the PR also fix the issue with the animation if a snackbar is already shown and second one is triggered?

**Comment by willshowell** [comment]
The back-to-back animation bug has been fixed in master via https://github.com/angular/material2/pull/7086.

However, if you want, I think you could reopen this issue specifically for having different snackbar durations at different screen sizes. See end of https://github.com/angular/material2/pull/6791#issuecomment-331934481 for reference.
