### ISSUE TITLE
Raise ripple from core to src/lib

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#7543]
- [ ] Move ripple code from `src/lib/core` to `src/lib` directly
- [ ] Add tsconfigs
- [x] Add `ripple.md` overview
- [x] Rework public API for easier-use.
- [x] Generate `material-ripple.html` for docs output.
- [ ] Add live examples
- [ ] Add ripple to docs-items on material.angular.io

**Comment by DevVersion** [comment]
The ripple directive is still part of `core/`, but is documented now. It also includes live examples. 

We didn't move it into a separate entry-point because the `<mat-option>` directive within `core/` also depends on the ripples.

So, that would mean that we either need to extract `MatOption` into a separate module, or the `@angular/material/core` would depend on `@angular/material/ripple`. This feels a bit odd.
