### ISSUE TITLE
MomentDateAdapter issue

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/material2#7581]
#### Bug, feature request, or proposal:
BUG

#### What is the expected behavior?
I have created a date Validator.
When you fill in a faulty date, that should trigger an error detection that the date is incorrect.
![image](https://user-images.githubusercontent.com/1098243/31277432-3a21b564-aaa1-11e7-949a-0a41fa9b2052.png)

#### What is the current behavior?
However, for the moment it does not do that:
![image](https://user-images.githubusercontent.com/1098243/31277348-cf485aa4-aaa0-11e7-9626-46696dd9cd7d.png)

I'm using the momentAdapter.
If I change in the momentAdapter:

    MomentDateAdapter.prototype.parse = function (value, parseFormat) {
        if (value && typeof value == 'string') {
            return moment(value, parseFormat, this.locale);
        }
        return value ? moment(value).locale(this.locale) : null;
    };

to:

    MomentDateAdapter.prototype.parse = function (value, parseFormat) {
        if (value && typeof value == 'string') {
            return moment(value, parseFormat, this.locale);
        }
        return value ? moment(value).locale(this.locale) : "faulty";
    };

then it does work.
The issue seems to me that a null is returned when the date is faulty.
This way, the validation is not done or the validation of the date is ok because the validation thinks the field is not filled.

**Comment by mmalerba** [comment]
The `null` you pointed out is so that empty string will get converted to null rather than an invalid date. Just to clarify, did you create your own validator or you're using the one built into the datepicker?

**Comment by LanderBeeuwsaert** [comment]
I'm using my own custom built. Can you tell me how I would be able to use the built in one? That would be much appreciated!

**Comment by mmalerba** [comment]
The built in one is added automatically when the `DateAdapter` fails to parse the user's input (see this stackblitz: https://stackblitz.com/edit/angular-material2-issue-v6rgjq?file=app/app.component.html)

I think the issue you're seeing might be because Moment.js does actually parse that as a valid date. For example the `NativeDateAdapter` considers `'abc/123'` to be a valid date because `new Date('abc/123')` returns a valid date. If you want stricter parsing you can extend one of the existing DateAdapters and override the `parse` function
