### ISSUE TITLE
CHANGELOG modified 'a month ago' :(

### ISSUE THREAD

**Issue by davidgabrichidze** [angular/material2#760]
Concerns of community's common member.

I know that it is not a place to submit such concerns, but really, is there vision or plan or something similar that will create clear expectations of development of this awesome framework? What are priorities of material2 compared to angular2, angular-cli, etc...

**Comment by jelbourn** [comment]
Our alpha.6 fell behind a bit due to other work that came up and should be releasing later today (with some items punted). Our current dev/release cycle is on ~3 week milestones, so "a month ago" isn't really that strange. You can see the actual activity in [commits](https://github.com/angular/material2/commits/master) and in [PRs](https://github.com/angular/material2/pulls).

**Comment by jelbourn** [comment]
Trying to bump to rc3 makes the [tabs tests mysteriously fail](https://travis-ci.org/angular/material2/builds/140156425) on CI (but pass locally), so... maybe Monday.

**Comment by davidgabrichidze** [comment]
@jelbourn thanks for update. It's not complain or something like that.
It's clear that you google guys and other community members are actively working on this and thank you all for your commitment and work.

I'm just expected that progress of publishing of version would be more quick that it is now. Also, I'm not able to find some meeting notes, or development road-map on web. That is, noting else, and again, thanks for your work!
