### ISSUE TITLE
drawer container not reacting to drawer removal

### ISSUE THREAD

**Issue by ghost** [angular/material2#7672]
fix(drawer): drawer container not reacting to drawer removal [#7060](https://github.com/angular/material2/pull/7060)

I got the latest using npm install --save @angular/material @angular/cdk

But still the issue seems to exist. Is the change not yet deployed?

**Comment by willshowell** [comment]
Can you reproduce in [StackBlitz](https://goo.gl/wwnhMV)?

**Comment by darshu514** [comment]
It works there, but I believe that the code is merged to master but it's not in the latest build. Because I got the latest using npm install --save @angular/material @angular/cdk. The first time when the page loads the margin-left for mat-sidenav-content is 0px, and when I click the  + button the margin seems to get applied as expected, i.e. the toggle functionality works fine

**Comment by willshowell** [comment]
#7060 should be in beta.12 and that stackblitz template uses beta.12. 

> The first time when the page loads the margin-left for mat-sidenav-content is 0px, and when I click the + button the margin seems to get applied as expected, i.e. the toggle functionality works fine

This sounds like https://github.com/angular/material2/issues/7682

**Comment by willshowell** [comment]
Though it seems to works fine,

https://stackblitz.com/edit/angular-material2-issue-moq6k8?file=app%2Fapp.component.html

Can you expand on what exactly the issue is?

**Comment by darshu514** [comment]
So, I mean this works fine in https://angular-material2-issue-qbxhcv.stackblitz.io

In my machine (fyi i did npm install --save @angular/material @angular/cdk) when I try to do the same thing, on the page load mat-sidenav-content has margin-left: 0px. When I click on the '+' button on the  the  mat-sidenav-content, mat-sidenav element hides(as expected). Now the mat-sidenav-content has margin-left: 0px. Again if I click the '+' button on the  the  mat-sidenav-content, mat-sidenav element appears and the mat-sidenav-content has margin-left: 200px. And from now on the toggle functionality works fine. So, the bug is that on page load when mat-sidenav element is visible, the margin-left for mat-sidenav-content should be 200px.

**Comment by willshowell** [comment]
Without providing a reproduction, this will be very difficult for anyone to track down. Are you positive beta.12 is installed?

**Comment by darshu514** [comment]
Yes, these are my packages:
"@angular/animations": "^4.4.4",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.4.4",
    "@ng-idle/core": "^2.0.0-beta.12",
    "@ng-idle/keepalive": "^2.0.0-beta.12",
    "@ngrx/effects": "^4.0.5",
    "@ngrx/store": "^4.0.3",
    "@ngrx/store-devtools": "^4.0.0",
    "add": "^2.0.6",
    "angular2-tag-input": "^1.2.3",
    "core-js": "^2.4.1",
    "dragula": "^3.7.2",
    "enhanced-resolve": "3.3.0",
    "file-saver": "^1.3.3",
    "immutable": "^3.8.2",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "mydatepicker": "^2.0.31",
    "mydaterangepicker": "^4.1.9",
    "ng-idle": "^1.3.2",
    "ng2-auto-complete": "^0.12.0",
    "ng2-dragula": "^1.5.0",
    "ng2-interceptors": "^1.3.0-1",
    "ngx-chips": "^1.5.3",
    "ngx-modialog": "^3.0.4",
    "ngx-pagination": "^3.0.1",
    "rxjs": "^5.4.2",
    "typescript": "2.3",
    "zone.js": "^0.8.14"

**Comment by darshu514** [comment]
Any update on this?

**Comment by mmalerba** [comment]
Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are stack overflow, gitter, mailing list, etc.
