### ISSUE TITLE
MatButtonToggleGroup shows multiple selection when adding a button under material pre-buillt themes

### ISSUE THREAD

**Issue by cezaryn** [angular/material2#7706]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Once you add a button and change the mat-button-toggle-group value to the new button only the new button should be shown highlighted

#### What is the current behavior?
Once you add a button and change the mat-button-toggle-group value to the new button both the new button and the old selected button are shown highlighted

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-gnovor

press the add button, this will add a new button, but will show two buttons highlighted

if you comment out the pre-built theming from style.css, the buttons are behaving correctly with only one highlighted

**Comment by tinayuangao** [comment]
The cause of this issue is after we added a new button to the group, the change detection not run and the list of button toggles inside button toggle group is not updated with the new button. Then when we assign a new value to the button toggle group, the old selected value will not be removed since the newly selected value is not in the list yet.

A way to solve this issue is run change detection after adding a new button: 
https://stackblitz.com/edit/angular-zzujtf?file=app/app.component.ts
