### ISSUE TITLE
wrong sourcemapping url for all bundle cdk min.js files

### ISSUE THREAD

**Issue by alanpurple** [angular/material2#7744]
It's obvious, no need to provide form

**Comment by willshowell** [comment]
I suspect if it were obvious, it would have been fixed already. Please use the issue template to help the team identify the problem.

**Comment by alanpurple** [comment]
@willshowell  what else I need to say about wrong string? you or any other just needs to see the last line of @angular/cdk/bundles/cdk*.min.js

**Comment by willshowell** [comment]
Consider pointing to the line of one of the broken sourcemapping urls and suggesting what it should be corrected to. That is the exact purpose of the "Current behavior" and "Expected behavior" headers in the issue template.

It is not constructive to tell maintainers of an open source project that their bugs are so obvious that you don't need to provide context.

**Comment by andrewseguin** [comment]
Please re-open using the issue template, thanks
