### ISSUE TITLE
bug(table): trackBy works if row moves down, but not up.

### ISSUE THREAD

**Issue by cpboyd** [angular/material2#7767]
#### Bug, feature request, or proposal:
I've setup a `trackBy` function to track rows by a unique identifier.
However, if that row moves up (from, say, index 4 to index 2) in the array then the row is recreated.

If the row moves down in the array (from index 2 to index 4), then the row is simply moved and not recreated.

#### What is the expected behavior?

I think trackBy ought to work in either direction.

#### What is the current behavior?

It only seems to work for tracking if a row moves downward in the table.

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/DlHd6U<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>

Will provide later.

#### What is the use-case or motivation for changing an existing behavior?

I noticed this because I sort the Observable that's hooked up to the table (since my table performs calculations in real-time based upon user input).

If I edit a row to increase the total and it moves down, the user can keep entering information into the material input field.

However, if the row's total decreases and it moves up in the table, the material input field loses focus.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

**Comment by cpboyd** [comment]
It seems to be related to [cdk/table/table.ts#L301](https://github.com/angular/material2/blob/0875b858d0fc374286ffa374572fed766454074d/src/cdk/table/table.ts#L301) and tracking the row's `adjustedPreviousIndex`

**Comment by andrewseguin** [comment]
Not sure I'm able to reproduce this one. Here's a table where you can dynamically change the trackBy: https://plnkr.co/edit/SK3OEjZ4IAtGvmPRjxPB?p=preview

Make a DOM change (highlights first `md-row`) and then swap the rows. You'll see that the highlighted row swaps correctly. This means its being moved rather than added/removed no matter the direction.

You can try different trackBy strategies to verify. One tracks by reference, the other by position. These should preserve rows and only move them after they are added. The index one won't want to swap since the table is told that the rows are equivalent.

If you can set up a plunker that reproduces the issue you are seeing, please re-open this and I can dive in to see whats up.
