### ISSUE TITLE
md-sidenav-layout should not prevent use of position:fixed

### ISSUE THREAD

**Issue by Hades32** [angular/material2#778]
package version: Alpha5.2

md-sidenav-layout seems to work with with css transforms what in turn breaks position:fixed as this establishes a new viewport.

This makes it impossible to place floating elements inside content in this layout.

I use the content as my router-outlet (what probably many will do). In my content I want to use a floating md-fab button which I now have to place in the main application component. this sucks.

**Comment by AmirTugi** [comment]
+1 Experiencing it right now

**Comment by sebastianhaas** [comment]
Confirm that this is still an issue. It's really really annoying. Even if I manage to put it outside the sidenav-layout (which is not so easy to achieve since I have to pass icon, click handler/router link etc.), the fab isn't affected by the black transparent overlay on sidenav.open() anymore which is a big visual break.

**Comment by petrosalema** [comment]
@hansl, just wondering why this issue was closed.

**Comment by petrosalema** [comment]
See also 👉🏾  https://github.com/angular/material2/issues/998

**Comment by safaahammoud** [comment]
Adding z-index 1000 to the parent which has position fixed would fix the issue.
