### ISSUE TITLE
mat-sidenav-container - hide address bar on mobile devices

### ISSUE THREAD

**Issue by maku** [angular/material2#7818]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
When using mat-sidenav-container it should be able that address bar on mobile devices will be hidden when scrolling.

#### What is the current behavior?
Address bar is not hidden.

I guess because of the "content" is placed in mat-sidenav-container the content "scrolls" in mat-sidenav-container and therefore the browser is not aware of the scrolling.

#### What are the steps to reproduce?
Look at e.g. https://material.angular.io

Maybe it is possible to use mat-sidenav without mat-sidenav-container...

**Comment by Chan4077** [comment]
Could you please rephrase your query? I don't really understand what you meant.

**Comment by juane1000** [comment]
First time commenting on GitHub so apologies if my response is a bit lacking! I've been struggling with this issue since Angular Material v1 of AngularJS. Whenever the height of a container is set to 100% with overflow on AUTO, it introduces a scrollable region that the browser doesn't recognize as a normal entire viewport scroll..if that makes sense. Which has that annoying effect of the URL bar on mobile devices staying visible.

As of the latest update to the Material module  last week, 2.0.0-beta.12 marble-mustache, this has been fixed by enabling the fixedInViewport attribute on the matSidenav element. Set it to TRUE and you're off to the races. It worked out of the box for me. Just be sure not to set the html, body, app-root elements to 100% height like the docs suggest. That is pre-latest update technique for fixed sidenav that resulted in the scrollable region. There really isn't much to it. I just added that attribute and worked as advertised.

[https://material.angular.io/components/sidenav/api](url)

The api section of the docs have been updated to reflect that new attribute on the matSidenav so check it out for better details. And here is the changelog that has it mentioned under the features section too.

Hope this helps!

**Comment by josephperrott** [comment]
@mmalerba Was this already addressed?

**Comment by mmalerba** [comment]
The sidenav does support this now, but you have to structure the page so that the body is the element that scrolls. To do that you'll need to use the `fixedInViewport` property. An example of how to do it can be found in this PR to update the documentation: https://github.com/angular/material2/pull/7775
