### ISSUE TITLE
Angular Material Release Timeline ?

### ISSUE THREAD

**Issue by Sharad777** [angular/material2#7820]
I like the angular material and was hoping to use this library for one of my projects.

Do you have any tentative date/timeline when the GA or RC release will be available?

**Comment by josephperrott** [comment]
We haven't announced an official date for this yet; stay tuned to the Angular blog for future announcements.

**Comment by tschock** [comment]
I find it a little concerning that whenever someone asks when Material will reach a stable release the only answer that is given is the one above.  Is there at least a ballpark estimate of when it will come out (EOY, sometime next year, the following year, etc...)?  One reason we like the Angular project is that you guys have created a release schedule so that people have an idea of when items will move out of alpha, beta, or rc.  But with Material it feels like a similar approach to what Bootstrap takes with LONG running alpha and beta releases with no real time line of when it will stabilize which makes it very difficult to schedule around when new releases are available.  We really want to take advantage of what Material offers and think that it is a fantastic product, it just needs to get caught up with how other Angular projects are managed and released.

**Comment by vitaly-t** [comment]
Now with Angular 5 released, if do not see an imminent release of Material 2, developers will be losing their trust in it. It's been in Beta-s way too long at this point.

**Comment by benb7760** [comment]
The [readme](https://github.com/angular/material2/blob/master/README.md) answers this question

> High level stuff planned for Q4 2017 (October - December):
> * RC and stable release
