### ISSUE TITLE
Dynamically Loaded Components(Dialog, Toast)

### ISSUE THREAD

**Issue by borislemke** [angular/material2#783]
#### Bug, feature request, or proposal:
I noticed that the Angular team hasn't started on components that needs to be dynamically loaded such as the MD Dialog and MD Toast present in Angular Material 1. There is no best practice in how to load and destroy elements like these in Angular 2. Any ideas on how this can be achieved?

In Angular Material 1, we could also pass data into the dialog and output data when the dialog is destroyed/hidden(promise based).

#### What is the expected behavior?
Dynamically load components into the view for modals, toasts and the likes

#### What is the current behavior?
No proper documentation

#### What is the use-case or motivation for changing an existing behavior?
If the Angular team has started on at least one of these components(dialog or toast), we may start exploring the possibilities of how to best handle dynamically loaded components and create our own

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.0.0-rc.3
Angular Material 2.0.0-alpha.5-2

**Comment by TheCaptainDate** [comment]
We can pass any data to dynamic components by using of [ng-content](https://toddmotto.com/transclusion-in-angular-2-with-ng-content).

In case of Modal we actually can place our html things inside any component that gonna use this Modal because modal should not draw itself before call of `popup()` or something. Also modal should have absolute position and z-index so there is no any reason for modal to be pasted somewhere at the special place (like root component or etc).

You can just write your modal where you want then pass data by using of ng-content and finally draw it when *ngif becomes true.

From the other hand it will be cool if modal component can be written only ones somewhere in root component and then just been reused when need to.

**Comment by borislemke** [comment]
Thanks for the reply. However, in Angular Material 1.x, this is not how
dialogs and toasts work. They just get injected by a service-like
module($mdDialo) which does not require the explicit declaration of a modal
wrapper in the document. These element will just get dynamically inject
into the documents body. I'm keen to know what the Angular team thinks and
whether they can give a better insight.

**Comment by TheCaptainDate** [comment]
@borislemke [take a look](https://github.com/angular/material2/pull/761/commits/cd7d7d12e23545b36c4880d7204556db968517c4)

**Comment by borislemke** [comment]
@TheCaptainDate thanks mate! Exactly what I was looking for. Will keep track of it

**Comment by jelbourn** [comment]
Check out https://github.com/angular/material2/pull/761.

More coming soon!

**Comment by m00zi** [comment]
ng-content solved my problem. Thanks
