### ISSUE TITLE
[Table] Rows are not provided correct $implicit with trackBy

### ISSUE THREAD

**Issue by quanterion** [angular/material2#7877]
#### Bug:
MatTable doesn't refresh row columns if [trackBy] function used. For example if I replace rows array with a new one having the same ids, but completely different data MatTable won't update. I suspect the same applies to CdkTable.
It looks like it correctly updates table when removing / adding rows but it fails to trigger ChangeDetection on <mat-row> components if no rows added or removed

#### What is the expected behavior?
When used with trackBy function Table should trigger change detection on all existing rows, just like ngFor with trackBy do.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-tbrfqj?file=app%2Fapp.component.html

**Comment by willshowell** [comment]
Wouldn't this be what you want?

`trackBy` is used to uniquely identify rows when you want to use some identifier other than the Object Reference. By using the same `id` for the swapped row, you're purposefully tricking the table into thinking that nothing has changed.

**Comment by quanterion** [comment]
I suppose using trackBy is intended to prevent recreating components and should not stop change detection to happen. I updated stackblitz template to show that ngFor+trackBy updates correctly.

**Comment by andrewseguin** [comment]
Thanks for reporting this issue. The intention of `trackBy` is to make sure we are being smart about when to build/teardown rows, which is a separate concern than change detection. In fact, since cell templates are written by the user and not the table, the table has no control over when change detection occurs for those cells.

It turns out that when `trackBy` is used, a row can be re-used for a different data object, but the table never updates row/cell `$implicit` data (the exported variable for cells). `ngFor` does have this built in by checking for identity changes in the data, but it didn't get brought over to the table's logic.

Thanks again for the issue, this was a major one that I'm surprised got this far.
