### ISSUE TITLE
Are you alive?

### ISSUE THREAD

**Issue by zigzag95** [angular/material2#788]
@jelbourn @kara are you still working on this project?
Many developers are using material2 and now we are blocked because we can't upgrade to RC3 since alpha-6 is frozen. Could you please make some communication about what is happening and please let us help you by detailing the roadmap.
@jelbour @kara are you really Google?

**Comment by vamsivarikuti** [comment]
@zigzag95 LOL,

But, seriously we are waiting for lot of feature
When is the next release?

**Comment by ikourfaln** [comment]
You right guys, We cant wait anymore, as @vamsivarikuti said, You said we can start using Material2, but you are not pro like ASP.NET Teams, they communicate with devs via conf and standups.
Anyway We cant wait. so We must start our project with another UI Framework such as Semantic UI.

**Comment by m0t0r** [comment]
Hey guys, can you think carefully before writing such messages? Do you think Google people are actually robotos which can and sit and build you components for 27/7? or do you think they just sitting on a beach drinking cocktails ? They work very hard for **you** to get for **free** high quality products. Does it say anywhere this project is ready for production? Presentations were just for preview what current progress is. No one ever said go and use it in production. 

**Stop such annoying behavior and these all questions "when"?** (and questions "are you really Google?") **Be respectful!** If you don't like something go and _help_ to build it, otherwise just go and use whatever else is there. They don't have to deliver anything for you by tomorrow. Be patience!

**Comment by RemKolomna** [comment]
Yeah! On their place I would go mad in a few days if I should constantly close endless duplicate issues after people not used to search and not able to wait.

**Comment by ikourfaln** [comment]
@m0t0r you right, but one thing, They work very hard not just for us to get what you call free high quality products. They create Angular and Materials for google's products in first place. So thanx to the community too, they are also working by delivering Feedbacks and some PRs.

**Comment by hacknaked** [comment]
@m0t0r I agree with all you said, but I also understand the frustration of lack of communication. This project have very high expectations but no roadmap, no feedback, no documentation and low activity (specially in the last weeks). Also, some weeks ago the Angular Material team announced that they will focus intensively on Angular Material2 on Q3 https://groups.google.com/forum/#!topic/ngmaterial/4ActiQp3nA0, 

So, I guess that many people has taken decisions and bet on this project based on that announcement and all this situation is frustrating. I don't want to be annoying or no respectful, but I think that better communication will help more people to contribute on this great project.

**Comment by vamsivarikuti** [comment]
@m0t0r: **no pun intended** , 

I am just excited to play with the new features.
I do know that open source developers are sacrificing their time and energy to save everyone else's. 

I apologize if I was rude

@jelbourn @kara Thank you for creating Material2

**Comment by jelbourn** [comment]
Released alpha.5-3 this morning, which is exactly what alpha.6 will be except for using `@angular/forms`. I'm trying to release alpha.6 now, but have run into an unexpected error w/ md-input + the new forms package. Going to release (with changelog) once we figure that out. 

Delays on releasing alpha.6 have been due work that's not directly "make new components". If you look at commits and PRs, you'll still see a steady stream of going-ons. Nothing should be blocking moving to Angular rc3 other than some peer dependency warnings (which AFAIK can be ignored). 

Most of my time recently has been trying to get material2 working with Angular's offline compiler, which is exposing bugs in the tooling that need to be resolved. The whole process is somewhat time consuming, but is necessary to validate this tooling so that Angular 2 _itself_ can get to final. Important, but not very visible.

If you have been following Angular, you might know that Kara has been driving the new `@angular/forms` module, which is another piece necessary to get Angular 2 itself to final. 

Other things include:
* Google I/O
* Working with Google teams using Angular and Material. getting internal tooling set up. 
* Being involved with design and work on Angular core
* Support for Angular Material 1.
* People get sick and go on vacation (I am on vacation right now.).
