### ISSUE TITLE
Nested menus arrows show on the right when xPosition before used.

### ISSUE THREAD

**Issue by alexw10** [angular/material2#7921]
#### Bug, feature request, or proposal:
I believe this is a bug:
xPosition before the arrows stay on the right side even though the overlays open on the left.
See stackblitz for example of this.

#### What is the expected behavior?
I would expect that the arrows should be on the left side if xPosition before is used.

#### What is the current behavior?
xPosition before the arrows stay on the right side even though the overlays open on the left.

#### What are the steps to reproduce?
https://angular-material2-issue-eep2va.stackblitz.io

#### What is the use-case or motivation for changing an existing behavior?
Arrow staying on the right seem incorrect since the overlays open on the right I would think the arrows would be pointed to the left and would appear before the text?

#### Is there anything else we should know?
Let me know if it is intended to be like this.

**Comment by crisbeto** [comment]
It works as intended. The arrow doesn't really show where the menu will open, but rather that there is a sub-menu to begin with. We also can't know where the overlay will open until it actually opens. Lastly, I haven't seen any other native elements where the arrow flips depending on the sub-menu direction (e.g. the native Windows menus point in the same direction, even though the menu opens on the other side), I assume because it would look inconsistent (for example, you could have a parent menu have the arrow on right, a child have the arrow on the left and a grandchild with an arrow to the right).

**Comment by alexw10** [comment]
Thanks for the insight @crisbeto seems to make sense to me! :)
