### ISSUE TITLE
mat/md-option using [innerHtml] break mat/md-select's multiple attr checkbox

### ISSUE THREAD

**Issue by WandersonAlves** [angular/material2#7925]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Using mat-option with `[innerHtml]`, show up the `multiple` checkbox component from mat-select

#### What is the current behavior?
Checkboxes doesn't show

#### What are the steps to reproduce?
Here are two selects, one with multiple and another without
http://plnkr.co/edit/MgUHLh1GaKe41fXbrXnF?p=preview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
In plurker: lastest of all
My project:

Angular 4.3.4
Material 2.0.0-beta-10
OS: Windows 10
TypeScript: 2.4.2
Browser: Chrome 61

#### Is there anything else we should know?
No, everything is on the plunker

**Comment by crisbeto** [comment]
Everything works as expected. When you bind to `innerHTML`, you're overwritten all the HTML inside the option, including the checkbox and the ripple effect. In general this is a bad idea, because of the performance and security implications, but if you really want to continue doing it, you can add a `span` inside the option and bind the `innerHTML` to it instead.
