### ISSUE TITLE
proposal(mat-button): rename mat-button directive to matButton

### ISSUE THREAD

**Issue by thefliik** [angular/material2#7954]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
The `mat-button` directive should conform to the [angular style guide](https://angular.io/guide/styleguide#directive-selectors) and have a name in lowerCamelCase: `matButton`

```
<button matButton></button>
```

#### What is the current behavior?
The `mat-button` directive does not conform to the [angular style guide](https://angular.io/guide/styleguide#directive-selectors)

```
<button mat-button></button>
```

#### What is the use-case or motivation for changing an existing behavior?
Conform angular material2 to the [angular style guide](https://angular.io/guide/styleguide#directive-selectors)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 4.4.6
material 2-beta.12

**Comment by fxck** [comment]
`mat-button` is a component, not a directive

**Comment by thefliik** [comment]
@fxck you are incorrect,[ see the docs](https://material.angular.io/components/button/api). `mat-button` is used as `<button mat-button></button>` and is a directive.

**Comment by fxck** [comment]
It's a component.

https://github.com/angular/material2/blob/master/src/lib/button/button.ts#L115-L215

**Comment by thefliik** [comment]
@fxck Oh wow you're correct. So in this case, `mat-button` is violating the style guide recommendation that components utilize element selectors rather then attribute selectors: https://angular.io/guide/styleguide#style-05-03

That also gives more context to this material docs line
> Native <button> and <a> elements are always used in order to provide the most straightforward and accessible experience for users.

That explanation is ambiguous enough that I don't know what it means. Is there a performance / other reason for `mat-button` to not conform to the standard style?

Obviously, I find the current implementation confusing.

**Comment by fxck** [comment]
It's a recommendation, not a dogma. The reason is obvious, `mat-button` can be used on both anchors and buttons. If you were to use elements, you'd have to have two components, `mat-button-button` and `mat-button-anchor` and pass all the possible attributes to the underlying native elements. So in this particular case, having attribute selectors for a component makes perfect sense.

**Comment by thefliik** [comment]
@fxck ok. That reasoning wasn't obvious to me. From my perspective, it's obvious that there could just be one `<mat-button>` element and users could apply a `routerLink` attribute to it or wrap it in an anchor tag, if desired.

In this case, `mat-button` is adding styling to an existing element (i.e. `mat-ripple`, `mat-button-focus-overlay`) which is behavior I traditionally associate with a (non-component) directive.

**Comment by thefliik** [comment]
I guess I'll close this issue because it seems clear that `mat-button` is functioning as intended, but, while it may have been easier to build the component this way, I find the existing component to be not intuitive.

**Comment by thefliik** [comment]
Anyway, thanks for info

**Comment by fxck** [comment]
You [can't have](https://stackoverflow.com/a/6393863/301596) button inside an anchor. And when it comes to "applying `routerLink` attribute to it", that wouldn't work, you can't internally switch between anchor and button element based on just that, since `routerLink` [listens to click](https://github.com/angular/angular/blob/4.4.6/packages/router/src/directives/router_link.ts#L135-L143) event, you can in theory use it on buttons as well. And as I mentioned, you'd have to manually add all the attributes native elements might have and then pass them down to underlying elements (think `disabled` for example). It's far better to simply have an attribute component.

**Comment by thefliik** [comment]
@fxck Thanks, I'm learning a lot today! `<a><button></button></a>` is something I've done frequently in the past, and, as the question you link to states, it seems to work just fine in most browsers. I'll have to read the spec to see why they don't want designers putting interactive content inside anchor tags...
