### ISSUE TITLE
Menu items can't be clicked in a dynamically populated menu

### ISSUE THREAD

**Issue by isaacnaveh** [angular/material2#8008]
#### Bug, feature request, or proposal:
When you bind a menu to a dynamic collection, items in that menu can't be clicked. This is true for hyperlinks (as in my StackBlitz example below) as well as for buttons with a click handler.

#### What is the expected behavior?
Clicking the hyperlink should trigger navigation.

#### What is the current behavior?
Clicking the hyperlink does nothing

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-ctjhpl

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested on 2.0.0 betas 11 and 12

**Comment by crisbeto** [comment]
The menu works as expected. Your issue comes from the fact that you're returning a new array (via `getItems`) for every change detection cycle. What ends up happening is that on mouse down Angular runs change detection, you return a new array which causes the menu items to be re-rendered. By the time you've lifted your finger, the link has been replaced which causes it to appear broken. You can fix the issue by having an `items` array instead of `getItem`. [Here's a forked working Stackblitz.](https://stackblitz.com/edit/angular-material2-issue-ind5i6?file=app%2Fapp.component.html)
