### ISSUE TITLE
md-fab color only applied to `<button>`s

### ISSUE THREAD

**Issue by Zyzle** [angular/material2#819]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
As per the docs, when using `md-fab` with `<a>` tags it should be possible to set the colour as one of `accent`, `primary`, `warn`

#### What is the current behavior?
This `color` value only appears to be picked up when the directive is used with `<button>` tags not `<a>`s 

#### What are the steps to reproduce?

http://plnkr.co/edit/WaG0nCPeGkJjW6YBaTOn

#### Which versions of Angular, Material, OS, browsers are affected?
material2 alpha.6

**Comment by kara** [comment]
Hey there, it looks like you've only included `MdButton` in your directives array and not `MdAnchor`.  There are actually two directives, one for the `<button>` tag and one for the `<a>` tag.

http://plnkr.co/edit/9IEwD4ZyGPrdIl3a01m7?p=preview

We typically suggest using the aggregate `MD_BUTTON_DIRECTIVES` array rather than the individual symbols to make this easier to remember.  That said, we should probably add a bit more detail to the button docs to clarify this distinction - thanks for reporting!

**Comment by Zyzle** [comment]
Ah that makes sense. Didn't realise there was another directive for anchors. Thanks @kara

**Comment by Zyzle** [comment]
Actually having thought about this a little more would it be possible to have a single `MdButton` directive that applies to both anchors and buttons? Either that or prevent it from applying any styling to anchors. I think there's a lot of room for confusion here as you can see in the plunk it sort of works.
