### ISSUE TITLE
tabs pagination doesn't show inside flex container

### ISSUE THREAD

**Issue by pedrolsamaral** [angular/material2#8252]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The tabs pagination should appear if the some tabs cannot be shown in the container's available width

#### What is the current behavior?
If the mat-tab-group is inside a flex container the tabs pagination will not be shown even when they should

#### What are the steps to reproduce?
This issue can be reproduced in https://plnkr.co/edit/af9GB7jmPRX9rim7p7Kz

#### What is the use-case or motivation for changing an existing behavior?
The pagination should appear whenever the tabs are not able to fit the container

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 4.4.5
Material: 2.0.0-beta.12
OS: Windows 7
TypeScript: 2.3.4
Browsers: Chrome

**Comment by josephperrott** [comment]
This is working as expected because the container element for the tabs is not constrained to a specific width and stretches to the width it needs.  Since all of the tab labels fix inside pagination is not needed.  For pagination to be needed the width should be constrained which could be done in this situation by adding `width: 100%` on the `<mat-tab-group>` you created.

**Comment by eagor** [comment]
just adding `width: 100%` [doesn't](https://stackoverflow.com/questions/55433670/mat-tab-group-width-is-not-reacting-to-width-100-container-in-flex) help
