### ISSUE TITLE
Issue #7306 has been labeled as "cannot reproduce" and closed

### ISSUE THREAD

**Issue by cyberbeast** [angular/material2#8275]
#### Bug, feature request, or proposal:
#7306 has been labeled as "cannot reproduce" and closed, but there seem to be many (including myself) who are still facing the same bug.

#### What is the expected behavior?
Issues should not be labeled "cannot reproduce" or closed if a significant number of people are facing this issue (especially since the latest updates include breaking changes)

#### What is the current behavior?
Issue has been closed but has not been fixed.

**Comment by julianobrasil** [comment]
Have you checked it after the latest 5.0.0-rc0 release? Angular should be upgraded (5.0.0) and the same applies to rxjs (5.5.2) and typescript (> 2.4.3).

**Comment by crisbeto** [comment]
That issue usually happens if you're running an old version of Angular that doesn't support multiple `exportAs` aliases.

**Comment by josephperrott** [comment]
I definitely recognize your frustration, but wanted to be sure to note that the team is not in the habit of closing non-stale issues ourselves because of a lack of reproduction.

-  The cannot reproduce label was applied as a reproduction was not provided (of note, I mistakenly in this case thought it was not provided, it was).  
-  The issue was closed by the poster of the issue.  


Specific to the issue mentioned (#7306), we are still unable to reproduce the issue with running the necessary newer version of Angular (>=4.4.4) as seen [here](https://stackblitz.com/edit/angular-wvqegk)

I am going to close out this issue as this issue was posted about the other issue being closed and wont be discoverable about the `exportAs` issues.  If you still are seeing the issues, please open up a new issue with a reproduction plunker and/or stackblitz  and we can take a look.
