### ISSUE TITLE
No way to have a modal to pop up

### ISSUE THREAD

**Issue by alvipeo** [angular/material2#8321]
please look at this https://stackoverflow.com/q/47192305/2896495
and this https://angular-rnj97t.stackblitz.io

Can we have a decent documentation and examples?

**Comment by josephperrott** [comment]
Please keep GitHub issues for bug reports / feature requests. Better avenues for troubleshooting / questions are stack overflow, gitter, mailing list, etc.

This is working as intended as you the issue you are running into is attempting to use `MatDialog` directives outside of the context of a dialog.  However the directives are expected to be used in a dialog and rely on the dialog context to work.

Specifically you are seeing this error.
```
Error: StaticInjectorError[MatDialogRef]: 
  StaticInjectorError[MatDialogRef]: 
    NullInjectorError: No provider for MatDialogRef!
```

This is happening because `MatDialogRef` is not provided in the injector tree above your `IlgErrorDialogComponent` component when you load it outside of a dialog (this is because `MatDialog` provides a set of injected values during creation of a dialog.  It is attempted to be loaded when you have `[mat-dialog-close]=true`.  You should only be instantiating your dialog content in the context of a dialog, currently you load it in the apps main component and then attempt to load it again in a dialog.

**Comment by alvipeo** [comment]
Sorry, I did not understand a work you wrote. Someone, PLEASE write a blog post!

**Comment by alvipeo** [comment]
ok, I got it. But now I have another problem. Please help out the community - https://stackoverflow.com/q/47196274/2896495
