### ISSUE TITLE
Sidenav height is cut to the content height

### ISSUE THREAD

**Issue by theunreal** [angular/material2#833]
Sidenav height and content height is always equals, Although the min-height was set to 90%.

```
<div class="sidenav-primary-content" style="min-height:90%">
<div class="container-fluid" style="min-height:90%">

<div style="min-height:90%">
<router-outlet></router-outlet>
</div>

</div>

</div>
```

Tried to set min-height:90% to any div and it still cut. 

Strange thing I used it and it worked fine before I moved my project to angular-cli.
I'm using the latest angular2-material and angular.

**Comment by maciejsobala** [comment]
Try "fullscreen" attribute :)

**Comment by cleever** [comment]
Yep,

Although the docs don't mention the 'fullscreen' mode:
https://github.com/angular/material2/tree/master/src/components/sidenav

It exists since 2.0.0-alpha.4:
https://github.com/angular/material2/blob/7635e72053b1676f38e07a1d548f59c877bb47a8/CHANGELOG.md

As you can see in the demo app:
https://github.com/angular/material2/blob/master/src/demo-app/demo-app/demo-app.html
