### ISSUE TITLE
Ripple animation on some controls has jagged edges

### ISSUE THREAD

**Issue by wuchtig** [angular/material2#8392]
#### Bug, feature request, or proposal:
Ripple animation on mat-radio-button, mat-checkbox and mat-slide-toggle has jagged edges.

#### What is the expected behavior?
The round ripple should be smooth.

#### What is the current behavior?
![checkbox](https://user-images.githubusercontent.com/1224640/32701462-b038ee50-c7d6-11e7-949c-c07d23fec0ba.gif)

#### What are the steps to reproduce?
Look at Material Demo Site [Checkbox](https://material.angular.io/components/checkbox/overview), [RadioButton](https://material.angular.io/components/radio/overview) or [SlideToggle](https://material.angular.io/components/slide-toggle/overview).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
MSEdge: 41.16299.15.0
Material: 5.0.0-rc0-3ca801a

**Comment by jelbourn** [comment]
@DevVersion is this just an Edge thing?

**Comment by DevVersion** [comment]
I was able to reproduce this in Edge and it's makes the ripples on all of those components really _unelegant_. We can fix this by no longer clipping the ripples using `border-radius`. 

Ripples are circular by default and since the ripples are always centered we can just use the default radius of those.
