### ISSUE TITLE
mat-progress-spinner animation doesn't work as expected in EdgeBrowser and IE11

### ISSUE THREAD

**Issue by wuchtig** [angular/material2#8393]
#### Bug, feature request, or proposal:
mat-progress-spinner animation doesn't work as expected in EdgeBrowser and IE11

#### What is the expected behavior?
mat-progress-spinner should work as defined on material design guidelines.

#### What is the current behavior?
![spinner](https://user-images.githubusercontent.com/1224640/32701553-4c723b5e-c7d8-11e7-9a1c-bd4c92fbc545.gif)

#### What are the steps to reproduce?
Look at [Material Demo Site](https://material.angular.io/components/progress-spinner/overview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
MSEdge: 41.16299.15.0
Material: 5.0.0-rc0-3ca801a

**Comment by qcryptic** [comment]
Agreed.

I have to run my app with the <meta http-equiv="X-UA-Compatible" content="IE=EDGE" /> header otherwise I cannot load the app in IE11 which I need to support. (this is due to issues with the pivotal reverse proxy setup I believe which I cannot change, and is not an angular materials issues)

But that being said, my progress spinner doesn't even move in IE11, its just a circle.

**Comment by jelbourn** [comment]
The image you linked is the working-as-intended fallback behavior for IE11 and Edge because those browsers don't support the necessary features to make the on-spec behavior possible via css animations. We decided that having different animation for IE / Edge was worth having an all-css animation so that the component still works when server-side prerendered.

@qcryptic if you're just seeing a solid, unmoving circle, please file an issue with reproduction steps.
