### ISSUE TITLE
[Sort] MatSortHeader depends on CdkColumnDef

### ISSUE THREAD

**Issue by jelbourn** [angular/material2#8443]
The sort-header optionally injects `CdkColumnDef` to make the name optional. This reference, though, means that using `matSort` or `matSortHeader` will bring in all of the code for the cdk/table.

**Comment by crisbeto** [comment]
I looked into this one. We need an injection token that can be used to provide the column definition to the sort header, but the problem is where to put the token. We can't have it in `material/sort`, because it needs to be imported both by `material/table` and `cdk/table` (we have some tests according to which `MatSortHeader` supports both). The token can't be in `material/sort` either, because it would introduce a dependency between `cdk/table` and `material/sort`.

**Comment by jelbourn** [comment]
A possible workaround here is to use a string token (unorthodox but will get the job done)
