### ISSUE TITLE
mat-slider thumb does not move with track when setting value in setInterval callback on Chrome

### ISSUE THREAD

**Issue by chriskinzel** [angular/material2#8495]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Slider thumb should move with the track

#### What is the current behavior?
Slider track moves correctly but slider thumb does not move unless the mouse is clicked or moved

#### What are the steps to reproduce?
https://plnkr.co/edit/lvvMNOF2WGMl3wH2unLi?p=preview

All relevant code is in slider-configurable-example.ts and slider-configurable-example.html

Set the value of a mat-slider in a setInterval callback:
```typescript
@ViewChild('someSlider') mySlider;

setInterval(() => {
    mySlider.value += 0.01; // Put some reasonable step value here
}, 33);
```

On Safari, Firefox, etc... the slider thumb and track will move at a constant rate together as would be expected.

On Chrome the slider track moves at a constant rate but the slider thumb will be stationary unless the mouse is being moved around or clicked.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All / latest

**Comment by mandarini** [comment]
Hi chriskinzel, when you set a longer interval the issue disappears. So, it seems to be a rendering issue. If you set your interval to anything above 50ms (yours is at 30ms), the animation runs smoothly, and the thumb is not jumping around. I know that this is not an issue solver, but still, the issue seems to be in very frequent intervals, not in intervals in general.

**Comment by chriskinzel** [comment]
HI mandarini, even with an interval of 50ms or longer the thumb is still shaky and the animation is not smooth. I have narrowed the cause of the issue down to this style:
`.mat-slider-thumb-container {
  position: absolute;
  z-index: 1;
  transition: transform $swift-ease-out-duration $swift-ease-out-timing-function;
}`

If you remove the transition property the movement is smooth but this is not quite a fix since the thumb does not animate when larger value changes occur such as when the value wraps back to the beginning.

**Comment by mmalerba** [comment]
@chriskinzel have you tried adding the `mat-slider-sliding` class to the slider when you start this animation and then removing it when the animation is finished? This is the class we use to disable CSS animations when the user is dragging the thumb, it should probably work for this use case too.

**Comment by timmoy** [comment]
I've been doing some experimentation myself and was wondering if something like this

https://github.com/timmoy/material2/blob/86ebc154af3fd0a75c509911ad55ecad36eb182f/src/lib/slider/slider.ts#L222-L235

would work?

I had tried in other areas like in the [container styles getter](https://github.com/timmoy/material2/blob/86ebc154af3fd0a75c509911ad55ecad36eb182f/src/lib/slider/slider.ts#L390-L400), but those proved unsuccessful as the class didn't apply correctly or persist since it got overridden elsewhere.

So rather than try to add the class to it via dom or css, it seemed appropriate to use the isSliding member to turn it on/off. Hopefully I'm not going off into the wrong direction here.

**Comment by mmalerba** [comment]
@timmoy I'd be wary of messing with the `_isSliding` property. Its internal and not really meant to be messed with. If you're having issues with the `mat-slider-sliding` class getting removed prematurely you can just make your own CSS class that does the same thing but you control when it gets added and removed. All the class does is set `transition-duration: 0` on a few things: https://github.com/angular/material2/blob/HEAD/src/lib/slider/slider.scss#L155

**Comment by timmoy** [comment]
I've made a new commit which uses a new custom css class and a few new properties to determine when to turn it on via what seems to be the class binding section [here](https://github.com/timmoy/material2/blob/10e2e412da7b29e3ea0bea24781899a26b9b8991/src/lib/slider/slider.ts#L120-L129).  

[Commit](https://github.com/timmoy/material2/commit/10e2e412da7b29e3ea0bea24781899a26b9b8991)

**Comment by mmalerba** [comment]
You should be able to do it without modifying the slider code at all. I don't think its a change we want to in the library since most people don't animate their sliders with `setTimeout`.

If you want to apply the fix to all sliders in your app you can make a directive that selects on `mat-slider` and manages the extra class

**Comment by timmoy** [comment]
I see, that makes sense since it does seem like this is mainly an edge case.

I am not affected by this issue, but was seeing if I could contribute PR for this issue, but it seems like a PR might not be needed at all?

Perhaps this issue could be closed if @chriskinzel is no longer experiencing this problem?

**Comment by mmalerba** [comment]
Yeah I don't think there's anything to change in the library for this. @chriskinzel feel free to open a new issue if the solution outlined above doesn't work for you. Closing this issue for now.

**Comment by Polyterative** [comment]
I also have this issue
demo: https://imgur.com/a/Cc4RBzy
