### ISSUE TITLE
md-step cut off ripple effect

### ISSUE THREAD

**Issue by milanstamenkovic** [angular/material2#8518]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Visible ripple effect in all positions

#### What is the current behavior?
Md-step cut off ripple effect of checkbox close to edges

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/animations": "^4.4.4",
"@angular/cdk": "^2.0.0-beta.11",
"@angular/common": "^4.4.4",
"@angular/compiler": "^4.4.4",
"@angular/core": "^4.4.4"
"@angular/material": "^2.0.0-beta.10",

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/9901106/32961540-35c2c4a6-cbc9-11e7-873d-001e82ef4e69.png)

**Comment by josephperrott** [comment]
This is caused by the CSS rule in stepper:
```
.mat-horizontal-stepper-content {
  overflow: hidden;
}
```
Since the `mat-checkbox` is sitting in the upper left corner of the space of the stepper's content, it does not show the ripple overlay as they do not offset space. An option would be to put a margin around the `mat-checkbox` to create the offset space needed.

**Comment by ricardosaracino** [comment]
weak hack

.mat-horizontal-content-container {
  padding: 0 20px !important;
  margin: 0 -20px !important;
}
