### ISSUE TITLE
ng-container cannot work with mat-form-field

### ISSUE THREAD

**Issue by Teamop** [angular/material2#8626]
#### Bug, feature request, or proposal:
Currently, I'm not sure it's a bug or it's intended:
When use ng-container with mat-form-field, got this error: field must contain a MatFormFieldControl.
#### What is the expected behavior?
work properly.

#### What is the current behavior?
Error: field must contain a MatFormFieldControl.

#### What are the steps to reproduce?
I just use the "Basic Input" of material.angular.io to reproduce.
[plunker](https://plnkr.co/edit/RrCG3outlhMnldvW6oLg?p=preview)
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.2
Angular Material 5.0.0-rc.1
Typescript 2.4.2

#### Is there anything else we should know?
I also tried to add ngProjectAs="input[matInput]" to ng-container, it still cannot work even though I'm not sure I used it correctly.

**Comment by jelbourn** [comment]
This is working as expected. The form-field has to be able to query for its control, which is cannot do through a template outlet.

**Comment by bmcbarron** [comment]
I have a dynamically generated form, where I use ngSwitchCase to choose between input, textarea, mat-select, and custom form fields. Despite the different field types, there is a lot of shared behavior at the mat-form-field level: flex settings, css classes, mat-label, mat-hint, and even matSuffix buttons. Because of the restriction identified by this issue, each field type must include this boilerplate.

I understand that the issue is a limitation of angular, and not the material widgets. Are there other suggestions for how to minimize this repetition? The boilerplate copies continues to grow worse, as the form acquires new custom input components for new data types.

**Comment by asleire** [comment]
A solution that works for my use case is having templates with the `ngProjectAs` attribute inside `mat-form-field`

Plunker: https://plnkr.co/edit/O3oQH7jrEfsy7eKuVx30?p=preview
