### ISSUE TITLE
Slider - Invert, does not invert keyboard action

### ISSUE THREAD

**Issue by Cyberdada** [angular/material2#8633]
#### Bug, feature request, or proposal:

If you use the invert attribute on the slider control, keyboard left arrow will move slider to the right, and keyboard right arrow will move the slider to the left

#### What is the expected behavior?

Position on slider should move in the same direction as the keyboard arrow, regardles of if it is inverted or not. 

#### What is the current behavior?

see above 

#### What are the steps to reproduce?

goto 
https://material.angular.io/components/slider/examples
check the inverted box, 
and try to move slider position with arrow keys

#### What is the use-case or motivation for changing an existing behavior?
It is confusing to the user if pushing the left arrow moves current slider position to the right

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
using 
angular/material: 5.0.0-rc.1
angular: 5.0.3
chrome 62.0.3202.94

**Comment by jelbourn** [comment]
@mmalerba is this working as intended? I vaguely recall this being what was necessary for a11y

**Comment by mmalerba** [comment]
yep, users using a screen reader will not know that the slider is inverted, it's a purely visual thing, therefore we leave the normal meaning of left = decrement, right = increment.

@Cyberdada If you do want the behavior you're describing, you could try placing the slider in an RTL container instead of inverting it. Here it will have the behavior you described, since left = increment in RTL (https://stackblitz.com/edit/angular-eedhhy?file=app/slider-overview-example.html)
