### ISSUE TITLE
Unresizable Spinner because of width & height set explicitly to 100px

### ISSUE THREAD

**Issue by YoannBureau** [angular/material2#8835]
#### Bug, feature request, or proposal:
Bug: Spinner now have a style tag in its generated html that is ```style="width: 100px; height: 100px;"```, so we can't change its size by an external css file anymore.

#### What is the expected behavior?
We should be able to resize the spinner by css

#### What is the current behavior?
We can't resize the spinner by css

#### What are the steps to reproduce?
Just add a new mat-spinner to a component and see the DOM output

#### What is the use-case or motivation for changing an existing behavior?
It is a regression: it was set before by its css class

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Angular Material 5.0.0.rc-2

#### Is there anything else we should know?
This will trigger some regressions on early adopter's projects

**Comment by donroyco** [comment]
Have you checked #7653?

**Comment by YoannBureau** [comment]
@donroyco yep, I use that now. But I still think it is weird to have this "css style html prop" set. It is the only one angular material component with this dirty prop setting (instead of using css selectors)

**Comment by chuihinwai** [comment]
Agree with @YoannBureau. This also prevents setting a global width and height for all loading indicators

**Comment by jelbourn** [comment]
This is working as intended. Setting the size of the spinner through code was necessary in order to make the animation of the spinner based entirely on css animations (instead of javascript animations). This allows the spinner to work when doing SSR.

Feel free to open a new issue for a feature request for an option to set the size globally (would be be some provider).
