### ISSUE TITLE
[Chip] Color is not applied when using *ngFor

### ISSUE THREAD

**Issue by ctwoolsey** [angular/material2#8888]
#### Bug:
Color does not get applied to "mat-chip" if using *ngFor and selected is not set to "true".

#### What is the expected behavior?
I would expect: 
```
<mat-chip *ngFor="let chip of availableColors" [color]="chip.color">
          {{chip.name}
</mat-chip>

```
To work the same as:
```
<mat-chip *ngFor="let chip of availableColors" selected="true" [color]="chip.color">
          {{chip.name}}
</mat-chip>
```

#### What is the current behavior?
In the above examples modified from https://material.angular.io/components/chips/examples
The first example does not apply color to the chips
The second example does.

#### What are the steps to reproduce?
http://plnkr.co/edit/cboYDev2KVgN6d0eSFkd?p=preview

**Comment by crisbeto** [comment]
It seems to be because the theming is only scoped to selected chips: https://github.com/angular/material2/blob/master/src/lib/chips/_chips-theme.scss#L44. @tinayuangao do you remember the reasoning behind it?

**Comment by tinayuangao** [comment]
This is working as intended. 
I think we need a way to differentiate selected chips from unselected chips. 
In our docs we said "The <b>selected</b> color of an `<mat-chip>` can be changed by using the `color` property. " See https://github.com/angular/material2/blob/master/src/lib/chips/chips.md

**Comment by AndrewEckart** [comment]
@tinayuangao What is the difference between a selected chip and a focused chip?

Currently, the color is applied to the most recently added chip because it is considered "selected". This remains the case even if I manually click or use arrow keys to focus an earlier chip (giving it a corresponding shadow). Now there are two visual indicators that a chip is focused on two different chips.

![image](https://user-images.githubusercontent.com/5485577/34842901-eeb2abc0-f6da-11e7-8891-c116bdd31ec1.png)

If this is the intended behavior, it seems counterintuitive. What exactly is a "selected" chip if not the one which currently has focus and can be deleted?
