### ISSUE TITLE
Angular 2 mat-input type = number is not working in IE 11

### ISSUE THREAD

**Issue by lokeshnagpal** [angular/material2#8923]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-input type=number should accept only number.

#### What is the current behavior?
It is accepting string in IE and increment & decrement button is not showing in IE. But it is working fine in chrome only accepting number.

#### What are the steps to reproduce?
Try in the below link and give 
<input matInput type="number" placeholder="Favorite food" value="Sushi">
  </mat-form-field>
https://stackblitz.com/angular/jrldlmvxlox?file=app%2Finput-overview-example.html

#### Is there anything else we should know?
No

**Comment by julianobrasil** [comment]
This is actually the (bugged?) behavior in IE11 (it's how IE11 renders `<input type="number">` when you use raw HTML).

Open this w3schools link in IE11 and you'll notice the lack of the arrows: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_number_step

**Comment by jelbourn** [comment]
Closing since this seems to be the behavior of IE on its own.

**Comment by dannye** [comment]
I understand that this is the behavior of IE, but wouldn't it be possible (and I would argue, _desired_) for Material to support a `mat-numeric-input` or something similar, so that non-numeric key presses are rejected, in a browser-agnostic way? It seems like an unfortunate thing for us to have to hack around.
