### ISSUE TITLE
[Spinner] Flickering on Chrome 63/64 Linux

### ISSUE THREAD

**Issue by pitops** [angular/material2#8984]
#### Bug, feature request, or proposal:
Progress spinner animation fix

#### What is the expected behavior?
To not flicker but instead have constant and balanced animation

#### What are the steps to reproduce?
Just go to the material.angular.io section of the progress spinner and observe the spinner. It flickers. Tested on Chrome 63 and Firefox 57. Note that it can happen at random intervals and not constantly.

It is best observed when you open a new tab -> material.angular.io -> progress spinner

**Comment by donroyco** [comment]
I can't reproduce this behaviour. What is your setup?

Chrome 62.
![chrome-62-animation-spinner](https://user-images.githubusercontent.com/1763537/33982461-e7a0b542-e0b0-11e7-9aec-d32a9cf5383e.gif)

Chrome 63
![chrome-63-animation-spinner](https://user-images.githubusercontent.com/1763537/33982492-055a507a-e0b1-11e7-9ad6-fc026d0ab8bc.gif)

**Comment by pitops** [comment]
@donroyco under further investigation, it seems to happen on linux machines (only checked a Virtual windows machine and it works fine). However getting deeper, firefox 45 ESR displays the spinner just fine but chrome 62/63 on multiple linux machines does not. Neither Firefox 57.

**Comment by eTallang** [comment]
I'm not sure if it's the exact same issue, but I experience flickering with the progress spinner as well. It can happen in the material.angular.io example as well, but I was not able to record it, since it only happens occasionally, without any apparent pattern.

![distortion](https://user-images.githubusercontent.com/24789715/34150955-29237d5e-e4aa-11e7-9a29-f2a81e682e31.gif)
This is recorded from my own application. If you pause the gif on the flicker, it is apparent that the circle changes to a oval shape for 1 frame:
![image](https://user-images.githubusercontent.com/24789715/34151004-53014570-e4aa-11e7-8dc8-6167a8f1eb0c.png)

**Comment by pitops** [comment]
@eTallang this is exactly what happens in our case. Thanks for providing an animation of it.

**Comment by kordeviant** [comment]
me too

**Comment by kuwas** [comment]
👍 

I've seen this flickering for months now, only decided to look for a solution today.

**Comment by Lakston** [comment]
Here is another gif example, I'm guessing it just happens when data is loaded in the background [as suggested in the other issue](https://github.com/angular/material2/issues/9050)

![material-spinner](https://user-images.githubusercontent.com/17677346/35033335-9683f60e-fb6a-11e7-857f-1d12b064b6b7.gif)

We've also experienced the 'ellipse' bug shown in @eTallang 's post on our app.

**Comment by pitops** [comment]
@crisbeto can you please provide an ETA on this?

**Comment by pitops** [comment]
@michaelthe Your solution is simple and elegant - works great!
