### ISSUE TITLE
Can't bind to 'floatLabel' since it isn't a known property of 'mat-form-field'.

### ISSUE THREAD

**Issue by jeffersonvivanco** [angular/material2#8996]
I set [floatLabel]="never" in the mat-form-field element and I get this error. 
Can't bind to 'floatLabel' since it isn't a known property of 'mat-form-field'.
I tried the example in the Material2 website and I'm using angular 5 with the
angular cli.

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to our community at StackOverflow, Angular Material mailing lists, Gitter, etc. We try to keep our issues here only open for bugs and feature requests.

**Comment by bitsmuggler** [comment]
@jeffersonvivanco I had the same error. 

My fix was: Upgrading @angular/cdk from 5.0.0-rc.2 to "@angular/cdk": "^5.0.0" and  @angular/material from 5.0.0-rc.2 to "@angular/material": "^5.0.0

The floatLabel is in angular/material since 5.0.0-rc.3. See this commit:  https://github.com/angular/material2/commit/d6fec3573cbc854d5bf67d920c5b0f8a6eef0c86

**Comment by jeffersonvivanco** [comment]
thank you @bitsmuggler  !!
