### ISSUE TITLE
Button in select display in wrong way

### ISSUE THREAD

**Issue by masza** [angular/material2#9155]
#### Bug, feature request, or proposal:
BUG
I try to display button in angular material select and I use this code:

```
<mat-select #placeNameControl="ngModel" placeholder="Place name">
  <mat-option >
    Add new place name
  </mat-option>
  <mat-option *ngFor="let addedPlaceName of addedPlaceNames" [value]="addedPlaceName">
    {{addedPlaceName}}
    <button mat-icon-button>
        <mat-icon>remove</mat-icon>
    </button>
  </mat-option>
</mat-select>

```

And this works, but when I select one of the options, this display selected element and name of the icon like this: 
![zrzut ekranu 2017-12-28 o 17 14 09](https://user-images.githubusercontent.com/17169222/34416562-612ade8a-ebf4-11e7-817e-711f041a91be.png)

**Comment by julianobrasil** [comment]
Inside the Button tags and surrounding the ícone name you need mat-icon tag:

```html
 <button mat-icon-button>
    <mat-icon>remove</mat-icon>
 </button>
```

**Comment by masza** [comment]
Of course my mistake. I tried different solutions and by mistake pasted wrong snippet. I already edit this.

Unfortunately this:
`<button mat-icon-button>
    <mat-icon>remove</mat-icon>
 </button>`

and this:
```
  <button type="buttton" mat-icon-button>
       <i class="material-icons">remove</i>
  </button>
```
give the same result. Icons display as expected when select shows dropdown.

**Comment by julianobrasil** [comment]
The trigger value is a string, that's why the icon isn't shown after selection.

But if you desire to remove and option (I don't know whether the `remove` icon is a random one or you really want to remove an option by clicking on the icon), you can try something like this demo: https://stackblitz.com/edit/angular-select-icon

But you'll have to do some work to remove when clicking on the icon in the opened panel (the example allows you to remove after the panel is closed).

**Comment by jelbourn** [comment]
Having a button inside of an option would be considered invalid and not something we'd support.

**Comment by zshlomyz** [comment]
Select with 2-way value binding cause the selected option to not contains the icon - 
[https://angular-select-icon-ucgq7q.stackblitz.io](https://angular-select-icon-ucgq7q.stackblitz.io)
I did something wrong?
