### ISSUE TITLE
MdCheckbox does have different size then in Material docs

### ISSUE THREAD

**Issue by palpatine1991** [angular/material2#9244]
#### Bug, feature request, or proposal:
MdCheckbox component have different size then in the Material documentation. I found this issue when I was comparing Material2 checkbox and material-components-web checkbox.

#### What is the expected behavior?
I am expecting MdCheckbox to have the same sizing as is in documentation: https://material.io/guidelines/components/selection-controls.html#selection-controls-checkbox which is 18px.

I believe that this mistake/decision was made to unify the size with MdRadio which is 20px wide.

![checkbox](https://user-images.githubusercontent.com/2939313/34602753-6476f30e-f201-11e7-9512-0e6fb3692fb2.png)
![radio](https://user-images.githubusercontent.com/2939313/34602757-69319d36-f201-11e7-96ca-16bda978defa.png)

#### What is the current behavior?
Current MdCheckbox have 20px.

#### What is the use-case or motivation for changing an existing behavior?
20px checkbox looks too huge. Also this library should follow the documentation.

**Comment by donroyco** [comment]
Where [in the docs](https://material.io/guidelines/components/selection-controls.html#selection-controls-checkbox) is it stated that it should be `18px`? I don't see a writeup of exactly that number.

**Comment by palpatine1991** [comment]
The exact sizing is not included in material guidelines by word but there are images of the checkbox and all of them are of the size of 18px.

https://material.io/components/ in here they say that they are implementing the pixel-perfect implementation of the spec. And I believe that following that rule may help to keep the consistency of all material design libraries across the internet.

![pixels](https://user-images.githubusercontent.com/2939313/34616957-14752572-f23a-11e7-8399-107870ec8bde.png)

**Comment by jelbourn** [comment]
Would need to confirm the different. Our checkbox was originally written _by_ someone on the Material Design team, so I'd be surprised if it was off. If it is different, this would be a major breaking change that we might decide not to peruse.

**Comment by Philip-Sultanescu** [comment]
I agree with the 18px size instead of 20px.
Also the $_mat-checkbox-ripple-radius should be 24 instead of 25, which means a total ripple size of 48px.
This way it follows also the **table guidelines** (#9152) where the row height is 48px.
![table checkbox](https://user-images.githubusercontent.com/30979663/35184563-a5633970-fdf7-11e7-8c7b-3bac3abc4691.png)


A checkmark of 18px will also better align with the label.
<img width="115" alt="18px checkbox" src="https://user-images.githubusercontent.com/30979663/35184550-6f5ea774-fdf7-11e7-9aab-05e6c03e381b.png">

As opposed to the 20px checkbox that we have now, where clearly the bottom is offset.
<img width="115" alt="20px checkbox" src="https://user-images.githubusercontent.com/30979663/35184551-6f757ce2-fdf7-11e7-93ef-7be7f7d34c3d.png">

I think the intention of the designer was to align the check sign in the middle of the Checkbox with the label text, including for the Radio (note that radio is not normally used in Tables so it won't be an issue there).

**Comment by jelbourn** [comment]
This should be resolved as of v7
