### ISSUE TITLE
[Paginator] Add functionality to jump to first and last page

### ISSUE THREAD

**Issue by Chris2011** [angular/material2#9278]
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
There should be 2 buttons like << and >> to jump to the first and last page.

#### What is the current behavior?
There is no button for this. There is only a button for < and > prev and next.

Items per page: 10    -    1 - 10 of 100 < >

#### What is the use-case or motivation for changing an existing behavior?
If you have a long list, often it is needed to jump to the end and back to the first page/first items.

Items per page: 10    -    1 - 10 of 100  **<<**  < >  **>>**

#### Is there anything else we should know?
https://github.com/angular/material2/issues/7615 - as a reference.

**Comment by lharries** [comment]
Hi @andrewseguin I'd be keen to give this one a go

**Comment by andrewseguin** [comment]
Sounds good to me, let's set the requirements and iterate from there:

- Needs to be optional (turned on through some `Input()`)
- Should be able to draw up some icons that match the material icon (can't use the icons directly, should be done with divs): https://material.io/icons/#ic_first_page and https://material.io/icons/#ic_last_page
- Needs tests
- Needs to be added as an example in documentation

**Comment by lharries** [comment]
I agree with the above requirements. 

For tests would it just be the spec tests? I don't see the paginator in the e2e tests.

**Comment by andrewseguin** [comment]
Yup just some spec unit tests would suffice, try to consider the main case and edge cases, e.g. the jump-to-first button should be disabled when on the first page

**Comment by lharries** [comment]
Whilst doing the above I found two (non-breaking) bugs in the spec file. Would it be best to do them as separate PRs or in the same PR that I'm currently working on when I have completed this feature?

1. A test was wrongly named. [See fix here](https://github.com/lharries/material2/commit/8e2197dc13f3e25815fc38690af00009dd4a1cb5)
2. There was an off-by-one error where the index of the last page was wrongly calculated.  
This happened in both the `goToLastPage()` method and in the following test `'should disable navigating to the next page if at last page'`.  
In headless chrome, it was going to page index 10 to check that it could no longer navigate forward. Whilst there are 10 pages they are starting from index 0 and therefore the last page is in fact index 9. [See fix here](https://github.com/lharries/material2/commit/dc98333b20559062f8c291ac41edb0625905ab6c)

The bug fix for 2 is required in order to write a valid test for the current feature.

**Comment by andrewseguin** [comment]
Good catch - if you submit the fixes via separate PRs, that'd be a lot easier for us.

**Comment by lharries** [comment]
Thanks! And will do

**Comment by lharries** [comment]
Do I need to create an issue for them or straight to the PR?

**Comment by andrewseguin** [comment]
No issue needed, just a PR will do

**Comment by lharries** [comment]
Will do. 

On a side note: for the Component attribute of showing/hiding the first and last buttons would you have any recommendations on naming? I am thinking `hideFirstLastButtons`, which would be similar to the current `hidePageSize`?

**Comment by andrewseguin** [comment]
Naming tends to be one of the harder parts of these sort of features.

By default, the paginator shouldn't show the first/last buttons anyways since the material spec doesn't include them. I imagine the flag would be more like `showFirstAndLastButtons`.

Curious how the interaction would look if you had a paginator for an "infinitely" long list. You'd want to make sure you can easily hide the Jump to Last button since it doesn't make sense.

**Comment by lharries** [comment]
Ok, I'll make the first/last buttons hidden by default and implement the `showFirstAndLastButtons` attribute.

Shall I add `showFirstButton` and `showLastButton` too to allow the control such as with the "infinitely" long list?

**Comment by andrewseguin** [comment]
Since its a pretty uncommon case and I'd lean more towards keeping a thinner API surface, let's leave those off. In that case it should be fairly trivial to just add a `display: none` to the last button. 

If it comes up from users in the future, we can always add it in then

**Comment by lharries** [comment]
Great point

**Comment by lharries** [comment]
Is there a best practice for doing multiple PRs for the same file to avoid the conflicts on merge?

**Comment by lharries** [comment]
I have added the first and last buttons to the [demo app](https://github.com/lharries/material2/commit/cd1645ddc626a7352e412e5e8e49ebef27198adc), in a new table, and to the [material-examples](https://github.com/lharries/material2/commit/f98176d9534cf74b2bcb92e7b3ccb73b0b7c52c3), to the existing table, is this correct or would there be a better way to do this.

Additionally, would we need to submit a PR to the [material.angular.io docs](https://github.com/andrewseguin/material.angular.io)?

Here's where I'm currently at:
- [x] Needs to be optional (turned on through some Input())
- [ ] Should be able to draw up some icons that match the material icon (can't use the icons directly, should be done with divs): https://material.io/icons/#ic_first_page and https://material.io/icons/#ic_last_page
- [x] Needs tests
- [ ]  Needs to be added as an example in documentation 

I'll have a look into the icons tomorrow but the functionality and all the tests are done 😄

**Comment by lharries** [comment]
I came across another bug, where the classes of the increment and decrement icons were wrongly named. I have implemented a fix in a separate PR #9597

**Comment by lharries** [comment]
I believe I have managed to implement the icons correctly with divs:
![image](https://user-images.githubusercontent.com/22766134/35396143-08234722-01e4-11e8-90f7-b3d344f29b19.png)

I will submit a PR for the feature now, let me know if there is anything you'd like changed.

**Comment by andrewseguin** [comment]
Awesome looks great!

When we launch the material.angular.io site with these changes, the script we use will automatically pull in your docs and example

**Comment by lharries** [comment]
Thanks very much!

Not sure if you saw my previous message: "Is there a best practice for doing multiple PRs for the same file to avoid the conflicts on merge?"

The new PR will include the changes made in the previous 3 bug fixes

**Comment by andrewseguin** [comment]
Ah right - go ahead and include the fixes in your PR and then write in the description that they include fixes from the other PRs and that the PR is blocked until the others are in. Since they are small I imagine they will be merged fairly quickly. Once they are in, you can rebase and remove the disclaimer on your final PR

**Comment by lharries** [comment]
Thanks Andrew, will do!

**Comment by willshowell** [comment]
This is awesome. Great work @lharries!

**Comment by btroncone** [comment]
@lharries I'm seeing this in Edge on first render:

![image](https://user-images.githubusercontent.com/5085101/35930844-00803706-0c01-11e8-9b76-0fc6cb929e19.png)

Once you click on the button it corrects:

![image](https://user-images.githubusercontent.com/5085101/35930922-3c2697e6-0c01-11e8-8d5f-c4e3cde6bc79.png)

Any ideas?

**Comment by lharries** [comment]
@btroncone apologies for that. I'll set up an Edge development environment and get this fixed

**Comment by btroncone** [comment]
@lharries No worries! Had QA catch it in one of my projects and wanted to make you aware. I messed around with it briefly but didn't reach a solution I was happy with, hopefully you will have better luck!

**Comment by lharries** [comment]
@btroncone I'll create an issue and see if we can get it fixed

**Comment by btroncone** [comment]
@lharries Awesome, thanks for the update!

**Comment by tomliem** [comment]
Hi how to install this package @lharries ? is it by the default npm install --save @angular/material?
