### ISSUE TITLE
Multilevel vertical menu

### ISSUE THREAD

**Issue by ipchaube** [angular/material2#9286]
#### Bug, feature request, or proposal:
 Looking for Multilevel vertical menu but not sure how I can do it with mat tag. Please see if it can be available, if already available how I can do it.

#### What is the expected behavior?
Multilevel vertical menu(Collapsible and expendable)

#### What is the current behavior?
No options

#### What are the steps to reproduce?
Providing a StackBlitz/Plunker (or similar) is the *best* way to get the team to see your issue. <br/>
Plunker starter (using on `@master`): https://goo.gl/uDmqyY<br/>
StackBlitz starter (using latest `npm` release): https://goo.gl/wwnhMV<br/>
Using this doc https://material.angular.io/guide/getting-started

#### What is the use-case or motivation for changing an existing behavior?
Better user experience

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular-4 and following this link https://material.angular.io/guide/getting-started 

#### Is there anything else we should know?
N/A

**Comment by jotatoledo** [comment]
You mean something like this? https://material.angular.io/components/menu/overview#nested-menu

**Comment by andrewseguin** [comment]
Please refer all troubleshooting questions to our community at StackOverflow, Angular Material mailing lists, Gitter, etc. We try to keep our issues here only open for bugs and feature requests.

**Comment by ipchaube** [comment]
Hi Jota,
I need similar but like tree and not a popup. Expand and collapse on click with icons.
Like https://jmouriz.github.io/angular-material-multilevel-menu/demo/demo.html

**Comment by Srikanthasv** [comment]
Hi All,
We also require similar kind of Multi level Vertical Menu with Toggle and collapse events.  same like the below
https://jmouriz.github.io/angular-material-multilevel-menu/demo/demo.html

**Comment by gustavogsimas** [comment]
Did you guys manage to make this?

**Comment by Tryforce** [comment]
I put together a little example. It mimics (tries to at least) gmail's "mini" sidenav that is still visible when its collapsed. Stackblitz below.
https://stackblitz.com/edit/material-sidenav-example?file=app%2Fsidenav-autosize-example.html

It'd be nice if there was a more out of the box way to achieve this. We're trying to compare the effort into implementing material vs other component frameworks and stuff like Clarity is super appealing because they offer functionality like this with much less effort. For example:
https://vmware.github.io/clarity/documentation/v0.12/vertical-nav/basic-structure/charmander

**Comment by kubersingh** [comment]
PrimeNG may also help: https://www.primefaces.org/primeng/#/panelmenu

**Comment by alexmantaut** [comment]
Does something like this work? https://stackblitz.com/edit/dynamic-nested-sidenav-menu?file=app%2Fnav-item.ts (not my code, just a stackblitz I found)

**Comment by ashokona** [comment]
Hi @alexmantaut , your solution was too good, but how can make a the selected item active even if its a sub menu item.

**Comment by Splaktar** [comment]
@alexmantaut @LoganDupont @gxg10 I've added that functionality to the first section (DevFestFL). It required defining a lot more routing information in the routing module and in the NavItem array. I only did it for that one section because the rest is just duplicate filler. It will obviously make more sense with your apps **real** nav structure.

Updated Stackblitz: https://stackblitz.com/edit/dynamic-nested-sidenav-menu?file=app%2Fapp-routing.module.ts

**Comment by gxg10** [comment]
@Splaktar I think i was misunderstood. I was looking for the following behaviour: i would browse through the first section, expanding another menu, going for example for a level 3 menu item: DevFestFL > Speakers > Michael Prentice > Create Enterprise UIs. When i click Create Enterprise UIs the menu would close , routing me to my page but when i would open the menu again the menu would be in the original position(unexpanded). Now it points me what menu i clicked. Kind regards

**Comment by BastiOfBerlin** [comment]
@Splaktar Great work! I'd love to see this as a ready-to-use npm package <3

**Comment by Splaktar** [comment]
@gxg10 https://stackblitz.com/edit/dynamic-nested-sidenav-menu-reset-on-nav?file=app%2Fmenu-list-item%2Fmenu-list-item.component.ts seems to do what you are asking. I don't really recommend it as a general UI/UX pattern, but if you need it for some specific reason, then go for it 😄 

The only real change is this
```ts
 ngOnInit() {
    this.navService.currentUrl.subscribe((url: string) => {
      this.expanded = false;
      this.ariaExpanded = false;
    });
  }
```

**Comment by Splaktar** [comment]
@BastiOfBerlin I'm glad that you found it helpful. I've started moving the patterns that [I've presented](https://www.youtube.com/watch?v=OU6z3IKmyNI&list=PLBge-_7rhfzRV4pl-lM_OeavC8_P8C_-M&index=2&t=2s) over to a library (https://www.npmjs.com/package/@devintent/dev) in my spare time, but so far I've only got the Responsive Button Bar. I'll try to make the dynamic nested sidenav my next priority, but I'm also happy to accept and assist with community contributions.
