### ISSUE TITLE
sharedModule in individual apps

### ISSUE THREAD

**Issue by molikh** [angular/material2#9294]
#### Bug:
can't share material components through sharedModule in individual apps.

#### What is the expected behavior?
i already used sharedModules to share my component from an template app through my other individual apps and everything works fine.
the main idea is, create some custom components like <input-email></input-email> with angular material components that handle everything i want from an email input or ... and then i can use this tested component with minimum work and errors in all of my apps.

#### What is the current behavior?
but when i'm trying to use angular material components inside my components i face this error:
Error: StaticInjectorError[ElementRef]: 
  StaticInjectorError[ElementRef]: 
    NullInjectorError: No provider for ElementRef!
    at _NullInjector.get (core.js:993)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveNgModuleDep (core.js:10878)
    at NgModuleRef_.get (core.js:12110)
    at resolveDep (core.js:12608)
BtnComponent.html:3 ERROR TypeError: Cannot read prop

* everything works fine if i use this sharedModule with components inside in the same app (folder) but when i try to use in other app ( completely different locations ) it gives me this error.
so there is no problem in the way i share my module i think so.

#### What are the steps to reproduce?
there is more details:
https://stackoverflow.com/questions/48124479/sharedmodules-into-multiple-completely-different-apps

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
i'm using latest version of all . 
i'm creating new app.

thanks

**Comment by andrewseguin** [comment]
Is this a bug in Material? Looks like you are having trouble sharing a module between apps? If this is an issue with Material, please re-open with a stackblitz of what you are trying to achieve. If this is an Angular issue, please open an issue with angular/angular instead. Right now this looks to be out of the scope of the Material library

**Comment by molikh** [comment]
that is what i'm trying to figure out . let me explain again.
i have templateApp and mainApp.
i have created a sharedModule in templateApp contains a component with a <h1> tag then I have imported this sharedModule my mainApp and works fine.(so it's not angular problem )
But then i use mat-btn inside that component insted of <h1> now it gives me error "elementRef".
**Notes** : 
* if i use this sharedModule inside templateApp it is working fine but when i use in mainApp gives me error.
* if i want to import MatButtonModule to my mainApp when i already imported sharedModule it gives me "dublicate component" error , so material btn module is defined.

**Comment by damienwebdev** [comment]
@andrewseguin I'm not sure that this is necessarily a bug in material, but I think I can explain the use case, as well as what I'd like to see happen.

# Bug (docs?)

#### What is the expected behavior?
When I create a new module which utilizes Angular Material components, package it for public usage, import my module (as below), and then use the component, I should see my component in all it's angular material glory.

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    ComponentsModule //This is my custom module
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

#### What is the current behavior?
When I try to do the above:
1. Package my module
2. Import my module (which only uses MatButtonModule)
3. Use my component
4. See in console:

```
ERROR Error: StaticInjectorError(AppModule)[MatButton -> ElementRef]: 
  StaticInjectorError(Platform: core)[MatButton -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
```

#### What is the use-case or motivation for changing an existing behavior?
Ideally, I'd like to create a super-set of components to Angular Material. I'd like to follow the "O" in SOLID principles, and extend the Angular Material library. When I extend the library, I'd like to expose my modules which utilize Angular Material components.
