### ISSUE TITLE
Feat (Mat-Slider) : Focus method and blur Output

### ISSUE THREAD

**Issue by seedy** [angular/material2#9332]
#### Bug, feature request, or proposal:
Feature request : 
Implement Focus and Blur on mat-slider

#### What is the expected behavior?
- Allow mat-slider with thumbLabel to activate thumbLabel programatically on focus via MatSlider class
- Allow mat-slider to notify of blur via MatSlider class

#### What is the current behavior?
Need to use an ElementRef instead of a reference to MatSlider

#### What is the use-case or motivation for changing an existing behavior?
Uniformisation of component's api

#### Is there anything else we should know?
I love ViewChildren with specific class component matching!

**Comment by julianobrasil** [comment]
@seedy, what do you mean exactly? Isn't it possible to set the focus programmatically to the slider to make it show the thumblabel autommatically?

Something like `matSlider.nativeElement.focus()`?

I have the same question concerning blur... `<mat-slider (blur)='someMethod()'></mat-slider>` doesn't work?

I mean... I din't get whether you are thinking of forcing the thumbLabel to be visible _even without getting focus_ or just the regular behavior programmatically (show the thumb label when it gets focused).

Also the blur.... you are thinking of a simple`@Output` or an observable?

**Comment by julianobrasil** [comment]
Just to better understand it.

### Case 1: you just want to set focus programmatically and get notified of blur event

You can do it with the actual MatSlider:

```html
<mat-slider thumbLabel max="30" value="10" (blur)="someMethod()"></mat-slider>
```

```ts
@ViewChild(MatSlider) _slider: MatSlider;

  ngAfterViewInit() {
    this._slider._elementRef.nativeElement.focus()
  }

  someMethod() {
    alert('you just lost focus');
  }
```

### Case 2: you want to show the thumb label _even without setting the focus to the slider_. And you want to get notified of blur event by an observable.

```html
<mat-slider thumbLabel max="30" value="10"></mat-slider>
```
You want a way to do something like:

```ts
@ViewChild(MatSlider) slider: MatSlider;

...
    // to show the slider thumb label
    this.slider.showThumbLabel(true);

    // to hide the slider thumb label
    this.slider.showThumbLabel(false);

    // to get notified of blur
    this.slider.blur.subscribe(() => alert('I lost focus'));
```

If you are thinking of case 2... well, I could give it a shot, but dispite the fact that this issue was labeled as "good for community contribution", I'm affraid that this kind of feature should be added by someone in the core team... I mean, it doesn't seem to much effort, but it implies in eventually creating some more css classes and I'm not sure I'm aware of all the project rules. The PR would likely be refused.

Anyway, I can try if you confirm that case 2 is what you're thinking of. It would be a good learning opportunity for me.

**Comment by julianobrasil** [comment]
Oh, I got it. I missed the part you wrote "Need to use an ElementRef instead of a reference to MatSlider"
