### ISSUE TITLE
mat-list-item doesn't have ripple when transcluded into mat-nav-list

### ISSUE THREAD

**Issue by tylerbrockett** [angular/material2#9396]
#### Bug, feature request, or proposal:

mat-list-item element doesn't have ripple when it is transcluded into 
```
<mat-nav-list>
    <ng-content></ng-content>
</mat-nav-list>
```

#### What is the expected behavior?

`<mat-list-item>` element should have ripple

#### What is the current behavior?

`<mat-list-item>` doesn't have ripple

#### What are the steps to reproduce?

[Plunker Link](http://plnkr.co/edit/bXRCe5eTr4n2YljeM1L4?p=preview)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Tested on:
Material 5.0.4
Angular 5.2.0
Windows 10
Chrome 63.0.x

**Comment by DevVersion** [comment]
Technically the behavior is correct. Ripples are only shown for `mat-list-item` elements that are part of a `<mat-nav-list>`.

Since Angular instantiates the `<mat-list-item>` before the transclusion happened, the list-item isn't able to figure out that it's part of a `<mat-nav-list>`. The list item just checks using dependency injection if there is a parent `MatNavList` instance.

```html
<custom-component>
  <mat-list-item>
    Doesn't have ripple
  </mat-list-item>
</custom-component>
```
