### ISSUE TITLE
Does my material/core is broke ? No OverlayContainer

### ISSUE THREAD

**Issue by Etitrane** [angular/material2#949]
#### Bug, feature request, or proposal:

I try to use the menu component but i can't import the "OverlayContainer" from material/core
I checked the content of my material/core and it is different from the one i see on the git page. 

I used the following line to install my material/core:
npm install --save @angular2-material/core

I already use other components such as sidenav, toolbar etc.. everything works fine, but i can't find a way to use the menu 

#### What is the expected behavior?

get the material/core i see on the git 

#### What is the current behavior?

get a "light" material/core without OverlayContainer (and lot of other objects missing)

Thanks for your help
(I'm new to all this stuff, sorry if it is a really basic problem)

**Comment by Daeluse** [comment]
I might be wrong, but I believe the current NPM release of this repository is quite a few commits behind. As such, many of the modules, such as '@angular2-material/menu' are not yet available from npm. You have the option to compile a release from your self by downloading the src from this repository, and passing the source files into your application.

**Comment by teleaziz** [comment]
+1, I had to lock the version to 2.0.0-alpha.6 to make it work

**Comment by paralin** [comment]
When is another release going to come out?

**Comment by fxck** [comment]
I'm only guessing, since giving the community updates on what's going isn't really a thing in this project. But I think they won't release until 

a) angular2 rc.5 is out, because `@NgModules`
b) dialog is done, since it's already in master, but it's at the moment missing backdrop and docs, and none was working on those, because the guy assigned was working on porting all other components to NgModules
c) slider have docs
d) some of these are merged https://github.com/angular/material2/pulls most of them looks merge ready, it's most likely just that none had time to review and merge them

**Comment by jelbourn** [comment]
@fxck Astute observations :)

@Etitrane indeed menu is not released not; it is still a work in progress. Same goes for dialog. An alpha.7 will be released very soon with the slider, some ripples, button-toggles, and NgModule support.
