### ISSUE TITLE
mat-tab-group doesn't show styles for default tab selected

### ISSUE THREAD

**Issue by ATakaSKY** [angular/material2#9540]
#### What is the current behavior?
There are three tabs:`label1`, `label2` and `label3`. Inside each one of them there is another set of tabs. Now by default `label1` shows the selected style as well as `tab1` inside of it. Now once I click on another label like `label 2` another set of tab loads but none of them shows tab label highlighted. Same goes for `label3`. I explicitly have to click on the tabs to see the styles.

#### What is the expected behavior?
Tab labels inside of  `label 2` and `label 3` should also show highlighted tab labels.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-tyjslw?file=app/tabs-template-label-example.html

**Comment by MNorgren** [comment]
I am also having this issue. Seems like when visibility is toggled, the styles aren't being applied. Ive tried using a .hide class instead of *ngIf, but that doesnt fix it either. Any current workarounds that anyone knows of?

**Comment by amcdnl** [comment]
Explanation: Tab content is eagerly loaded by default. The tabs use dom size/position calculations for animations, since the tabs are loaded when the content is not visible it causes this side effect. This can be resolved by lazy loading the tabs which is capable as of: https://github.com/angular/material2/pull/8921
