### ISSUE TITLE
 Possibility to add "dialog" with the NPM packages ?

### ISSUE THREAD

**Issue by bastienlemaitre** [angular/material2#958]
Hi,
It's possible to add dialog to the npm package please ?
Thanks !

**Comment by vapits** [comment]
This is something that is really needed (among others) but I think the issue here is not the dialog itself but a better releases strategy as a number of fixes and new features is merged on master but it is impossible to get to your project.

Let's hope team will think about this as soon as possible/

**Comment by fxck** [comment]
It's not on npm yet and I don't think it's really finished either, it's still more of a skeleton.

**Comment by jelbourn** [comment]
Indeed- dialog is still in-progress and will be released when it is closer a complete initial version.
