### ISSUE TITLE
mat-card not responsive for small screens

### ISSUE THREAD

**Issue by NagPraveen** [angular/material2#9589]
#### Bug, feature request, or proposal:
mat-card is not responsive when it is loaded in a small screen in the browser. 

#### What is the expected behavior?
mat-card should adjust width of image/content inside the card or should give a scroll bar at bottom end of card.

#### What is the current behavior?
Only portion of content in the card is visible.

#### What are the steps to reproduce?
1.open material design page and go to examples> card.
    Link: https://material.angular.io/components/card/examples
2.Resize browser to a small screen resolution.

![material-bug1](https://user-images.githubusercontent.com/29298342/35373742-deff9d3c-01c5-11e8-801c-5940fdd8c02b.PNG)

![material-bug2](https://user-images.githubusercontent.com/29298342/35373741-decc876c-01c5-11e8-8a1e-983cab1e64cb.PNG)

**Comment by donroyco** [comment]
That's because `.example-card` has a set width of `400px` ([see CSS reference](https://github.com/angular/material2/blob/master/src/material-examples/card-fancy/card-fancy-example.css#L1)). If you remove it, the card is responsive (again).

![screen shot 2018-01-25 at 08 33 47](https://user-images.githubusercontent.com/1763537/35376271-8e767464-01aa-11e8-8a91-c201432b3e00.png)
