### ISSUE TITLE
MatTooltip show() behaves like toggle()

### ISSUE THREAD

**Issue by marzn** [angular/material2#9598]
#### Bug, feature request, or proposal:
MatTooltip.show() behaves like I expect it from MatTooltip.toggle()

#### What is the expected behavior?
show() should not toggle the tooltip, but shows it, independent if it is shown or hidden actaully.

#### What is the current behavior?
show() toggles the view

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-qqg9qp

#### What is the use-case or motivation for changing an existing behavior?
Meet the expected behaviour for the methods

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Firefox 57 & 58, Chrome 64

**Comment by crisbeto** [comment]
AFAIK what you're seeing here is the tooltip's behavior where it closes on any click.

**Comment by andrewseguin** [comment]
@crisbeto is right, looks like you are mistaken due to the click you are performing. Material design spec states that clicks should close the tooltip.

See the code here for show, which doesn't have any toggle-behavior: https://github.com/angular/material2/blob/master/src/lib/tooltip/tooltip.ts#L256
