### ISSUE TITLE
(portal) use cases

### ISSUE THREAD

**Issue by fxck** [angular/material2#964]
It's not quite clear to me from the docs whether portal can do this(and how): 

I have a component, `<modal>`, with `@Input` for the state and `@Output` for close event. Now I add this component in a nested route component, so the path is..

> app > someroute > someotherroute > modal

..and I would like the modal to be rendered inside `app` while still getting it's inputs from and emiting events to`someotherroute`.

Can portal do that?

**Comment by jelbourn** [comment]
For now we consider `Portal` to be an internal API, which is why it doesn't have any real docs. It will someday graduate to a standalone supported thing once we build more stuff on top of it to validate that the concept is sound.

The gist is that a portal is a wrapper around a component or a `TemplateRef` that you can pass around to render wherever you want (in a `PortalHost`). It sounds like it would work for your use-case; check out the code in our (in-progress) dialog for an idea of how portals work.

**Comment by fxck** [comment]
@jelbourn would you mind creating a simple plunk with something similar to what I described? I tried looking at the dialog code, but there's way too much going on. What I can't quite wrap my head around is how can I make a single `portalHost` pick up any of my `modal` components as I'm navigating around.. or do I need one `portalHost` per component?
