### ISSUE TITLE
How hide / replace the table header with custom template??

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [angular/material2#9798]
#### Feature request, or proposal:

Looking for a feature on a selectable rows table, where on selecting the rows I need to replace the columns header with the new header with custom HTML template say, the new header will accommodate the data about the rows selected and few icons to do a bulk operation on all the selected rows at a time.

#### What is the expected behaviour?

Replace the Column header with custom header, on selecting rows.Any suggestions, please.

**Comment by andrewseguin** [comment]
If I were in your shoes, I may push back on the UX designer and say that column headers should not disappear on selection. You may be thinking about a table header that is changing (see Material Design spec that talks about selection)

That said, if you want to change the header to show other content, it's trivial to change what is displayed. Rather than passing it the standard set of columns to show, just pass in a single column definition with a header cell that contains what you want to display. 

Check out this example for help: https://stackblitz.com/edit/angular-uqsh69?file=app/table-basic-example.html
