### ISSUE TITLE
Stackblits examples error

### ISSUE THREAD

**Issue by demisx** [angular/material2#9805]
Many examples (basic sidenav, basic drawer, etc.) on https://material.angular.io/components/sidenav/examples don't work in the linked stackblits. The error thrown is shown in the attached image.

![stackblitz-error](https://user-images.githubusercontent.com/4452412/35867684-411286ae-0b0f-11e8-905a-0c2902f6354a.jpg)

Also, the example pages were more useful when the examples were embedded right into the page before.

**Comment by Chan4077** [comment]
Looks like it's because the Angular Material version is fixed to `5.0.0-rc.3` and they're trying to import `MatDividerModule` into the modules even though it doesn't exist at that version and that causes the problem... #fails
[More info](https://github.com/angular/material.angular.io/blob/427d757ad63840d5040e60909f40f2dd3e80fd94/src/app/shared/stackblitz/stackblitz-writer.ts#L24)
I'll try to submit a PR for this.

**Comment by donroyco** [comment]
@Chan4077 See also #9380

**Comment by Chan4077** [comment]
@demisx @donroyco I've created a PR for the issue
