### ISSUE TITLE
mat-autocomplete causes lags and crashes with 5k items

### ISSUE THREAD

**Issue by consq** [angular/material2#9854]
#### Bug, feature request, or proposal:
I'm trying to use the mat-autocomplete to show up about 6000 cities,when i enter the first char in input it gives a load delay and lag for about 3-4 seconds,the same happens when i'm clearing it back to empty means it should load all of the cities,probably the problem is caused because of much data items should be displayed,is there any way to make a limit to speed up first char search?Thanks

#### What is the expected behavior?
mat-autocomplete should pull the data without any slow downs or lags,at least just a small delay
#### What is the current behavior?
mat-autcomplete makes chrome even crash sometimes when loads the huge amount of data

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Load the mat-autocomplete with over 5000 items

#### What is the use-case or motivation for changing an existing behavior?
it would be really useful if everyone could use the mat-autocomplete for even huge amount of data
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material 5.2.0 angular 5.2.2

**Comment by josephperrott** [comment]
Closing as the list of displayed items in the autocomplete is not controlled by the autocomplete but by the end user.  With this being the case it is not something that can be addressed from within the Material library.

**Comment by Raulkg** [comment]
What is the solution to overcome this lag ?? Please suggest .

**Comment by thw0rted** [comment]
You need to limit the amount of items being provided to the autocomplete.  In [the docs example](https://material.angular.io/components/autocomplete/overview) you're creating one `mat-option` for each option in the `options` property of the component.  If there are 5k items in `options`, you're gonna have a bad time.  This is nothing to do with Material, it's just basic DOM: adding thousands of DOM elements at once is always a recipe for terrible user experience.

Look at the example under [Adding a Custom Filter](https://material.angular.io/components/autocomplete/overview#adding-a-custom-filter).  The component has a collection (`options`) with all possible values, and an Observable (`filteredOptions`) which emits a view over that collection, filtered by the user's typed text.  You can improve this by e.g. returning an empty collection (= no autocomplete options) until the user has typed 2 or 3 characters, so that you won't have to return too many items, or you can just sort/slice the filtered options to limit how many will be shown to the user at a time.
