### ISSUE TITLE
<mat-checkbox> class not updating to ng-invalid

### ISSUE THREAD

**Issue by gauravsoni1** [angular/material2#9923]
#### Bug, feature request, or proposal:

The first time the component loads , the class is ng-invalid , if i check and uncheck the checkbox. The class does not update to ng-invalid. 
I am using the reactive form.
I have set the Validators.required for this componenet

#### What is the expected behavior?
Class should update to ng-invalid 

#### What is the current behavior?
Class is ng-valid , even though it should be ng-invalid

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

StackBlitz - https://stackblitz.com/edit/angular-material2-issue-jlarze

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": "^5.2.0"

**Comment by tinayuangao** [comment]
@gauravsoni1 Could you please provide a StackBlitz reproduction?

**Comment by gauravsoni1** [comment]
@tinayuangao - added Stackblitz to the issue.

**Comment by tinayuangao** [comment]
@gauravsoni1 
See https://stackblitz.com/edit/angular-material2-issue-ftuvb7?file=app/app.component.ts

If you use `Validators.required` the form control will be valid when the checkbox value is `false` (the value when you uncheck the checkbox). This is because `false` is still a valid answer.

Use `Validators.requireTrue` to make form control invalid when checkbox is false.

**Comment by zencakd** [comment]
Validators.requireTrue works but it necessary to alter the class manually to render the checkbox as invalid in html. Should not checkbox behave in the same way as invalid input?
